Display login logos instead of combo box
NYPL-Simplified/circulation-patron-web pull request #115
Opened 2020-08-17 21:40 UTC by M0nica

- Display login logos instead of combo box when there are fewer than 5 AuthProviders
- When there are 1-4 AuthProviders show Auth buttons instead

2020-08-18 09:39 UTC, kristojorg commented on src/auth/BasicAuthButton.tsx
> +  }
This isn't a huge deal in this case, but for the future I try to steer clear of declaring let variables as it becomes difficult for developers to track their value when code becomes complicated. I personally would change this to:
```
const imageUrl = props.links.find(link => link.rel === "logo").href
```

2020-08-18 09:41 UTC, kristojorg commented on src/auth/BasicAuthButton.tsx
> +        mr: 0,
I assume this is so that you can have multiple in a list? Does this work if it breaks from a horizontal to a vertical list? If not, you might look at using the `Stack` component in whatever component is consuming this one. That one is supposed to space children evenly and allow horizontal to vertical wrapping

2020-08-18 17:31 UTC, M0nica commented on src/auth/BasicAuthButton.tsx
> +        mr: 0,
The AuthButton is currently only used in the `<ul>`  in the Auth modal so it should always be displayed as a stacked horizontal list. I'll look into replacing the `<ul>` with the `Stack` component.

2020-08-19 07:48 UTC, kristojorg commented on src/components/Auth.tsx
> +}
Can you type the arguments to these functions?

2020-08-19 10:42 UTC, kristojorg commented on src/auth/BasicAuthButton.tsx
> +const BasicAuthButton = props => {
Can you type this component please?

2020-08-19 10:42 UTC, kristojorg commented on src/auth/BasicAuthButton.tsx
> +        mr: 0,
Within a stack I think you shouldn't need to add these custom spacings to make them line up

2020-08-19 10:43 UTC, kristojorg commented on src/auth/BasicAuthButton.tsx
> +        backgroundSize: `280px 51px`,
Are we doing this so that the button is the same height as the clever background image? If so, maybe we should extract this style and apply it to all of the buttons on this form so they're all of uniform size?

2020-08-19 10:44 UTC, kristojorg commented on src/components/Auth.tsx
> +    [][0] as AuthProvider<AuthMethod>
I don't really understand what's going on here. What is the shape of this state meant to be now?

2020-08-19 10:44 UTC, kristojorg commented on src/components/Auth.tsx
> +        ([][0] as AuthProvider<AuthMethod>)
Why is it now necessary to cast this everywhere. Casting is generally an escape hatch or to be used with values from outside our typescript environment (like when making a network request and receiving some value).

2020-08-19 10:45 UTC, kristojorg commented on src/components/Auth.tsx
> +            <div sx={{ mb: 2, textAlign: `center` }}>
You can apply this styling directly to the stack and get rid of the wrapping div I believe

2020-08-19 10:46 UTC, kristojorg commented on src/components/Auth.tsx
> +                  listStyleType: "none"
Are these doing anything? I think the Stack has these set by default already

2020-08-19 10:50 UTC, kristojorg commented on src/components/Auth.tsx
> +                      )}
Is it possible to just define this as a `buttonComponent` in the `basicAuthProvider` and then you can just render the component and pass in the provider just like you're doing for clever. That way we aren't doing custom checks for different provider types and they all work the same way

2020-08-19 14:00 UTC, M0nica commented on src/auth/BasicAuthButton.tsx
> +        backgroundSize: `280px 51px`,
Yes, these measurements are so that it matches the size of the buttons' background images. I will look into making sure all of the buttons on the form are a uniform size.

2020-08-19 14:03 UTC, M0nica commented on src/components/Auth.tsx
> +    [][0] as AuthProvider<AuthMethod>
The default state of authProvider is being changed to be no provider instead of defaulting to the first provider. Although, if there is only 1 provider we'd want the default state to be that 1 provider which isn't explicitly handled at the moment but I  need to see if that is causing some of the issues you were seeing with button alignment. I am going to try to reproduce your above screenshot.

2020-08-19 14:05 UTC, M0nica commented on src/components/Auth.tsx
> +        ([][0] as AuthProvider<AuthMethod>)
in the case where there are no providers I wanted to cast it to an empty provider. I was running into a lot of other type issues when the provider was explicitly undefined but I can look into if there's another way to approach those type issues.

2020-08-19 15:45 UTC, kristojorg commented on src/components/Auth.tsx
> +    [][0] as AuthProvider<AuthMethod>
Okay so maybe just set it to `undefined` then yea? And set the type to be a provider or undefined:
```
React.useState<AuthProvider<AuthMethod> | undefined>(undefined);
```

2020-08-19 15:46 UTC, kristojorg commented on src/components/Auth.tsx
> +        ([][0] as AuthProvider<AuthMethod>)
See the comment I made above. Hopefully that helps?

2020-08-19 15:55 UTC, kristojorg commented on src/auth/BasicAuthButton.tsx
> +        backgroundSize: `280px 51px`,
Thanks : )

2020-08-19 15:55 UTC, kristojorg commented on src/auth/BasicAuthButton.tsx
> +        backgroundSize: `280px 51px`,
Maybe extract it into an `<AuthFormButton` that has those styles and then use that one for all of them?

2020-08-20 15:18 UTC, hokei commented
If you hit "cancel" on this modal, it doesn't look like hitting "sign in" brings it up again (or brings you to a sign in page).  It will show up again if you hit "refresh"

2020-08-20 19:54 UTC, M0nica commented
> This looks great in the gif! I think it still needs some massaging in some cases though. This is what I get with a single SAML provider:
> 
> ![image](https://user-images.githubusercontent.com/4398775/90606728-72d74300-e1bd-11ea-97a3-9a0666252d4d.png)
> 
> I think buttons should be aligned and the same size, and the first login button should have tab focus initially I think

I was able to reproduce some misalignment (although it looked different than the screenshot you shared) when the only provider option was Clever. I was then able to get the button to center in that case. Can you check if the new `ModalButtonStyles` I've applied to all of the buttons in the modal appear to resolve the alignment issue you were seeing? If not, I might need help reproducing in a SAML environment. 

![Screen Shot 2020-08-20 at 3 52 17 PM](https://user-images.githubusercontent.com/6998954/90819036-63f7aa00-e2fd-11ea-89ed-f90f81126a16.png)

2020-08-26 16:06 UTC, M0nica commented on src/components/Auth.tsx
> +    [][0] as AuthProvider<AuthMethod>
I was running into a lot of issues when re-typing the state value without casting 🤔

2020-08-26 17:05 UTC, kristojorg commented on src/components/Auth.tsx
> +                      onClick={handleChangeProvider as () => void}
The error this was giving you before casting it was actually pointing to a valid runtime error. The onClick method here was not guaranteed to provide an event object, and especially in this situation would not be a Select Event. Take a look at how I've changed it to see a safer way to approach this than casting

2020-08-26 17:07 UTC, kristojorg commented
I'm making a commit to remove the type casting, but I'm still seeing style issues. It looks like it has to do with the length of the library name making the modal wider than the one you're using in development:

![image](https://user-images.githubusercontent.com/4398775/91334524-6790a280-e7cf-11ea-8387-2672234b30b9.png)

2020-08-26 17:32 UTC, kristojorg requested changes
just this capitalization, the button styles in the modal still need some massaging with long library names, and also check the code with the updates that I pushed

2020-08-26 17:32 UTC, kristojorg commented on src/components/Modal.tsx
> +export const ModalButtonStyles = {
This shouldn't be capitalized. We only capitalize components and classes and types

2020-08-26 18:22 UTC, M0nica commented
I updated the styling to make sure the buttons are aligned with longer library names (manually changed the library name)
<img width="1440" alt="Screen Shot 2020-08-26 at 2 09 26 PM" src="https://user-images.githubusercontent.com/6998954/91341449-8713d500-e7a7-11ea-9535-47fee2bd429f.png">
<img width="1440" alt="Screen Shot 2020-08-26 at 2 09 22 PM" src="https://user-images.githubusercontent.com/6998954/91341450-87ac6b80-e7a7-11ea-82a6-e1294faf1c5b.png">
<img width="1437" alt="Screen Shot 2020-08-26 at 2 09 08 PM" src="https://user-images.githubusercontent.com/6998954/91341451-88450200-e7a7-11ea-99c6-356b14a9d403.png">
<img width="1440" alt="Screen Shot 2020-08-26 at 2 09 04 PM" src="https://user-images.githubusercontent.com/6998954/91341456-88dd9880-e7a7-11ea-90a7-db20cd108d7c.png">

2020-08-26 18:27 UTC, kristojorg approved these changes
looks good!

2020-08-26 18:34 UTC, M0nica commented on CHANGELOG.md
> +- Feature: Add support for Clever auth providers.
Clever auth was added in a previous PR but wasn't reflected in the CHANGELOG.

2020-08-26 18:42 UTC, merged