add visible focus to filled and ghost buttons
NYPL-Simplified/circulation-patron-web pull request #119
Opened 2020-08-25 16:23 UTC by M0nica

- focus was barely visible in Firefox since it was using browser defaults instead of styling from circulation-patron-web
- updated to use the same focus style as the Reakit button example: https://reakit.io/docs/button/#main

2020-08-25 16:28 UTC, M0nica commented on src/components/Button/styles.ts
> +          boxShadow: `0 0 0 0.2em rgba(0, 109, 255, 0.4)`
Is there a variable I can use here instead?

2020-08-25 16:37 UTC, M0nica commented on src/components/Button/styles.ts
> +          boxShadow: `0 0 0 0.2em rgba(0, 109, 255, 0.4)`
Right now the focus/hover styles are coupled but I am wonder if he boxShadow outline should only apply to focus and not hover.

2020-08-25 17:50 UTC, hokei commented
If this can wait, I'd wait until https://github.com/NYPL/nypl-design-system/pull/354 gets merged, tbh.  We're pulling in DS anyway, it means we don't have to maintain our own CSS for this kind of stuff (also IE fallback, etc)

2020-08-25 18:54 UTC, M0nica commented
> If this can wait, I'd wait until [NYPL/nypl-design-system#354](https://github.com/NYPL/nypl-design-system/pull/354) gets merged, tbh. We're pulling in DS anyway, it means we don't have to maintain our own CSS for this kind of stuff (also IE fallback, etc)

We're not currently using the DS buttons yet. Is the plan to convert from Reakit to DS once #354 is merged?

2020-08-26 12:23 UTC, kristojorg commented on src/components/Button/styles.ts
> +          boxShadow: `0 0 0 0.2em rgba(0, 109, 255, 0.4)`
I think it should only apply to focus, and I would put this in the theme object and then reference it that way

2020-08-26 12:25 UTC, kristojorg commented on src/components/Button/styles.ts
> +          boxShadow: `0 0 0 0.2em rgba(0, 109, 255, 0.4)`
I think you can add a second `&:hover` setting in addition to the shared `&:focus,&:hover`

2020-08-26 12:32 UTC, kristojorg requested changes
I am not totally sure, but I think there will be more work to do before we can use the DS buttons. Ours seem significantly different from the buttons I saw in DS before, because they allow for variants, icons, and different buttons for different purposes (anchor buttons, nav buttons, regular buttons)

The only change here is that the shadow should only be on focus and we should move the setting into the theme object as a variable. You can find out where to put it on the theme-ui website

2020-08-26 14:16 UTC, scooooooooby commented
> If this can wait, I'd wait until [NYPL/nypl-design-system#354](https://github.com/NYPL/nypl-design-system/pull/354) gets merged, tbh. We're pulling in DS anyway, it means we don't have to maintain our own CSS for this kind of stuff (also IE fallback, etc)

As an FYI on this PR, it is applying styling directly to browser elements over the DS components (a hold-out from grabbing this from the other DS we have at NYPL). Reading through this I think it's worth asking whether the PR over there should even be doing that.

That said, it does mean that the styling would get applied here regardless or whether or not you were using DS buttons or not—if you're using semantic `<button>`s, it will be applied.

2020-08-27 14:55 UTC, kristojorg requested changes
Just a small change

2020-08-27 14:55 UTC, kristojorg commented on src/components/Button/styles.ts
> +          boxShadow: shadows.focus
Once you've added it to the theme, you can simply do `boxShadow: "focus"` and it will pull in the value from the theme in context

2020-08-27 21:52 UTC, M0nica commented on src/components/Button/styles.ts
> +          boxShadow: shadows.focus
Great, thanks for sharing that syntax. I just updated it to `boxShadow: "focus"`.

2020-08-27 22:22 UTC, kristojorg approved these changes
Looks good!

2020-08-27 22:35 UTC, merged