Clever auth button needs to use AnchorButton
NYPL-Simplified/circulation-patron-web pull request #124
Opened 2020-09-02 17:03 UTC by M0nica

The Clever auth button currently has a <button> nested inside an <a> tag. This isn't proper semantic HTML, and it isn't a11y friendly. It also may cause bugs because it is possible to follow the anchor without causing a click event on the button. We need to make this component use an <AnchorButton> instead, which is designed for the purpose of an anchor that looks like a button.

2020-09-02 20:24 UTC, M0nica commented
> to fix the typecheck issue copy over this line: https://github.com/NYPL-Simplified/circulation-patron-web/pull/93/files#diff-e9f950f17198d3d5e3122a44230a09b9R50
> 
> (It's cuz typescript got updated so github ci is now using a different version than we are)

Thanks, that seemed to resolve TypeScript complaining about a file that's unrelated to my changes.

2020-09-02 21:11 UTC, hokei commented
I don't quite understand -- why isn't this a pure button?  What is `href={authUrl}` doing here?  There's no navigation, so why is it using an anchor in the first place?

2020-09-02 21:14 UTC, M0nica commented
> I don't quite understand -- why isn't this a pure button? What is `href={authUrl}` doing here? There's no navigation, so why is it using an anchor in the first place?

authUrl is the redirectUrl to get the circulation manager to handle authentication with Clever. It's an external link that redirects to the Clever login.

The user flow is: Click Clever button -> navigates to authUrl -> authUrl switches to clever auth callback url -> login -> are redirected back to open e-books.

2020-09-03 11:35 UTC, kristojorg commented
So then I guess I'm curious how both the external link and the `onClick` work together? Which one happens first? Do they both need to happen? Maybe it would be better actually to navigate programatically after saving the auth credentials with `window.open`?

2020-09-03 18:34 UTC, M0nica commented
> So then I guess I'm curious how both the external link and the `onClick` work together? Which one happens first? Do they both need to happen? Maybe it would be better actually to navigate programatically after saving the auth credentials with `window.open`?

I updated  to programmatically navigate to the authLink after saving the authCredentials

2020-09-07 08:43 UTC, kristojorg requested changes
Looks good, just a couple of changes

2020-09-07 08:43 UTC, kristojorg commented on src/auth/cleverAuthButton.tsx
> +export function getAuthUrl(provider, currentUrl) {
Please type the arguments to this function

2020-09-07 08:43 UTC, kristojorg commented on src/auth/__tests__/cleverAuthButton.test.tsx
> +describe("CleverButton", () => {
Can you add a test in here for whatever conditions cause it to render `null` (even if we weren't testing this before, I think we should have that code path covered).

2020-09-07 08:44 UTC, kristojorg commented
Also please update the changelog with a `- fix: xyz...`

2020-09-09 16:09 UTC, M0nica commented on src/auth/__tests__/cleverAuthButton.test.tsx
> +describe("CleverButton", () => {
I updated to add tests for the button (whether or not it renders based on if provider is passed in)

2020-09-09 16:26 UTC, kristojorg commented on src/auth/cleverAuthButton.tsx
> +  }
Do we really want to return an empty string here or should we return null? What is more clear for the caller of this function? Or do we not even want to accept the case where `provider` is `undefined` and handle that case upstream?

2020-09-09 16:27 UTC, kristojorg commented on src/auth/cleverAuthButton.tsx
> +  }
It looks like you're already testing for whether `provider` is defined below, so maybe change the arguments of the function so that it can't be `undefined` and then you shouldn't need this check at all I think?

2020-09-09 16:28 UTC, kristojorg commented on src/auth/cleverAuthButton.tsx
> +export function CleverButton({ provider }): JSX.Element | null {
Curious why you changed how this was defined? I think this leaves `provider` untyped in this definition. Seems like it should take the `AuthButtonProps<AuthMethod>` type

2020-09-09 16:29 UTC, kristojorg commented on src/auth/cleverAuthButton.tsx
> +        router.push(authUrl);
I'm actually not sure this is what we want to use. It's an external url isn't it? Does `router.push` work for external urls? Maybe check the nextjs docs

2020-09-14 15:18 UTC, M0nica commented on src/auth/cleverAuthButton.tsx
> +        router.push(authUrl);
`router.push` works for external urls but the nextjs documents recommend using window.location to navigate to external URLs so I have updated accordingly. https://nextjs.org/docs/api-reference/next/router#routerpush

2020-09-14 15:19 UTC, M0nica commented on src/auth/cleverAuthButton.tsx
> +export function CleverButton({ provider }): JSX.Element | null {
I updated the definition while trying to debug some issues with hooks errors in the unit tests but this change was not necessary so I have reverted.

2020-09-14 15:20 UTC, M0nica commented on src/auth/cleverAuthButton.tsx
> +  }
I just updated to make provider and currentUrl required inputs for the getAuthUrl function.

2020-09-14 15:21 UTC, M0nica commented on src/auth/cleverAuthButton.tsx
> +  }
Now when either, current location or provider is, undefined then the CleverButton will return null for the AuthUrl and when the AuthUrl is undefined the CleverButton doesn't render.

2020-09-16 12:28 UTC, kristojorg approved these changes
looks good to me

2020-09-16 15:16 UTC, merged