display loans from redux on MyBooks page
NYPL-Simplified/circulation-patron-web pull request #125
Opened 2020-09-02 20:18 UTC by M0nica

2020-09-03 11:38 UTC, kristojorg commented
Should we _only_ be checking `state.loans.books`? And then we shouldn't use `setCollectionAndBook` when rendering the component, but use the opds-web-client `fetchLoans` action instead? That seems like it's the way this is supposed to work and I'm not sure why I had it working with `state.collection` at all to be honest. Must have just been my mistake

2020-09-03 15:36 UTC, M0nica commented on src/components/MyBooks.tsx
> +      {!loans ? (
LoansState doesn't have a loading state https://github.com/NYPL-Simplified/opds-web-client/blob/ad836e0e6a1d94e34caca2427c1620729ac87861/packages/opds-web-client/src/reducers/loans.ts#L9 unlike CollectionState https://github.com/NYPL-Simplified/opds-web-client/blob/ad836e0e6a1d94e34caca2427c1620729ac87861/packages/opds-web-client/src/reducers/collection.ts#L15 so I'm not sure how to best handle the loading state.

2020-09-03 16:24 UTC, M0nica commented on src/components/MyBooks.tsx
> +      {!loans ? (
the test that is currently failing is related to the loading state ❌

2020-09-04 17:34 UTC, M0nica commented on src/components/MyBooks.tsx
> +      {!loans ? (
I wasn't sure if loading state can be removed since LoansState doesn't have a fetching/loading state?

2020-09-07 08:47 UTC, kristojorg requested changes
To me it looks like you can remove the local state and that will fix this issue

2020-09-07 08:47 UTC, kristojorg commented on src/components/MyBooks.tsx
> +  );
I'm curious why you introduced this state? Aren't the books already stored in redux state under `loans.books`? It seems like we can just use that but maybe there is a reason to do it this way instead?

2020-09-07 08:47 UTC, kristojorg commented on src/components/MyBooks.tsx
> +  }, [loans, loansUrl, actions, dispatch]);
This is going to fire off the fetchLoans network event every time the `loans` object changes (via reference equality), which doesn't seem like what we want or am I missing something?

2020-09-07 08:47 UTC, kristojorg commented on src/components/MyBooks.tsx
> +  }, [loans, loansUrl, actions, dispatch]);
Just checked and it is indeed creating an infinite loop:
![image](https://user-images.githubusercontent.com/4398775/92366203-21074600-f0f5-11ea-9ca9-df12eb1fd0d8.png)

2020-09-07 08:48 UTC, kristojorg commented
Also please update CHANGELOG with a `- fix: xyz...`

2020-09-07 08:49 UTC, kristojorg commented on src/components/MyBooks.tsx
> -      ) : !isSignedIn ? (
I think removing the loading state is confusing, but it's okay for now because this will all be replaced somewhat soon

2020-09-08 19:36 UTC, M0nica commented on src/components/MyBooks.tsx
> +  }, [loans, loansUrl, actions, dispatch]);
I just updated to select `state.loans` instead of using the `useEffect()`

2020-09-08 20:55 UTC, hokei commented on src/components/__tests__/MyBooks.test.tsx
> -test("shows loading state", () => {
why does loading state need to no longer show?

2020-09-09 12:03 UTC, kristojorg commented
I notice we are no longer calling `fetchLoans` at all. Does this work without that?

2020-09-09 14:48 UTC, M0nica commented
> I notice we are no longer calling `fetchLoans` at all. Does this work without that?

It seems to work with or without fetchLoans but I am re-adding to try to avoid stale loans

2020-09-09 15:00 UTC, kristojorg commented
Okay that's fine for now thanks

2020-09-09 15:39 UTC, kristojorg approved these changes
looks good

2020-09-09 16:15 UTC, merged