Testing docker push
NYPL-Simplified/circulation-patron-web pull request #142
Opened 2020-09-18 13:12 UTC by hokei

2020-09-22 22:00 UTC, hokei commented on Dockerfile
> +ENV NEXT_PUBLIC_COMPANION_APP=openebooks
From what I can understand, `process.env` doesn't read from the nodejs environment variables, which is what's set in ECS.  It reads them from here.  Therefore, the environment variables aren't set unless they're set here.  

I don't know if this is an ok place to put these environment variables - because the beta merge pushes a publish to `nypl/patron-web`, maybe it's ok to have it be Open Ebooks?  If not though, where else can we put these configs?  Do we need to not be reading `env.ts` from `process.env` ?   We should keep this in mind as we put together the configuration plan.

2020-09-22 22:02 UTC, hokei commented
@kristojorg I'm not sure if this is a good idea, but the current `beta` is also untenable as any push may cause a new deploy that breaks environment variables.

2020-09-23 12:34 UTC, kristojorg commented on Dockerfile
> +ENV NEXT_PUBLIC_COMPANION_APP=openebooks
So my understanding is that `nypl/patron-web` is to be the community version, and I don't think it should have (or be necessary to have) env vars hard coded that can't be changed when you actually run the docker container. I'm a bit confused what you mean when you say `process.env` doesn't read from the nodejs env vars... isn't `process.env` _the_ nodejs env vars?

2020-09-23 12:36 UTC, kristojorg requested changes
I agree we need to resolve the issues with the env vars before merging to master. However, I don't believe this is a suitable way to do it because it will bread non open-eBooks deployments by setting them to use Open eBooks. We need to have a way to set these env vars when running the docker container. Let's workshop this in our meeting today

2020-09-24 00:12 UTC, hokei commented
@kristojorg ok I'm stuuuumped.  
When putting everything in `publicRuntimeConfig`, it won't start up (it says `SIMPLIFIED_CATALOG_BASE` isn't defined).  So I moved it back to see if it works.  The thing is, when running with a local env file, it really does look like all the all the variables are set (in the docker desktop inspector) but it still doesn't show up in the browser 

![Screen Shot 2020-09-23 at 5 11 52 PM](https://user-images.githubusercontent.com/3579472/94086473-f0473200-fdbf-11ea-90af-ed17d43222b7.png)


This, of course, isn't happening when I'm just running it locally.  I'd love any and all insights ...

2020-09-24 10:00 UTC, kristojorg commented
Hmmmm okay I can try to give this some time today. But in general, process.env is only server side, so Nextjs _should_ be exposing those variables on window in the browser. Let me give this a look though

2020-09-24 10:03 UTC, kristojorg commented
I should test this by pulling the `test` tag and running that right?

2020-09-24 14:05 UTC, hokei commented
@kristojorg Yeah, pull the `nypl/patron-web:test` tag

2020-09-24 20:07 UTC, hokei commented
I think there's just some nextjs issues with env variables:  See 
https://github.com/vercel/next.js/issues/7713
and https://github.com/vercel/next.js/discussions/15651

I would love to chat tomorrow morning about stuff I found, and also how we might move forward, because I feel like I've spent way outsized amount of time on this already.

2020-09-25 10:27 UTC, kristojorg commented
Okay yea so! I read through all the issues and chatter. I did some testing. I think there _is_ a bug in next.js, but also we need to change the way we are doing this anyways. The reason is that in the near future (after the data layer rewrite), we will be generating some of the pages statically at build time (more on this later), which means that the environment variables will be read at build time, which means there can't be one docker image that everybody uses. Everyone needs their own build. 

So this is my solution: 

1. We move the building of docker images out of github actions and into the docker repository itself. We have a `nypl/openebooks` docker hub repository that has the openebooks env vars set up. Alternatively, NYPL can use Amazon ECR if to rebuild if that's easier for them (since it connects with ECS).
1. I will set it up similarly for Lyrasis, building our own image on beta and master tags. 
1. Anybody else looking to use this/run it will need to do the same. It's a bit unfortunate because it's asking people to go through one more step to build their own version of the app, but I think it's necessary because env vars really are set at build time with a static or partially static application.

2020-09-28 16:06 UTC, kristojorg commented on .github/workflows/publish-beta.yml
> +jobs:
Is this all new? I don't remember this getting commented out in beta

2020-09-28 16:08 UTC, hokei commented on .github/workflows/publish-beta.yml
> +jobs:
The checking out submodules is new, but most of this is commented out -- https://github.com/NYPL-Simplified/circulation-patron-web/blob/beta/.github/workflows/publish-beta.yml#L11

2020-09-28 16:10 UTC, kristojorg requested changes
A few changes! Does this work now though?

2020-09-28 16:10 UTC, kristojorg commented on jest.config.js
> +  setupFiles: ["<rootDir>/jest.setup.js"],
I don't think we want to change this

2020-09-28 16:10 UTC, kristojorg commented on jest.setup.js
> +jest.mock('next/config', () => () => ({ publicRuntimeConfig: mockEnvConfig }));
You should update `test-utils/setEnv` to do this and set the env var to whatever a tester needs

2020-09-28 16:10 UTC, kristojorg commented on src/pages/404.tsx
> -}
Why was this deleted?

2020-09-28 16:10 UTC, kristojorg commented on src/utils/env.ts
>    process.env.CACHE_EXPIRATION_SECONDS ?? "10",
Should this not also be in the publicRuntimeConfig? I think every env var should be there now

2020-09-28 16:10 UTC, kristojorg commented on tsconfig.json
> +  "exclude": ["node_modules", "config/srv", "jest.config.js", "jest.setup.js"],
Don't think we should do this

2020-09-28 16:11 UTC, kristojorg commented on .github/workflows/publish-beta.yml
> +jobs:
I see, I guess I missed that PR

2020-09-28 16:13 UTC, hokei commented on src/pages/404.tsx
> -}
gaaaah I totally thought I put this back in.

2020-09-28 17:55 UTC, hokei commented
Ran it again and it works!

2020-09-28 19:42 UTC, kristojorg requested changes
Just a couple more things

2020-09-28 19:42 UTC, kristojorg commented on next.config.js
> +    NEXT_PUBLIC_COMPANION_APP: process.env.NEXT_PUBLIC_COMPANION_APP,
I actually don't think these should be necessary here. The `NEXT_PUBLIC_` prefix does this implicitly, which is why I started migrating to use it

2020-09-28 19:42 UTC, kristojorg commented on package.json
> +    "build-and-start": "npm run build && npm run start",
The one other thing is that previously we got rid of all but runtime files when building the docker container. I don't know if this is still a requirement or not (I can ask lyrasis and maybe you can ask NYPL), but the function of it was to minimize the size of the image being run, because apparently that does have an impact on pricing

2020-09-28 19:44 UTC, kristojorg commented on package.json
> +    "build-and-start": "npm run build && npm run start",
What I was originally thinking is that once we confirmed this works, we would make a script file that does:
1. `npm run build`
1. `npm run prune`
1. copy `.next` and `package.json` over to a new directory
1. delete the old directory and everything in it
1. `npm run start` in the new directory

2020-09-28 19:54 UTC, kristojorg commented on package.json
> +    "build-and-start": "npm run build && npm run start",
I did confirm that Lyrasis would like this, but that it isn't blocking. You can add it in a follow on PR if you need to get this in ASAP

2020-09-28 21:44 UTC, hokei commented on package.json
> +    "build-and-start": "npm run build && npm run start",
let's confirm that the script actually works/deploys first.

2020-09-29 09:55 UTC, kristojorg approved these changes
Okay I'll approve if you wouldn't mind adding a ticket to remove unneeded files in the future!

2020-09-29 09:55 UTC, kristojorg commented
Also changelog please!

2020-09-29 14:14 UTC, hokei commented
OK filed https://jira.nypl.org/browse/SIMPLY-3135

2020-09-29 15:05 UTC, merged