#9: Collection and books
NYPL-Simplified/circulation-patron-web pull request #152
Opened 2020-09-28 21:28 UTC by kristojorg

2020-09-30 12:12 UTC, kristojorg commented on src/__tests__/computeBreadcrumbs.test.tsx
> -    expect(computeBreadcrumbs(data, history)).toEqual(expected);
Using the history in the breadcrumbs didn't work previously. I've removed it here and we will need to make a ticket to eventually make the breadcrumbs better using navigation history.

2020-09-30 12:14 UTC, kristojorg commented on src/components/BreadcrumbBar.tsx
> +      : [{ text: catalogName, url: catalogUrl }];
If there are no breadcrumbs, we default to the catalog root

2020-09-30 12:17 UTC, kristojorg commented on src/components/bookDetails/index.tsx
> +    }
We now parse server errors properly, yay!

2020-09-30 12:18 UTC, kristojorg commented on src/computeBreadcrumbs.tsx
> +export function hierarchyComputeBreadcrumbs(
This was copied over from opds-web-client

2020-10-02 17:55 UTC, hokei commented
![Screen Shot 2020-10-02 at 10 53 55 AM](https://user-images.githubusercontent.com/3579472/94954259-b94add80-049d-11eb-9065-763026db20fa.png)
![Screen Shot 2020-10-02 at 10 54 40 AM](https://user-images.githubusercontent.com/3579472/94954261-b9e37400-049d-11eb-9bee-cf15b5a26620.png)


Was this change intended?

2020-10-02 17:58 UTC, hokei commented
Logging in with Clever seems to be broken.  Maybe it happened in this, maybe it happened in the auth work previously.

2020-10-02 19:03 UTC, hokei commented on src/components/WebpubViewer.tsx
> +          const fulfillmentData = await fetch(webpubManifestUrl);
Something about this change is not passing in the username and password into this fetch.  As a result, `fulfillmentData` gets the "you are not logged in" value, and the book cannot be fulfilled.

2020-10-02 19:35 UTC, hokei commented on src/components/BookList.tsx
> +export const InfiniteBookList: React.FC<{ firstPageUrl: string }> = ({
+1 for the new name

2020-10-02 19:36 UTC, hokei commented on src/components/BookList.tsx
> +import { useSWRInfinite } from "swr";
what does swr stand for?

2020-10-02 19:37 UTC, hokei commented on src/components/BookList.tsx
> +      {isFetchingMore && <ListLoadingIndicator />}
Is this the same loading indicator on the initial list load, or is that loading indicator somewhere else?

2020-10-02 19:41 UTC, hokei commented on src/components/Collection.tsx
> +  const hasLanes = collection?.lanes && collection.lanes.length > 0;
Is it possible for collection to be null here?  Can we do a check under `useSWR` to throw an error and then eliminate the need to check every time we use collection?

2020-10-02 20:49 UTC, hokei requested changes
There's a few things that seem to be not working (most importantly, the fulfill link is being called without credentials)

2020-10-02 21:07 UTC, hokei commented on src/components/ListFilters.tsx
> +const ListFilters: React.FC<{ collection: CollectionData }> = ({
are these being used anywhere?  I'm having trouble finding references to it.

2020-10-03 11:16 UTC, kristojorg commented on src/components/BookList.tsx
> +import { useSWRInfinite } from "swr";
It stands for stale-while-revalidate, which is basically the cache strategy that this hook uses. It serves you the stale data while revalidating with the backend and then updating the UI once the new data comes in. You can see more on: https://swr.vercel.app/

2020-10-05 09:09 UTC, kristojorg commented on src/components/Collection.tsx
> +  const hasLanes = collection?.lanes && collection.lanes.length > 0;
It is possible for it to be `undefined`, when no data has been returned yet. I could return the loading state early in that case, if that's what you mean?

2020-10-05 09:14 UTC, kristojorg commented on src/components/BookList.tsx
> +      {isFetchingMore && <ListLoadingIndicator />}
This is supposed to only be shown when loading more... the reason is that the `<Collection>` component makes the initial request for the collection using SWR, and then we only render this infinite list if it has `books` instead of `lanes`. This infinite list then takes the collection url as the first page and requests it again. Since this initial url was already loaded by the `<Collection>` component, SWR returns the cached version immediately, therefore not showing this loading indicator. 

The initial loading indicator is in the `<Collection>` compoent

2020-10-05 09:32 UTC, kristojorg commented on src/components/ListFilters.tsx
> +const ListFilters: React.FC<{ collection: CollectionData }> = ({
They are not actually right now. I took them out at one point as we migrated to the new designs, but kept them in the codebase as I knew we would want them eventually. These are the filter selectors we will use to add the new filters for Open eBooks.

2020-10-05 09:45 UTC, kristojorg commented on src/components/WebpubViewer.tsx
> +          const fulfillmentData = await fetch(webpubManifestUrl);
Okay yep my mistake. I now pass the token in to this function from the main application so we can use it to fetch with. Previously it was stored internally in the `fetcher` class, which we no longer use.

2020-10-05 09:47 UTC, kristojorg commented
Okay, good catches. 

1. I fixed the missing background url on the FirstBook auth button. That was my mistake.
1. I passed the token in to the fetcher, though I haven't been able to test it yet because I don't know how to find a book I can open in the reader. Also, I had to add a new fallback state that is unfinished in case the user isn't signed in and gets to that point. How should we deal with that?

I haven't been able to reproduce the errors you sent me on slack, so let's go through those today

2020-10-05 13:56 UTC, hokei commented on src/components/Collection.tsx
> +  const hasLanes = collection?.lanes && collection.lanes.length > 0;
Yeah, I think it would be nicer (to look at) to return the loading state rather than checking if it's been loaded on every assignment

2020-10-05 13:58 UTC, hokei commented on src/components/ListFilters.tsx
> +const ListFilters: React.FC<{ collection: CollectionData }> = ({
ok I am putting filters in pretty soon so I was getting thrown by the fact that they were in the code but not showing up -- this is good to know!  Thanks!

2020-10-05 13:59 UTC, hokei commented
Oh is the Vercel integration new as of this PR and what is it supposed to do?

2020-10-05 19:30 UTC, hokei commented
Navigating to the login modal the first time is showing an error, even though I haven't tried logging in yet
![Screen Shot 2020-10-05 at 12 30 23 PM](https://user-images.githubusercontent.com/3579472/95123284-8fe0ba80-0706-11eb-81ed-d02620ab67d5.png)

(the icon on the right of the input is my password manager, so ignore that)

2020-10-05 19:33 UTC, hokei commented
in the search results page, does the loading indicator stop showing up if you've seen all the books

2020-10-05 20:44 UTC, hokei commented on src/dataflow/utils.ts
> +export default function extractParam(
Any reason why it has to be this way rather than an approach that takes advantage of https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams?  (Feel free to punt if this requires refactoring)

2020-10-05 20:46 UTC, hokei commented
there's a lot going on here and I'm not confident I fully understand all of it, but most of it looks reasonable to me -- I'm mostly concerned about the functional issues, and then I think it's more important to merge and move forward and fix bugs when we see them.

2020-10-06 07:51 UTC, kristojorg commented on src/dataflow/utils.ts
> +export default function extractParam(
So I may have written a misleading comment. This is to extract a parameter from what next.js gives us. These aren't search parameters so much as dynamic routes (the `library` and `bookUrl` in `/[library]/book/[bookUrl]`). The type that Next.js gives us for those is `string | string[] | undefined`, because they could technically somehow be an array of strings. So this function just takes the query returned by `useRouter` and extracts a specific value and narrows the type to `string | undefined`. TBH I think next.js is misusing `query` here, because they aren't search queries, they're url parameters. But alas

2020-10-06 11:42 UTC, kristojorg commented
> Oh is the Vercel integration new as of this PR and what is it supposed to do?

This was an experiment, but we've removed it.

> Navigating to the login modal the first time is showing an error, even though I haven't tried logging in yet

This is a tricky one. It has to do with the fact that I don't clear the credentials when login fails. I couldn't really figure out a solution before but I'll give it a fresh look today.

> in the search results page, does the loading indicator stop showing up if you've seen all the books (It currently seems like it will spin forever)

Good question... I looked and you were right it was a problem I tried to fix, and uncovered another problem with how I was detecting the end of the search results on scroll. I tried to fix it for a while and resorted to removing the auto fetch more functionality in favor of a "View More" button. I asked on slack if that's okay. If not, we should revisit this in a separate ticket I think.

I also merged in the tests so now we just have this one PR to juggle.

2020-10-06 14:35 UTC, hokei commented
> I tried to fix it for a while and resorted to removing the auto fetch more functionality in favor of a "View More" button. I asked on slack if that's okay. If not, we should revisit this in a separate ticket I think.

Even tho slack says it's ok, I think let's move this to a new ticket and have the perpetual loading icon just be a known bug for now.

2020-10-06 14:40 UTC, kristojorg commented
> Even tho slack says it's ok, I think let's move this to a new ticket and have the perpetual loading icon just be a known bug for now.

I already went ahead and moved to the "View more" button, because the issues were larger than just the loading more icon. It was perpetually fetching actually, which wasn't good. I think the way it works now should be okay

2020-10-06 16:00 UTC, hokei commented on src/components/WebpubViewer.tsx
> +    if (!response.ok || data.status) {
I'm getting this error when the response is 
{"status": 401, "type": "http://librarysimplified.org/terms/problem/credentials-invalid", "detail": "A valid library card barcode number and PIN are required.", "title": "Invalid credentials"}

which sends this page
![Screen Shot 2020-10-06 at 8 57 56 AM](https://user-images.githubusercontent.com/3579472/95226922-58c7e300-07b2-11eb-99a7-b263db8b0188.png)

When it would be great to show a nice message to the user

2020-10-06 16:01 UTC, kristojorg commented
Okay I added a loading state to the login modal so that when you go to the reader or loans page directly it will show you "Logging in..." until the loans are fetched. We can technically not show this at all and just wait until we get a 401 response from the server, but let's make a separate ticket for that

2020-10-06 16:02 UTC, kristojorg commented on src/components/WebpubViewer.tsx
> +    if (!response.ok || data.status) {
This _should_ be caught by an error boundary in production and show a message to the user. Let me test that though. How did you get to this state?

2020-10-06 18:28 UTC, hokei commented on src/components/WebpubViewer.tsx
> +    if (!response.ok || data.status) {
Was not able to reliably reproduce ... I feel ok punting it until it shows up again.

2020-10-06 18:51 UTC, hokei commented
FYI while tabbing, the infinite list still shows.  New ticket.

2020-10-06 20:32 UTC, hokei commented
one last thing:  Let's test the fetch more button just to make sure its behavior is documented/won't regress without us knowing.

2020-10-06 20:32 UTC, hokei commented
but otherwise, it looks good to me.

2020-10-06 21:20 UTC, kristojorg commented
> FYI while tabbing, the infinite list still shows. New ticket.

What do you mean? 

> one last thing: Let's test the fetch more button just to make sure its behavior is documented/won't regress without us knowing.

Will do

2020-10-06 21:23 UTC, hokei commented
> What do you mean?

If you tab down the list, you never get to the "see more" button.  Instead, it will continue to load the list as long as you keep tabbing.  This means that the experience for a keyboard user is not the same as the experience for a mouse user.

2020-10-06 21:24 UTC, kristojorg commented
Okay I added a test for the "View more" functionality

2020-10-06 21:26 UTC, hokei commented
teach me how to write tests this quickly

2020-10-06 21:28 UTC, hokei approved these changes
There are a bunch of `firstPageUrl="/fist-page"` typos but let's get this in!

2020-10-06 21:28 UTC, kristojorg commented
> If you tab down the list, you never get to the "see more" button. Instead, it will continue to load the list as long as you keep tabbing. This means that the experience for a keyboard user is not the same as the experience for a mouse user.

That is weird... it seems to work on my localhost. I can tab down the list and get to the "View more" button, then press enter and it loads more. Anyway, yea lets open a ticket for what you're seeing.

> teach me how to write tests this quickly

haha copy/paste mostly

> There are a bunch of firstPageUrl="/fist-page" typos but let's get this in!

urgh will fix before merging!

2020-10-06 21:29 UTC, merged

2020-10-06 21:32 UTC, hokei commented
> That is weird... it seems to work on my localhost. I can tab down the list and get to the "View more" button, then press enter and it loads more. Anyway, yea lets open a ticket for what you're seeing.

 I will verify this, my localhost might have been in a bad state.  Yay!