Return and Revoke
NYPL-Simplified/circulation-patron-web pull request #156
Opened 2020-10-13 10:13 UTC by kristojorg

This PR adds the ability to return books and cancel reservations

2020-10-13 10:14 UTC, kristojorg commented on src/components/CancelOrReturn.tsx
> +      setError("You muse be signed in.");
We shouldn't get here, but there is no way to make it impossible from a type perspective right now

2020-10-14 04:48 UTC, hokei commented on src/components/CancelOrReturn.tsx
> +      setError("You muse be signed in.");
spelling nit

2020-10-14 04:49 UTC, hokei commented on src/components/CancelOrReturn.tsx
> +      // if it works, we need to refetch our loans
? what does this mean?  Where does the refetching happen?

2020-10-14 04:55 UTC, hokei commented
So I notice return functionality isn't in the NYPL mocks, is this mostly to help us with our testing?  Should we show it by default on pages?  (If it's driven by libraries/etc I'm surprised it doesn't show up at least on the "my loans" page, that's where I'd expect to be able to return books)

2020-10-14 09:26 UTC, kristojorg commented on src/components/CancelOrReturn.tsx
> +      setError("You muse be signed in.");
How r u so good at spelling

2020-10-14 09:29 UTC, kristojorg commented on src/components/CancelOrReturn.tsx
> +      // if it works, we need to refetch our loans
Good catch, the `setBook` above does that work for us, this comment is outdated. `setBook` optimistically sets the returned book in our loans and then refetches them afterwards just to make sure we are properly sync'd up

2020-10-14 09:31 UTC, kristojorg commented
Yea this was requested by Lyrasis and also it was in some mocks from Marcus at some point I thought... idk. I just guessed. But yea ultimately it would be good to have this on the list view in the loans page once we redesign the list page

2020-10-14 09:38 UTC, kristojorg commented
I think we should show it though, it's necessary functionality for Open eBooks, I think they just never realized it wasn't already there tbh.

2020-10-14 17:06 UTC, kristojorg commented
Okay @hokei this should be ready when you are

2020-10-20 17:31 UTC, hokei commented on src/components/CancelOrReturn.tsx
> +      <Button
is it difficult to start moving these over to use DS buttons?  Just because then we don't need to worry about keeping them consistent re: font weight, etc.  (Haven't looked at the list refactor branch, but assume that's not there)

2020-10-20 17:34 UTC, hokei commented on src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
>      expect(utils.getByText("You have this book on loan.")).toBeInTheDocument();
Shouldn't this also expect the return button?

2020-10-20 17:35 UTC, hokei commented on src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
>      expect(utils.getByText("You have this book on loan.")).toBeInTheDocument();
If Open Ebooks should explicitly not have a return button, let's test for that.

2020-10-20 17:35 UTC, hokei commented on src/dataflow/opds1/parse.ts
> +function canReturnFulfillableBook(links: OPDSAcquisitionLink[]): boolean {
haha guessing this doesn't have at test

2020-10-20 17:37 UTC, hokei commented on src/types/opds1.ts
> +export const IncorrectAdobeDrmMediaType = "vnd.adobe/adept+xml";
wait am I understanding correctly that when something happens with the Adobe DRM, it will send back a resource with this media type?

2020-10-20 17:40 UTC, hokei commented on src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
> +  test("handles cancel reservation errors", async () => {
in general it'd be nice to figure out exactly what errored from the name of the test ... is this test checking that an error while cancelling reservations will return the document to the un-cancelled state?

2020-10-20 17:41 UTC, hokei commented on src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
> +  test("displays return button that calls apropriate url", async () => {
does there need to be something that checks when the return state errors?

2020-10-20 18:04 UTC, kristojorg commented on src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
> +  test("displays return button that calls apropriate url", async () => {
Good point, I can test for that also for that

2020-10-20 18:07 UTC, kristojorg commented on src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
>      expect(utils.getByText("You have this book on loan.")).toBeInTheDocument();
Ah yes, I was testing this in the parser.test.tsx, but I'll also add it here that there should _not_ be a return button here

2020-10-20 18:07 UTC, kristojorg commented on src/dataflow/opds1/parse.ts
> +function canReturnFulfillableBook(links: OPDSAcquisitionLink[]): boolean {
Ok you caught me... it does now though : )

2020-10-20 18:24 UTC, hokei commented on src/components/CancelOrReturn.tsx
> +      <Button
sounds good.  In the screenshots I was showing Marcus it looked like some of the text wasn't bolded, etc.  so that's why I brought it up.  But I'm happy to do it at some other point or whenever it makes life easier.

2020-10-21 13:59 UTC, hokei requested changes
Returns always seem to bounce the first time, but work the second time.  (Sent a video in slack)

2020-10-22 13:19 UTC, kristojorg commented
@hokei I believe this is only happening with reservations through overdrive, and it's a server issue. If you don't mind, could you test this with another book for now?

2020-10-22 13:44 UTC, kristojorg commented
I just debugged and we're opening a ticket to fix this on the server

2020-10-23 14:37 UTC, kristojorg commented
@hokei I'd love to get this in if possible! It's currently blocking us from merging the list design PR also. There is a ticket open to fix the bug you discovered in the CM

2020-10-26 12:29 UTC, hokei approved these changes

2020-10-26 15:18 UTC, merged