See More Block
NYPL-Simplified/circulation-patron-web pull request #168
Opened 2020-10-14 22:59 UTC by kristojorg

This is for the see more block at the end of a lane

2020-10-16 15:20 UTC, hokei commented
the right button doesn't seem to scroll to the end of the extra block:  
![Screen Shot 2020-10-16 at 8 19 54 AM](https://user-images.githubusercontent.com/3579472/96276928-77836200-0f88-11eb-91d1-eac524c4b7d3.png)

2020-10-16 15:22 UTC, hokei commented on src/components/__tests__/Lane.test.tsx
> +  expect(utils.getByTestId("lane-list").childNodes).toHaveLength(1);
So the rest of the cards aren't li ?

2020-10-16 15:26 UTC, hokei commented on src/components/bookDetails/__tests__/Recommendations.test.tsx
> +test("doesn't show recommendations if the lanes don't have enough books", () => {
is "enough books" defined by a constant somewhere or is it hardcoded?  If hardcoded, it would be nice to for the test name to show the expected number of books is so that if it's fails the title will be more informative.

2020-10-16 15:26 UTC, hokei requested changes
Mostly looks good, my main concern is with the screenshotted issue.

2020-10-19 14:36 UTC, kristojorg commented
> the right button doesn't seem to scroll to the end of the extra block:

Question: Had you recently resized the browser when you got to this state? I can't seem to get there without resizing the browser. It occurs when you do that because (I think) our lane scrolling calculations aren't being rerun on browser resize, which I think should be a separate ticket. Can you check if this works if you keep the same size browser from load to when you scroll? (Or maybe you did that any I'm just not able to reproduce)

2020-10-19 14:49 UTC, kristojorg commented on src/components/__tests__/Lane.test.tsx
> +  expect(utils.getByTestId("lane-list").childNodes).toHaveLength(1);
This is only when there are 0 books, it will still show the "See More" block

2020-10-19 14:50 UTC, kristojorg commented on src/components/bookDetails/__tests__/Recommendations.test.tsx
> +test("doesn't show recommendations if the lanes don't have enough books", () => {
Yep this is >1, I updated the test title : )

2020-10-19 15:49 UTC, hokei commented on src/components/__tests__/Lane.test.tsx
> +  expect(utils.getByTestId("lane-list").childNodes).toHaveLength(1);
why should it show the See More block when there are 0 books?  Shouldn't it just not show lanes with no books in them?

2020-10-20 17:02 UTC, kristojorg commented on src/components/__tests__/Lane.test.tsx
> +  expect(utils.getByTestId("lane-list").childNodes).toHaveLength(1);
Yea I guess you're probably right... although for some reason I didn't add that before

2020-10-20 17:02 UTC, kristojorg commented on src/components/__tests__/Lane.test.tsx
> +  expect(utils.getByTestId("lane-list").childNodes).toHaveLength(1);
I'll add it

2020-10-20 17:43 UTC, hokei approved these changes

2020-10-20 18:07 UTC, merged