Stable loans sort
NYPL-Simplified/circulation-patron-web pull request #176
Opened 2020-10-20 10:31 UTC by kristojorg

This simple fix corrects the way that the loans page would resort after a second when you click the page. If two books don't have availability defined, we sort by title, which makes the sort "stable", meaning that it will return the same output every time if it is given the same input.

2020-10-20 20:05 UTC, hokei commented on src/components/MyBooks.tsx
> +    // if both have defined availabilities, sort by date
What if it's the same date? Will that still be stable?

2020-10-20 20:10 UTC, hokei requested changes
see above comment

2020-10-21 13:16 UTC, kristojorg commented on src/components/MyBooks.tsx
> +    // if both have defined availabilities, sort by date
Good point, just added

2020-10-26 12:30 UTC, hokei approved these changes

2020-10-26 15:27 UTC, merged