Simply 3311 image optimization new
NYPL-Simplified/circulation-patron-web pull request #227
Opened 2020-12-04 22:17 UTC by kaplanmichael

2020-12-07 21:44 UTC, kristojorg requested changes
Looks great! And I think is going to be very helpful! Just a few things

2020-12-07 21:44 UTC, kristojorg commented on src/components/LazyLoadImage.tsx
> +      data-src={src}
Curious what this attribute does?

2020-12-07 21:44 UTC, kristojorg commented on src/components/LazyLoadImage.tsx
> +const LazyLoadImage: React.FC<LLImgProps> = LLImgProps => {
Can you rename the props parameter so that it is different from the interface name? I think it's fine to just name it `props` or you can even destructure it right there if you'd like:

```ts
const LazyLoadImage: React.FC<LLImgProps> = ({ src, alt, ...otherProps }) => { ... }
```

2020-12-07 21:44 UTC, kristojorg commented on src/components/LazyLoadImage.tsx
> + * pixel of the image becomes visible in the viewport.
I think we should change this so that the image begins loading when it is some distance away from the viewport. I'm not sure what the threshold should be exactly, but the idea is that the user rarely sees an image in the process of loading when they're scrolling because they're already loaded

2020-12-07 21:44 UTC, kristojorg commented on src/components/BookCover.tsx
> +      <LazyLoadImage
nit: Personally I would name this `LazyImage` because otherwise it sounds like a verb, which doesn't seem right as a component name

2020-12-07 21:56 UTC, kristojorg commented
I just tested it, and it looks like this one change reduces the amount of image data loaded on the catalog root page from 1.3MB to 250kB! That's huge!

2020-12-07 21:57 UTC, kristojorg commented
I would also put a test and mock `useInView` to make sure that when it returns true, the source is in fact added to the image (and conversely it is undefined otherwise).

2020-12-07 22:02 UTC, kristojorg commented
Total size of network requests decreased by half from ~3MB to ~1.5MB.

2020-12-08 19:44 UTC, kaplanmichael commented on src/components/LazyLoadImage.tsx
> +      data-src={src}
Good catch.  That was a remnant of an earlier implementation I had tried and eventually changed.  I've removed that property now.

2020-12-08 19:48 UTC, kaplanmichael commented on src/components/LazyLoadImage.tsx
> +const LazyLoadImage: React.FC<LLImgProps> = LLImgProps => {
Great idea! Done!

2020-12-08 19:50 UTC, kaplanmichael commented
> Total size of network requests decreased by half from ~3MB to ~1.5MB.

...And this is just the beginning [of ways we can optimize] !!

2020-12-08 19:54 UTC, kaplanmichael commented on src/components/BookCover.tsx
> +      <LazyLoadImage
Fixed!

2020-12-08 21:53 UTC, kaplanmichael commented on src/components/LazyLoadImage.tsx
> + * pixel of the image becomes visible in the viewport.
Yes that makes complete sense.  I've gone ahead and made this fix for when the user is scrolling vertically.  In order to also do this for horizontal scrolling, however, I would need to refactor a bit.  Let me know if it makes sense to do that here or in a different PR.

2020-12-08 22:35 UTC, kristojorg commented on src/components/LazyLoadImage.tsx
> + * pixel of the image becomes visible in the viewport.
I think it's fine to leave the horizontal scrolling work to a separate ticket for now. We might actually just leave it and see if people like it as it before refactoring to make that change.

2020-12-08 22:40 UTC, kristojorg approved these changes
Looks good! We can merge once you fix the lint error 

PS. I set my editor (VSCode) to run format on save using eslint, which automatically fixes these prettier errors for me

2020-12-09 17:34 UTC, kaplanmichael commented on src/components/LazyLoadImage.tsx
> + * pixel of the image becomes visible in the viewport.
👍

2020-12-09 20:28 UTC, kaplanmichael commented
> I would also put a test and mock `useInView` to make sure that when it returns true, the source is in fact added to the image (and conversely it is undefined otherwise).

Done!

2020-12-09 20:43 UTC, kristojorg approved these changes
Tests look great! Just the one typefix and we're good!

2020-12-09 20:43 UTC, kristojorg commented on src/components/__tests__/LazyImage.test.tsx
> +};
You'll need to type the parameters to this function, probably this will work:
```
const HookComponent = ({ options }): Parameters<typeof useInView> => { ... }
```

2020-12-11 18:50 UTC, merged