Open eBooks Custom Login Page
NYPL-Simplified/circulation-patron-web pull request #228
Opened 2020-12-07 13:40 UTC by kristojorg

This is a custom `LoginPicker` for Open eBooks that shows some documentation of the two available login methods (taken from the home page).

2020-12-07 13:42 UTC, kristojorg commented on src/auth/LoginPicker.tsx
> +import * as React from "react";
This file is simply extracted from the home page

2020-12-07 13:43 UTC, kristojorg commented on src/auth/OpenEbooksLoginPicker.tsx
> +/** @jsx jsx */
This file is extracted from `/components/OpenEbooksLanding.tsx`

2020-12-11 18:23 UTC, kaplanmichael requested changes

2020-12-11 18:23 UTC, kaplanmichael commented on src/auth/LoginPicker.tsx
> +  );
If I click one of the buttons, proceed to its login form, and then click the browser's back button, I see a version of the login page where the buttons do not appear properly and any subsequent activity will fail:
![image](https://user-images.githubusercontent.com/6432596/101938699-cbd64700-3bb1-11eb-9535-e7b2459365bb.png)

![image](https://user-images.githubusercontent.com/6432596/101938777-f32d1400-3bb1-11eb-8b62-98b8d9fd7f03.png)

2020-12-11 18:51 UTC, kristojorg commented on src/auth/LoginPicker.tsx
> +  );
This is a symptom of the ip address circ manager error that is being resolved elsewhere

2020-12-15 12:53 UTC, kristojorg commented on src/auth/LoginPicker.tsx
> +      ))}
Okay so the buttons and the logo were actually meant to be left-aligned according to the design (at this width). So I've updated to do that and I think it looks better. I also fixed some other design stuff like you pointed out. Should be more in line with the design specs now

2020-12-15 21:50 UTC, kaplanmichael commented on src/auth/LoginPicker.tsx
> +  );
Can't wait! :)

2020-12-15 21:55 UTC, kaplanmichael commented on src/auth/LoginPicker.tsx
> +      ))}
Looks great now!

2020-12-15 21:56 UTC, kaplanmichael approved these changes

2020-12-16 11:56 UTC, merged