Lazy React AXE
NYPL-Simplified/circulation-patron-web pull request #231
Opened 2020-12-07 22:33 UTC by kristojorg

When testing @kaplanmichael 's recent lazy image PR, I noticed we were still loading React-AXE in production... even though it wasn't being run. This was bloating our first load JS from 223kB to 351kB, an almost 60% increase! This happened because of how we checked for development. We need to keep it simple for webpack's tree shaking, and this change fixes it.

2020-12-10 21:16 UTC, hokei commented
Oh my god!  😬 
(PS I'm good with this but I'll leave it to Michael to approve)

2020-12-11 19:28 UTC, kaplanmichael requested changes

2020-12-11 19:28 UTC, kaplanmichael commented on src/pages/_app.tsx
> +import { IS_SERVER, REACT_AXE } from "../utils/env";
Looks good.  I did notice that this package is now deprecated on NPM though.  Is there an alternative or an updated version we should be using?

2020-12-11 19:30 UTC, kaplanmichael commented on CHANGELOG.md
Seems to be a merge conflict here.

2020-12-14 17:13 UTC, kristojorg commented on src/pages/_app.tsx
> +import { IS_SERVER, REACT_AXE } from "../utils/env";
Yea good point, I believe it just moved to a different name but I will install the updated version

2020-12-15 11:47 UTC, kristojorg commented
Installed the updated version @kaplanmichael thanks for finding that

2020-12-15 21:58 UTC, kaplanmichael approved these changes

2020-12-16 11:55 UTC, merged