SimplyE Library Registry Support
NYPL-Simplified/circulation-patron-web pull request #238
Opened 2020-12-17 13:54 UTC by kristojorg

JIRA Ticket: [SIMPLY-3385](https://jira.nypl.org/browse/SIMPLY-3385)

The goal of this PR is to complete support of having a library registry as a source of libraries for the app so that we can deploy the community version with all the libraries on the SimplyE registry. It does a few things to accomplish that:

1. If a registry base is provided in the CONFIG_FILE.libraries, we fetch that and parse it into an object of library configs the app can understand
2. Instead of using the `Error` page for `/` on non open-ebooks setups, I made a new `MultiLibraryHome` which just shows the instance name and allows you to select a library from the list. We can update the interface if anyone has suggestions.
3. Because we now fetch a list of all the libraries from the registry at build time, I could get rid of code used to handle registries at runtime. woohoo!

2020-12-17 14:23 UTC, jonathangreen commented
> Because we now fetch a list of all the libraries from the registry at build time, I could get rid of code used to handle registries at runtime.

Is this implication of this that we will need to redeploy every time a library gets added/removed from the registry?

2020-12-17 14:44 UTC, kristojorg commented
@jonathangreen yes, good point. That is indeed the implication, though triggering that redeploy would not be difficult. I have a vercel webhook you can send a GET request to for any given branch that will trigger a fresh deploy.

2021-01-22 16:15 UTC, kaplanmichael requested changes
Looks great!  I see there's just a small conflict in the readme file.

2021-01-25 12:37 UTC, kristojorg commented on community-config.yml
> +instance_name: Patron Web Catalog - Community Demo
That's because we are now publishing the community instance, running the community config under librarysimplified.org. It's not meant to be used as a production app, but rather as a demo for libraries to see how it works

2021-01-25 12:41 UTC, kristojorg commented on src/config/fetch-config.js
>      throw new Error("Config file not found at: " + configFilePath);
So I did this uncousciously back when I made the file, but now that I think about it my reasoning was basically because this file gets run as part of building the application, not at runtime, so I kind of wanted its naming to match the files you see at the project root more than the ones that are part of the application. Idk if it's a useful distinction or not though.

2021-01-29 21:39 UTC, kaplanmichael approved these changes

2021-01-29 21:39 UTC, kaplanmichael commented on community-config.yml
> +instance_name: Patron Web Catalog - Community Demo
👍

2021-01-29 21:39 UTC, kaplanmichael commented on src/config/fetch-config.js
>      throw new Error("Config file not found at: " + configFilePath);
👍

2021-01-30 08:44 UTC, merged