[SIMPLY-3318] Add catalog button on openE home page.
NYPL-Simplified/circulation-patron-web pull request #239
Opened 2020-12-22 15:39 UTC by kaplanmichael

2020-12-22 22:46 UTC, kaplanmichael commented
I tried adding a test to verify the functionality of the theme prop, but had no luck.  If I'm not mistaken, it seems related to us using CSS variables for our colors.  Let me know if you can think of a way to achieve this.

2020-12-23 13:29 UTC, kristojorg requested changes
Looks good, just a couple changes

2020-12-23 13:29 UTC, kristojorg commented on src/components/SignOut.tsx
> +}: SignOutProps) => {
If we're going to do this, I would rather add it as a color to the `Button` component, as in make the `Button` set it's own `color` to white when it's background is black. Can be done in `components/button/styles` I think

2020-12-23 13:29 UTC, kristojorg commented on src/components/OpenEbooksLanding.tsx
> +              <AnchorButton
The style of this button is a little off on hover. I think similar to my suggestion with `SignOut` we should make the button handle a white `color` prop in `components/button/styles`

2020-12-23 13:29 UTC, kristojorg commented on src/components/OpenEbooksLanding.tsx
> +                href={libraryLinks.libraryWebsite?.href}
So this sort of works, but it is an absolute url to the production version of the app. I think it would be better to use a `NavButton` and then you link to "/app" by getting the default library from the app config: `href={APP_CONFIG.openebooks.defaultLibrary}`

2020-12-23 13:29 UTC, kristojorg commented on src/components/OpenEbooksLanding.tsx
> +                title="Catalog"
What does this prop do?

2020-12-23 17:20 UTC, kaplanmichael commented on src/components/OpenEbooksLanding.tsx
> +                href={libraryLinks.libraryWebsite?.href}
Done!

2020-12-23 17:33 UTC, kaplanmichael commented on src/components/OpenEbooksLanding.tsx
> +                title="Catalog"
Removed!

2020-12-23 19:18 UTC, kaplanmichael commented on src/components/SignOut.tsx
> +}: SignOutProps) => {
OK.  Have a look at the latest; is that more what you had in mind?

2020-12-23 19:18 UTC, kaplanmichael commented on src/components/OpenEbooksLanding.tsx
> +              <AnchorButton
OK. Have a look at the latest; is that more what you had in mind?

2021-01-04 16:21 UTC, kristojorg approved these changes
Looks good!

2021-01-04 16:21 UTC, kristojorg commented on src/components/OpenEbooksLanding.tsx
> +                }}
This should work, but I think you can also just say ``href={`/${APP_CONFIG.openebooks?.defaultLibrary`}`` without the need to make it a URL Object

2021-01-04 16:21 UTC, kristojorg commented on CHANGELOG.md
> +- Add: "theme" prop to SignOut component so that its color scheme can be configured at page level
Can remove this now

2021-01-04 16:21 UTC, kristojorg commented
Just need to fix that failing test

2021-01-04 16:23 UTC, kristojorg commented
It looks like you just need to update the snapshots. Run `npm run test` and then press `u` and then commit and push

2021-01-04 19:00 UTC, kaplanmichael commented
> It looks like you just need to update the snapshots. Run `npm run test` and then press `u` and then commit and push

Done!  (There was no 'u' option, so I ran it from the prompt instead:  "npm run jest --updateSnapshot".  )

2021-01-04 19:03 UTC, kaplanmichael commented on CHANGELOG.md
> +- Add: "theme" prop to SignOut component so that its color scheme can be configured at page level
Done!

2021-01-04 19:14 UTC, kaplanmichael commented on src/components/OpenEbooksLanding.tsx
> +                }}
If I do that, it returns the following:   
![image](https://user-images.githubusercontent.com/6432596/103570485-299b3d80-4e97-11eb-9a21-562c9a71f31e.png)

2021-01-05 12:54 UTC, kristojorg commented on src/components/OpenEbooksLanding.tsx
> +                }}
Ohhhh good point that's because the `NavButton` is using our custom `Link` which is meant to handle routing _within_ a single library. So you can actually just set `href="/"` which is internally interpreted to be the home page of the library catalog. Maybe I should make this more clear now that we do actually have something at "/", whereas previously we didn't and only cared about the "/[library]" routes

2021-01-05 18:08 UTC, kaplanmichael commented on src/components/OpenEbooksLanding.tsx
> +                }}
Cool, that seemed to work. Should I also change the path of the "log in" button as well?  currently, in the code, it reads  `href={`/${slug}/login`}` but I could change it to ` href="/login"}`.

2021-01-05 21:53 UTC, kristojorg commented on src/components/OpenEbooksLanding.tsx
> +                }}
Yea good catch, I think that'll be clearer overall, thanks!

2021-01-05 21:54 UTC, kristojorg commented on CHANGELOG.md
> +- Add: "theme" prop to SignOut component so that its color scheme can be configured at page level
mmmm I'm still seeing it  : )

2021-01-06 18:51 UTC, kaplanmichael commented on src/components/OpenEbooksLanding.tsx
> +                }}
Done!

2021-01-11 11:02 UTC, merged