Bugfix/simply 3331 wide viewport issue
NYPL-Simplified/circulation-patron-web pull request #241
Opened 2021-01-06 17:15 UTC by kaplanmichael

https://jira.nypl.org/browse/SIMPLY-3331

2021-01-11 11:08 UTC, kristojorg requested changes
I don't think this is quite right... 

This is the original:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/4398775/104173084-2ce57a80-53fd-11eb-9fd0-8fd79f866b73.png">


And this is your new version:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/4398775/104173123-38d13c80-53fd-11eb-858d-d6335a730515.png">


I believe the books are being stretched right now when they shouldn't be

2021-01-11 11:08 UTC, kristojorg commented on CHANGELOG.md
> +Fix: Improve the appearance of home page book thumbnails for larger viewports
I think this needs a bullet point and shouldn't have a space between it and the preceding

2021-01-11 11:08 UTC, kristojorg commented on src/components/OpenEbooksLanding.tsx
> +                  flex: [1, 1, "auto"],
Is this meant to be `flex: 1 1 auto;` in the css or are you meaning to use these media queries?

2021-01-11 11:11 UTC, kristojorg commented
I can't quite tell what the solution is meant to be but I think this isn't right as is

2021-01-11 11:13 UTC, kristojorg commented
I think it would make sense to give a max width to the whole section maybe so it just doesn't expand wide enough to look weird

2021-01-12 18:21 UTC, kaplanmichael commented on CHANGELOG.md
> +Fix: Improve the appearance of home page book thumbnails for larger viewports
Fixed!

2021-01-12 18:22 UTC, kaplanmichael commented on src/components/OpenEbooksLanding.tsx
> +                  flex: [1, 1, "auto"],
Rewrote that code block so this no longer applies.

2021-01-12 18:24 UTC, kaplanmichael commented
We determined that the issues described above were due to the way Safari's implementation of certain Flexbox properties differs from that of other browsers.  Should be OK now.

2021-01-13 12:48 UTC, kristojorg commented on dev-server.js
> +var ipAddr = Object.values(require("os").networkInterfaces()).reduce(
A comment on what this is doing would be appreciated

2021-01-13 12:50 UTC, kristojorg commented on src/components/OpenEbooksLanding.tsx
> +      className="popular-books-section"
What is the purpose of this className?

2021-01-13 12:53 UTC, kristojorg reviewed
Some questions, and I would rather not use hard coded pixel values unless it's necessary

2021-01-13 12:53 UTC, kristojorg commented on src/components/OpenEbooksLanding.tsx
> +        my: ["20px", "20px", "35px"],
I would rather use theme scale values than hardcoded pixel values if possible. But if those aren't specific enough then we can use this

2021-01-13 12:53 UTC, kristojorg commented on src/components/OpenEbooksLanding.tsx
> +          marginTop: ["28px", "28px", "70px"]
Same here

2021-01-13 12:58 UTC, kristojorg commented
Otherwise this looks good to me.

2021-01-13 14:47 UTC, kaplanmichael commented on src/components/OpenEbooksLanding.tsx
> +      className="popular-books-section"
I felt that it makes the code slightly more readable, but I'm cool with zapping it if you'd prefer not having stuff like that in the code.  LMK.

2021-01-13 15:46 UTC, kristojorg commented on src/components/OpenEbooksLanding.tsx
> +      className="popular-books-section"
I think we should preserve classNames as styling, but you can add a comment if you'd like! It does seem pretty readable to me simply because the component is already named

2021-01-13 16:40 UTC, kaplanmichael commented on dev-server.js
> +var ipAddr = Object.values(require("os").networkInterfaces()).reduce(
Done!

2021-01-13 16:42 UTC, kaplanmichael commented on src/components/OpenEbooksLanding.tsx
> +      className="popular-books-section"
I was referring to the readability of the _rendered_ code, but you've sold me on stripping it out :)  Should be good now!

2021-01-13 18:40 UTC, kaplanmichael commented on src/components/OpenEbooksLanding.tsx
> +          marginTop: ["28px", "28px", "70px"]
Fixed!

2021-01-13 18:40 UTC, kaplanmichael commented on src/components/OpenEbooksLanding.tsx
> +        my: ["20px", "20px", "35px"],
Fixed!

2021-01-14 14:47 UTC, kristojorg approved these changes
Okay this looks good to me!

2021-01-14 22:26 UTC, kaplanmichael commented
> Okay this looks good to me!

@kristojorg Awesome, thanks!  Should I go ahead and merge?  How should I route the JIRA ticket?

2021-01-15 11:05 UTC, merged

2021-01-15 11:06 UTC, kristojorg commented
Okay I squashed and merged (which puts all the commits from this PR into a single commit on the dev branch to keep things clean). You can move the JIRA ticket to ready for QA!