[SIMPLY-3496] 401 page is flashed during login redirection in CPW
NYPL-Simplified/circulation-patron-web pull request #244
Opened 2021-02-03 17:18 UTC by kaplanmichael

Display a page loader instead of an error screen when a 401 is caught.

https://jira.nypl.org/browse/SIMPLY-3496

2021-02-04 10:34 UTC, kristojorg requested changes
Would be great to add a simple test to Error.test.tsx for the 401 case. Otherwise this looks great and works perfectly.

2021-02-08 22:10 UTC, kaplanmichael commented
> Would be great to add a simple test to Error.test.tsx for the 401 case. Otherwise this looks great and works perfectly.

Done!

2021-02-16 13:27 UTC, kristojorg commented
Okay this looks good. I'll merge.

2021-02-16 13:28 UTC, kristojorg approved these changes

2021-02-16 13:28 UTC, merged