Feature/simply 3517 text updates
NYPL-Simplified/circulation-patron-web pull request #245
Opened 2021-02-11 22:27 UTC by kaplanmichael

https://jira.nypl.org/browse/SIMPLY-3517

2021-02-16 13:43 UTC, kristojorg commented
Looks like there is a minor lint error on this. Otherwise looks good, I'm just waiting for access to the copy document to finish review

2021-02-16 22:00 UTC, kaplanmichael commented
> Looks like there is a minor lint error on this. Otherwise looks good, I'm just waiting for access to the copy document to finish review

Fixed!

2021-02-17 13:18 UTC, kristojorg requested changes
Can you just move the changelog and then we can merge this?

2021-02-17 13:18 UTC, kristojorg commented on CHANGELOG.md
> +- Update: Update landing page copy.
This should be moved to unreleased changes, this probably happened during the merge from dev -> this branch

2021-02-17 15:38 UTC, kaplanmichael commented on CHANGELOG.md
> +- Update: Update landing page copy.
Done!

2021-02-17 16:41 UTC, kristojorg approved these changes
Looks good

2021-02-17 16:41 UTC, merged