contributors
NYPL-Simplified/circulation-patron-web pull request #255
Opened 2021-04-14 19:54 UTC by kristojorg

This is a draft PR to resolve https://jira.nypl.org/browse/SIMPLY-3653 where contributors are not showing up right in list view or book details view.

2021-05-04 14:28 UTC, kaplanmichael requested changes
Looks good. Just a few quick questions:

2021-05-04 14:28 UTC, kaplanmichael commented on src/components/BookList.tsx
> +    authorsArray.push(`& ${authors?.length - 2} more`);
Does `authors` need the question mark here?  If there aren't any authors that line of code I think won't be executed in the first place.

2021-05-04 14:28 UTC, kaplanmichael commented on src/components/__tests__/BookList.test.tsx
> +  expect(utils.getByText("one, two, & 3 more"));
This Oxford comma just made my day.  This PR now gets 100 bonus points!

2021-05-04 14:28 UTC, kaplanmichael commented on src/components/BookList.tsx
>    // uses contributors if there are no authors
Is this comment accurate? Looking at `getAuthorsString`, I didn't see anything related to contributors (it seems like that's all handled in the `parse` method.

2021-05-04 15:26 UTC, kristojorg commented on src/components/BookList.tsx
> +    authorsArray.push(`& ${authors?.length - 2} more`);
Good point thanks

2021-05-04 15:26 UTC, kristojorg commented on src/components/__tests__/BookList.test.tsx
> +  expect(utils.getByText("one, two, & 3 more"));
Hahah it was a necessary fix

2021-05-19 18:13 UTC, kristojorg commented on src/components/BookList.tsx
>    // uses contributors if there are no authors
Yep it's accurate, it's withing the `getAuthors` method which is called inside `getAuthorsString`. I moved them next to each other in `utils/book.tsx` more obvious.

2021-06-01 05:03 UTC, merged