Create First Cypress Tests (Jira OE-166)
NYPL-Simplified/circulation-patron-web pull request #262
Opened 2021-07-27 15:01 UTC by jcsmit17

2021-07-27 16:28 UTC, kristojorg requested changes
We will need to change all queries from queries based on dom-structure, class name, id, or other non user-facing elements to ones that query elements the way users would: by their text content or aria-label or otherwise. We can do this using [cypress-testing-library](https://testing-library.com/docs/cypress-testing-library/intro/). I have already instantiated it in the cypress setup and used it in my sample test I believe. The reasons are as follows:

- Class names are generated at build type via a hash function, thus will change anytime any style changes. This would make tests fail almost every build.
- DOM structure and class names or IDs are all likely to change as the app continues to develop, even if the underlying functionality stays the same. The test should pass if the functionality is the same, even if we add new dom markup or move things around. 
- Most importantly, the presence of a certain class names or ids or dom children is not really what we care about. We care that there is a button called "login" on the page, and a field labeled "username" that can me typed into, etc. Further, we care that these things are accessible to people using screen readers, which means that the elements should have the apropriate aria-label, etc. Querying the dom this way is what cypress-testing-library helps you do. 

Writing the tests using this strategy should both be easier (you don't have to dig through for class names and dom structure etc), less flaky, and better verify the functionality we care about

2021-07-27 16:28 UTC, kristojorg commented on package.json
> +    "cypress:headless": "./node_modules/.bin/cypress run cypress"
you don't need the `./node_modules/.bin/cypress` here, you can just write `cypress run ...`

2021-07-27 16:28 UTC, kristojorg commented on cypress/integration/firstbook_spec.js
> +})
We should not be performing a manual login before every test. We should test the login flow independently, and then for other tests just provide the auth token directly. [Here is an example](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/logging-in__basic-auth/cypress/integration/spec.js) from the cypress website showing how to do that using basic auth, which would work for firstbook.

I highly suggest [this youtube video](https://www.youtube.com/watch?v=5XQOK0v_YRE) about why it's recommended to do it this way.

2021-07-27 16:28 UTC, kristojorg commented on cypress/integration/clever_spec.js
> +        cy.get('#viewer > main > div.page-container', {timeout: universal_timeout}).should('be.visible');
What does this verify?

2021-07-27 16:39 UTC, kristojorg commented on cypress/integration/firstbook_spec.js
> +})
This is another [example using JWT](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/logging-in__jwt/cypress/integration/spec.js), which is actually more like what we would need to do, since the page itself is not protected with basic auth, just the server endpoints. We need to save the auth token into the localStorage the same way the app does it before the tests, that way it is there when the app looks for it and we can proceed as logged in. 

Performing a manual login on every test will add complexity to every test, potential for flakiness, and will slow them down significantly. Let's try using the localStorage way. I would suggest loggin in manually and looking at `localStorage` to see the format it is stored in in, and then you can perform a login programmatically and get an auth token to save there in `beforeEach`

2021-07-27 19:20 UTC, jcsmit17 commented on cypress/integration/clever_spec.js
> +        cy.get('.Autosuggest--textInput', {timeout: universal_timeout}).type('573a4487a920880100000aba');
I may be able to trim it down or provide a cleaner way to wait for page loading, but this is the rough version to ensure the page is loaded before looking for elements.

2021-07-27 19:20 UTC, jcsmit17 commented on cypress/integration/clever_spec.js
> +        cy.get('#viewer > main > div.page-container', {timeout: universal_timeout}).should('be.visible');
This is verifying that e-reader is present in browser.

2021-07-27 19:23 UTC, jcsmit17 commented on cypress/integration/clever_spec.js
> +        cy.get('#viewer > main > div.page-container', {timeout: universal_timeout}).should('be.visible');
This is verifying that the e-reader without error after flipping pages.

2021-07-27 19:31 UTC, jcsmit17 commented on .gitignore
> +cypress/plugins
Good catch. I'll fix in next patch.

2021-08-17 14:39 UTC, kristojorg commented
Closing in favor of #264

2021-08-17 14:39 UTC, closed without merging