SFR-1239 & SFR-1241 Create Cypress Tests for browsing and checking age appropriateness
NYPL-Simplified/circulation-patron-web pull request #264
Opened 2021-08-05 22:27 UTC by samanthaandrews

2021-08-05 22:29 UTC, samanthaandrews commented on cypress.json
> +    "OPENEBOOKS_EARLY_GRADES_USER_PW": ""
These came from this [doc](https://docs.google.com/spreadsheets/d/1D0153QostVdk6YWMSZ4Vv_aBa2TxpKJ8vW7R8biiZoA/edit#gid=317403225) that @kristojorg sent, but it seems like we should have dedicated test accounts for these Cypress tests and make note that these will be running on a daily or hourly chron job?

2021-08-05 22:33 UTC, samanthaandrews commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // cy.findByText("404 Error: No such lane.").should("exist");
You will see these commented out assertions throughout this file, and that is because I believe these are bugs that I found! Basically, if you try to navigate directly to a path that you should not have access to, you can still see the content. For example, if I'm logged in as an "Early Grades" user and I navigate to the URL for the book _Betrayed_ by Jennifer Rush, I can view that page and do not get a 404 page. FWIW, there is a 451 server error that displays in the console.

I will create a bug for this issue.
![Screen Shot 2021-08-05 at 11 06 58 AM](https://user-images.githubusercontent.com/34348332/128429723-195c57b1-8ab3-4d36-baa2-c14ff2559535.png)

2021-08-05 22:34 UTC, samanthaandrews commented on cypress/integration/open-ebooks/report-problem.ts
> +    cy.findByRole("button", { name: "Submit" }).should("exist").click();
I am actually submitting this data, even though it's a test. I'm not sure who these reports are sent to, but perhaps this is annoying for them??

2021-08-05 22:35 UTC, samanthaandrews commented on cypress/plugins/index.ts
> +const injectDevServer = require("@cypress/react/plugins/next");
I thought that this would resolve issues with importing the `generateToken()` function into our tests, but it didn't, so I'm thinking I should just remove it and its associated packages.

2021-08-05 22:37 UTC, samanthaandrews commented on cypress/support/commands.ts
> +}
This is the function that I'm unable to import into any Cypress file without ultimately receiving this error. I am not really sure why Cypress needs access to this config only when importing an external function??
![Screen Shot 2021-08-03 at 12 38 37 PM](https://user-images.githubusercontent.com/34348332/128430128-3ce43920-ccef-4bf4-8cbd-ef499ff3cf24.png)

2021-08-05 22:38 UTC, samanthaandrews commented on cypress/support/utils.ts
> +export const BASIC_LOGIN = "http://opds-spec.org/auth/basic";
I put all of the "magic" strings in one file. Hoping this would make the tests easier to change if we needed to do so.

2021-08-05 22:40 UTC, samanthaandrews commented on src/interfaces.ts
> +export { OPDS2 };
Needed to do this to fix the errors when importing the `generateToken()` function in Cypress, which then led me to the missing `process.env.APP_CONFIG` error above 🙄

2021-08-05 22:42 UTC, samanthaandrews commented on package.json
> +    "webpack-dev-server": "^3.11.2"
These were the changes made to attempt to fix the import of `generateToken()` as recommended by the Cypress docs for ["Component Testing"](https://docs.cypress.io/guides/component-testing/framework-configuration) (but we aren't even doing component testing in Cypress). However, I get the same error with or without these additional packages which is why I'm thinking I should revert these changes.

2021-08-05 23:11 UTC, samanthaandrews commented on package.json
> +    "webpack-dev-server": "^3.11.2"
Removed.

2021-08-05 23:12 UTC, samanthaandrews commented on cypress/plugins/index.ts
> +const injectDevServer = require("@cypress/react/plugins/next");
Removed.

2021-08-10 20:38 UTC, hokei commented on cypress.json
> +    "OPENEBOOKS_EARLY_GRADES_USER_PW": ""
yes.  I think we can make a note in the google doc that this is what they're being used for, and make sure Miguel is aware of this.

2021-08-10 20:39 UTC, hokei commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    cy.findByRole("heading", { name: "High School collection" }).should(
wait isn't this a high school user?  Why would "high school collection" not exist?

2021-08-10 20:42 UTC, hokei commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // Verify early and middle grade lanes are not present
Somehow I was under the impression that high school students can view early/middle grade books, but not vice versa.  
Can we verify this?

2021-08-10 20:45 UTC, hokei commented on cypress/integration/open-ebooks/browse.ts
> +        cy.findByText("9999 out of 9999 copies available.").should("exist");
This I think might become frustratingly brittle if this book is used as a test from anyone else on QA.

2021-08-10 20:48 UTC, hokei commented on cypress/integration/open-ebooks/report-problem.ts
> +    cy.findByRole("button", { name: "Submit" }).should("exist").click();
you should ask in the #open-ebooks slack, I think Miguel should know (or should find the answer)  

I also think if there's a way to call a mock in this submit I'd prefer to do that?  You know, to prevent an [HBO Max ](https://twitter.com/hbomaxhelp/status/1405712235108917249)kind of problem

2021-08-10 20:50 UTC, hokei commented on src/interfaces.ts
> +export { OPDS2 };
this is weird because AFAIK CPW doesn't support a library registry but ... I think we can deal with this some other time

2021-08-10 20:53 UTC, hokei commented
What's here looks good, but I'm concerned about the fact that it's all using live data.  Right now, also, beta.openebooks.us is literally pointing to the qa.circulation so it's using live _production_ data.  I'm not sure when we're going to get a real QA instance, and I'm not sure if the data on this QA instance would be guaranteed, if we got it.  

Is there a way we can run these extensive tests using mocks, and then run a simpler set of "are the services up" tests using live data?  Or is there some reading I can do on why we don't want to mock the OPDS2 response?

2021-08-11 11:09 UTC, kristojorg commented on cypress.json
> +    "OPENEBOOKS_EARLY_GRADES_USER_PW": ""
Are we passing the passwords in via env vars? If so I think we should also pass in the username via env var, just so the two are set in the same place and easier to update in the future

2021-08-11 11:13 UTC, kristojorg commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // cy.findByText("404 Error: No such lane.").should("exist");
Yep this is a good find! Here is the deal- the circulation manager (backend) was not really built initially for this sort of authentication and user-role scheme, so the implementation we have is a bit naive. I could be wrong, but I think that individual books will always be "unprotected" which means they're public essentially and can be viewed by anyone, logged in or not, and no matter of age - if they navigate directly to them. So it may be that this is intended behavior, and we should actually have a test that it is true and add a comment as to why.

However, that said, I haven't seen this console error before, so maybe it's new and we should actually be blocking logged in users from viewing these books? 

@leonardr can you give any insight into the protections for an individual OPDS entry?

2021-08-11 11:15 UTC, kristojorg commented on cypress/integration/open-ebooks/report-problem.ts
> +    cy.findByRole("button", { name: "Submit" }).should("exist").click();
Lol yep we should at least ask, and possible just mock out that endpoint I agree

2021-08-11 11:18 UTC, kristojorg commented on cypress/support/commands.ts
> +}
I think this is because somewhere along the chain of that import we have some code that uses `process.env.APP_CONFIG`, which I set up for us in the actual app via next.config.js. I think we'll probably need to set it to some mock value for the cypress runtime as well.

2021-08-11 11:18 UTC, kristojorg commented on cypress/support/utils.ts
> +export const BASIC_LOGIN = "http://opds-spec.org/auth/basic";
This _should_ exist as a constant in the app somewhere already... but I guess we still aren't able to import the app code huh... anyway once we fix that we should see if we can import this string

2021-08-11 11:20 UTC, kristojorg commented on src/interfaces.ts
> +export { OPDS2 };
It does support a library registry actually. The "community demo" uses the NYPL library registry to deploy an instance for every library in the registry

2021-08-11 11:21 UTC, kristojorg commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // Verify early and middle grade lanes are not present
That's not the case I don't believe, but agree we should verify. My understanding is that each age group can see only their age group.

2021-08-11 11:24 UTC, kristojorg commented
@hokei - We do have a qa instance, and `qa-web.openebooks.us` is pointing to the qa circulation manager.

I also think it is good that this is using live data, and I think it should. That's why they're end to end tests as far as I understand. 

At some point, I wouldn't be opposed to having the same set of tests run against both live and mocked endpoints, but I think the starting point should be using live qa server, because we want to know if every _actually_ works from end to end. If something changes on the backend and that breaks our app, we want to know before someone randomly finds/reports it.

2021-08-11 11:45 UTC, kristojorg requested changes
This looks great, super thorough! I'm hoping that the qa-server collection is somewhat stable and we don't need to go updating the books and stuff in these tests often. We'll see though. If not, then we should talk to leonard about having some standard collections and books that stay the same for testing purposes added to the qa server. 

Just a couple comments

2021-08-11 11:45 UTC, kristojorg commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    cy.findByText("404 Error: No such lane.").should("not.exist");
I think I would generally try to confirm you can visit by making assertions in the affirmative. If we happen to change this error message these tests could pass erroneously.

2021-08-11 11:45 UTC, kristojorg commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    cy.findByRole("heading", { name: "High School collection" }).should(
They don't see the heading, it just shows them their sublanes. You only see the sub-lane headings. In the all-access case, the "high school collection" is a sub lane itself. Does that make sense? I think we could add a comment to clarify this though

2021-08-11 11:45 UTC, kristojorg commented on cypress/integration/open-ebooks/browse.ts
> +        cy.findByText("9999 out of 9999 copies available.").should("exist");
That's a good point. Maybe we could just test that "out of 9999 copies available" is there

2021-08-11 11:45 UTC, kristojorg commented on cypress/integration/open-ebooks/report-problem.ts
> +    cy.findByRole("heading", { name: "Report a problem" }).should("exist");
thought: do these exist before you click the button? I can't remember if this HTML is always rendered, but only visible after clicking button, or if it's actually not there until you click. Maybe you can verify?

2021-08-11 11:46 UTC, kristojorg commented
I can merge this without storybook working, and we can make storybook work next. However, I do think we should try to make the e2e actions work before merging maybe. Open to merging into dev first though and doing that in another PR.

2021-08-11 13:24 UTC, hokei commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    cy.findByRole("heading", { name: "High School collection" }).should(
Oh yes, this makes sense, but I think a comment would alleviate some confusion

2021-08-11 14:14 UTC, hokei commented
> At some point, I wouldn't be opposed to having the same set of tests run against both live and mocked endpoints, but I think the starting point should be using live qa server, because we want to know if every actually works from end to end. If something changes on the backend and that breaks our app, we want to know before someone randomly finds/reports it.

 I just think, if we're generating reports and stuff based on this, I don't want to be on the hook for server errors, or, even worse, just data getting updated.  This is a bigger conversation and I think we will continue it in a bunch of different venues - for now, this is fine.  
 
 It'll also be useful to get it out and seeing whether data actually does end up getting updated frequently 
When Leonard comes back we could also see about getting test users set up, with test lanes and collections, so that the data is stable.

2021-08-11 14:39 UTC, samanthaandrews commented on cypress/integration/open-ebooks/report-problem.ts
> +    cy.findByRole("heading", { name: "Report a problem" }).should("exist");
Good point. I will check on that.

2021-08-11 14:44 UTC, samanthaandrews commented on cypress/integration/open-ebooks/browse.ts
> +        cy.findByText("9999 out of 9999 copies available.").should("exist");
You're right. I think this might be a good candidate for using mocked data instead of live.

2021-08-11 14:45 UTC, samanthaandrews commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // Verify early and middle grade lanes are not present
I'll check with Miguel now

2021-08-11 14:46 UTC, samanthaandrews commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    cy.findByRole("heading", { name: "High School collection" }).should(
These lanes are "All access" lanes that are only visible to an "All access" user, so the separation-by-grade lanes will not be present. I will add a comment to clarify.

2021-08-11 14:57 UTC, samanthaandrews commented
> I can merge this without storybook working, and we can make storybook work next. However, I do think we should try to make the e2e actions work before merging maybe. Open to merging into dev first though and doing that in another PR.

@kristojorg @hokei My plan after reading through your comments (thanks, btw!) is to follow the Cypress docs recommendation and create mock data for these tests, while still having one e2e test that uses real data and runs through the app as a real user would.

I'd prefer to merge this PR into dev after making that change, in addition to the other changes requested. And then I will get to work on  https://jira.nypl.org/browse/SFR-1253, which includes several sub-tasks with getting Cypress configured to work with GitHub Actions & GitHub Secrets. Specifically, I'll work on https://jira.nypl.org/browse/SFR-1254 and https://jira.nypl.org/browse/SFR-1257. Feels like getting this config set up and running how we want it is a separate ticket.

2021-08-11 15:22 UTC, samanthaandrews commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // Verify early and middle grade lanes are not present
Miguel confirmed the behavior that @kristojorg described, each age group can see only their age group.

2021-08-11 23:16 UTC, samanthaandrews commented on cypress.json
> +    "OPENEBOOKS_EARLY_GRADES_USER_PW": ""
This is the doc where I found the test account info: https://docs.google.com/spreadsheets/d/1D0153QostVdk6YWMSZ4Vv_aBa2TxpKJ8vW7R8biiZoA/edit#gid=317403225

I requested edit access last week, but have not yet received it. Anyone able to access it and mark the accounts we're currently using?

2021-08-12 01:17 UTC, samanthaandrews commented on cypress.json
> +    "OPENEBOOKS_EARLY_GRADES_USER_PW": ""
@kristojorg Moved all these values into environment variables. I still think having the key in the cypress config is valuable, so folks who are new to the repo understand that these are being passed in _somewhwere_ and it's not happening by magic.

2021-08-12 01:19 UTC, samanthaandrews commented on cypress/integration/open-ebooks/browse.ts
> +    cy.wait("@staffPicks");
@hokei @kristojorg I experimented with mocking out _some_ of this data (I think in 3 or 4 different places in this file), mostly where it seemed to get really specific about one particular book. Otherwise, I kept communication with the server. Lmk what you think.

2021-08-12 01:21 UTC, samanthaandrews commented on cypress/integration/open-ebooks/read-book.ts
> +});
Here I was just experimenting with `cy.intercept()` and fixtures.

2021-08-12 01:21 UTC, samanthaandrews commented on cypress/integration/open-ebooks/report-problem.ts
> +    cy.wait("@submission");
@kristojorg @hokei I did successfully mock this server request 🎉

2021-08-12 16:21 UTC, hokei commented on cypress/integration/open-ebooks/report-problem.ts
> +    cy.wait("@submission");
🎉

2021-08-12 16:43 UTC, hokei commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // FIXME: Verify you cannot navigate to collections or books outside your age class
did we decide to make these test assert that you can navigate to them, as documentation that this is currently the functionality?  I'm reluctant to make and link a ticket because that's how stuff disappears into the Jira void, but at least we have it here?

2021-08-12 16:45 UTC, hokei commented
This is looking really good!  I'll leave it to Kristo for final sign off but great job!

2021-08-12 18:03 UTC, samanthaandrews commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // FIXME: Verify you cannot navigate to collections or books outside your age class
I also am reluctant to make a ticket until we know the answer to Kristo's question above... https://github.com/NYPL-Simplified/circulation-patron-web/pull/264#discussion_r686731553

I'll make a note to circle back on this with Leonard (I think he is on vacation) and either make a ticket to block these assets based on user type OR make these tests assert the behavior that Kristo described. It's strange because some of these tests I wrote passed, which means that they indeed blocked resources. However, they were often flaky.

2021-08-17 09:59 UTC, kristojorg commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // cy.findByText("404 Error: No such lane.").should("exist");
Is it also true that you can currently directly navigate to collections outside your age class?

2021-08-17 10:03 UTC, kristojorg commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // FIXME: Verify you cannot navigate to collections or books outside your age class
So we do need a JIRA ticket in the staging sprint (I think you made one yesterday) for:
- Make sure patrons cannot directly visit books outside their age class (send token on book entry requests)

One thing we want to make sure of when we do this - we currently get OPDS entries in full when we request a collection, and we save those OPDS entries into the cache keyed by the entry url, so that if we then request the entry, it will immediately be available because we have it in the cache from the collection. We want this pattern to still work when we are also sending tokens for the entry requests. We can chat more about it when it comes time

2021-08-17 10:10 UTC, kristojorg approved these changes
This looks fantastic. I think all we need to do is make a few tickets coming out of this:
- Make sure to protect the book details page from age-inapropriate requests. But still preserve the cacheing behavior we have setup so that we can save the entries we get in a collection request and not have to re-fetch them when we navigate to a book.
- Make the tests able to run as e2e and integration (with server mocks). Or some other similar setup so we can have both e2e and integration.
- Replace the duplicated `generateToken` with one imported from the app. This will require fixing the App Setup Error we get.
- Get GH Actions set up (I know you're already on this)
- Fix storybook build (idk if there is a ticket for this already)

If you can make sure we have those tickets @samanthaandrews in the staging sprint that would be awesome.

LGTM! 🥳

2021-08-17 10:11 UTC, kristojorg commented
Maybe also make an update to the changelog so that it passes that test and then I'll merge despite the storybook failure

2021-08-17 13:18 UTC, leonardr commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // cy.findByText("404 Error: No such lane.").should("exist");
I'm not sure exactly what you're asking so I'll restate the rules. If your account has an external_type ("E") that is associated with a root lane ("Early Grades") and you try to access a lane that is neither that root lane nor a recursive child of that root lane ("Middle Grades / Comics") you should get a 404.

2021-08-17 14:44 UTC, kristojorg commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // cy.findByText("404 Error: No such lane.").should("exist");
Sorry I was actually asking sam if that behavior was working or not. We currently have a known bug where we do not send the token with OPDS Entry requests, which means that authenticated patrons are erroneously able to view any book if they directly navigate to it with a link. 

The fact that this test is commented out for the _collection_ as well as the book, makes me wonder if we are also erroneously able to directly navigate to collections outside your root lane while logged in. This would be unexpected and another (different) bug if true

2021-08-17 14:44 UTC, merged

2021-08-17 15:12 UTC, samanthaandrews commented on cypress/integration/open-ebooks/age-appropriateness.ts
> +    // cy.findByText("404 Error: No such lane.").should("exist");
Collection lanes seem to be behaving as expected, i.e. getting blocked with a 404 for users outside their age class. For some reason, though, these tests were still flaky even for collection lanes. I'll make sure they're working as expected in the ticket that addresses the blocking resources at a book level.