[Test build] Re-enable access test
NYPL-Simplified/circulation-patron-web pull request #304
Opened 2021-11-08 22:59 UTC by Toxiapo

2021-11-16 21:16 UTC, Toxiapo commented on cypress/tests/open-ebooks/server-e2e/age-appropriateness/early-grades-access.ts
> +});
This is actually an expected behavior, that if no token was included in the header, we just give them access.

2021-11-16 21:34 UTC, Toxiapo commented on cypress/tests/open-ebooks/server-e2e/age-appropriateness/high-school-access.ts
> +  });
These two tests are actually failing when they shouldn't? I think ideally, a high schooler should have access to middle and early grade collections, but these tests are throwing 404 messages.

2021-11-16 22:08 UTC, Toxiapo commented on cypress/tests/open-ebooks/server-e2e/age-appropriateness/high-school-access.ts
> -    cy.loadApp();
Sometimes we get 502 errors from this command. Moving this out from beforeEach so that the rest of the suites can still run if any one of them failed.

2021-11-19 23:17 UTC, samanthaandrews requested changes
Just a few small nits to fix. Was the issue here the server-side issue you identified where making multiple authenticated requests as an early-grades users to the collections endpoint starts to send back high-school or middle-school collections?

2021-11-19 23:17 UTC, samanthaandrews commented on cypress.json
> +    "runMode": 0,
should we re-enable retries in runMode?

2021-11-19 23:17 UTC, samanthaandrews commented on cypress/tests/open-ebooks/server-e2e/age-appropriateness/high-school-access.ts
> +  // EARLY_GRADES_CHAPTER_BOOKS_COLLECTION_PATH,
I think we can remove commented out imports if they're not being used

2021-11-19 23:17 UTC, samanthaandrews commented on cypress/tests/open-ebooks/server-e2e/age-appropriateness/middle-grades-access.ts
> +    Cypress.Cookies.debug(true);
Not sure if we need this anymore?

2021-11-19 23:17 UTC, samanthaandrews commented on cypress/tests/open-ebooks/server-e2e/age-appropriateness/middle-grades-access.ts
> +      cy.log(`cookie value: ${c?.value}`)
For security reasons, I'm not sure it's a good idea to log the cookie anywhere

2021-11-19 23:17 UTC, samanthaandrews commented on cypress/tests/open-ebooks/server-e2e/login/firstbook-login.ts
> +describe.only("FirstBook login", () => {
I think we can remove the `.only`

2021-11-19 23:17 UTC, samanthaandrews commented on cypress/tests/open-ebooks/server-e2e/age-appropriateness/middle-grades-access.ts
> +      cy.log(`cookie value: ${c?.value}`)
Also I think we can pass in COOKIE_KEY const from utils if we need to keep this check.

2021-11-19 23:17 UTC, samanthaandrews commented on cypress/support/utils.ts
> +)}`;
nice!

2021-11-21 23:42 UTC, Toxiapo commented
> Just a few small nits to fix. Was the issue here the server-side issue you identified where making multiple authenticated requests as an early-grades users to the collections endpoint starts to send back high-school or middle-school collections? 

Yes! I think we can close this PR for now and try again after we find out the status of this endpoint.

What do you think? @kristojorg

2021-11-22 08:37 UTC, kristojorg commented
@toxiapo I'd like to get in the tests you added, even if they are commented out for now. Can we do that?

2021-11-22 14:10 UTC, Toxiapo commented
> @Toxiapo I'd like to get in the tests you added, even if they are commented out for now. Can we do that?

Yea! I will comment them out for now.

2021-11-22 22:07 UTC, samanthaandrews approved these changes
Looks great!

2021-11-23 16:52 UTC, kristojorg approved these changes
Looks good, thanks!

2021-11-23 17:05 UTC, Toxiapo commented on cypress/tests/open-ebooks/server-e2e/age-appropriateness/high-school-access.ts
> +    // FIXME: This test should not be valid, high schoolers should have access to HIGH/MID/Early grade contents
Hmm, GitHub didn't update this file for some reason. This is part of the backend fix linked above.

2021-11-23 17:11 UTC, merged