[DRAFT] Try nextjs API caching
NYPL-Simplified/circulation-patron-web pull request #308
Opened 2021-11-17 01:22 UTC by Toxiapo

2021-11-17 15:00 UTC, kristojorg requested changes
Looks great! Super happy this works. Still have a couple other things we need to do to get load times down, but this is a great step for us! 

Just a couple small edits requested below

2021-11-17 19:00 UTC, Toxiapo commented on src/pages/api/axisnow/[isbn].ts
>   * eg: http://localhost:3000/api/axisnow/[isbn]/[vaultId]
Updated!

2021-11-18 14:24 UTC, kristojorg requested changes
just the one thing, but otherwise awesome!

We _could_ add a test to make sure that we properly call this API endpoint on the read page.

2021-11-18 14:24 UTC, kristojorg commented on CHANGELOG.md
> +- Refactor: Change API `axisnow/[isbn]/[vaultId]` to `axisnow/[isbn]` so that Vercel could cache our webpub manfiest responses.
FWIW I think this should be `Perf: ` since it's not just a refactor

2021-11-18 14:24 UTC, kristojorg commented on src/dataflow/fetch.ts
> +export async function fetchWithValudId(url: string, valutId: string) {
Spelling in function name and argument name, and can we also add a comment to describe what this function is for

2021-11-22 17:07 UTC, kristojorg approved these changes
Looks good, LGTM!

2021-11-22 17:07 UTC, merged