OE_280 Auth Middleware
NYPL-Simplified/circulation-patron-web pull request #326
Opened 2021-12-16 15:12 UTC by kristojorg

This PR begins to make a change to how we handle auth in CPW. We use Next.js 12 Middleware to check the auth status of a user whenever they are loading a route under /[library]. To do this, we fetch the `/patrons/me` endpoint with their token. If they are not authorized, we redirect them to the login page. 

This will enable one powerful optimization: we can now pre-render all routes on the server with public data. Users won't be able to access it unless they are authenticated, but the page is statically pre-rendered and served as plain HTML. That means we eliminate an entire loading screen. 

In this example, I only enable the pre-rendering for `/[library]/index`, but we would want to do it eventually for all collections and all book detail pages. In order to make this happen, we need a way to fetch this data from the CM without getting a 401 error. We can do that easily for book detail pages (just don't send a token), but not for collections. I got around this for the time being by using a test firstbook user's credentials during build rendering. Not sure if that's an ok thing to do though because that user could have loans or something. Ideally we could get a universal "client token" that will simply bypass the auth.

2021-12-16 15:17 UTC, kristojorg commented on src/components/context/UserContext.tsx
> +    router.reload();
This is just good practice, but it also gives the middleware a chance to properly redirect us

2021-12-16 15:18 UTC, kristojorg commented on src/dataflow/opds1/parse.ts
> +}
DOMPurify needs a window object, which we don't have on the server. So we use JSDOM on server.

2021-12-16 15:20 UTC, kristojorg commented on src/dataflow/withAppProps.ts
> +export default function withAppProps<
This function gets the site-wide data, but it also can support getting page-specific data. We never used it before, but I wrote it with this in mind. I updated it a little though to make it work better.

2021-12-16 15:21 UTC, kristojorg commented on src/hooks/useCollection.ts
> +    fallbackData: collectionSeed
We pass the statically-fetched data to `useSWR` and it uses that for the first render while revalidating in the background

2021-12-16 15:22 UTC, kristojorg commented on src/pages/[library]/index.tsx
> +    );
I should handle errors here, especially 502 errors. Probably by just not sending the page data along and letting it fallback to the way it was before.

2021-12-16 16:42 UTC, kristojorg commented
In order for this actually to work:
- collections _do_ change per-patron. So we would need middleware to redirect a patron to the right root collection also. 
- we would need to check if a patron has access to a collection in middleware, ideally without fetching the entire collection.
- we would need a way to fetch collections publicly at build time, like with a client-only universal token

2021-12-16 17:14 UTC, kristojorg commented
Update from convo with leonard:
- We can make a HEAD request to a collection to determine if a user can access it.
- Only the root lane changes per patron. We can fetch the root lane for the user and get the redirect that the server sends and redirect the user there.
- There would be no such thing as `/app` then. You would always get redirected to your specific root lane.

2021-12-16 18:47 UTC, kristojorg commented
Todo:
- Don't check patron/me if you're on collection page. It's not necessary since auth is checked via collection url
- Resolve lane issue with useLayoutEffect
- Dig in to infinite redirect issue

2021-12-16 23:51 UTC, kristojorg commented
I am seeing an issue (https://github.com/vercel/next.js/issues/32590) when trying to build for production, but otherwise this is looking promising. It works in dev!

2021-12-21 22:32 UTC, samanthaandrews commented
This is a big improvement! 🎉

The biggest issue I noticed while doing manual testing (this is also showing up in Cypress tests) is that sometimes when I click on a book or navigate to a collection, I am redirected to the login screen where it shows the loading spinner and then I am redirected back to page I was previously on.

https://user-images.githubusercontent.com/34348332/147005783-b074f073-11af-4d38-808f-9376a244e70a.mov

Perhaps related, I am sometimes getting an indefinite loading spinner when navigating to the `/loans` page. When I do a hard refresh, the issue seems to be resolved and I can see my loans.

https://user-images.githubusercontent.com/34348332/147005861-097cff8e-b9b7-4a4e-86a9-276ba017bfae.mov

2021-12-22 23:48 UTC, samanthaandrews commented on cypress/tests/open-ebooks/server-e2e/login/clever-login.ts
>    it("Incorrect Clever token displays error", () => {
This test has been failing and I think it's catching an actual issue. It's checking that if this query param `?loginError=` exists in the url, we display the error to the user in the UI.

![Clever login -- Incorrect Clever token displays error (failed) (attempt 2)](https://user-images.githubusercontent.com/34348332/147167376-26b03fe9-7f17-4adc-83d0-a258bad665e0.png)

2021-12-23 00:49 UTC, Toxiapo commented on src/hooks/useMounted.ts
> +export default function useMounted() {
I am wondering how is this being used. Does it work as a force re-render?

2021-12-23 19:16 UTC, samanthaandrews commented
An update on Cypress tests: We are getting 502 BAD GATEWAY errors on almost every Cypress test that run in CI. These 502 errors come from the /loans endpoint, `https://qa-circulation.openebooks.us/USOEI/loans`

I also occasionally see these errors when doing manual testing, but the CI runs into them much more frequently.

```
detail: "Error in authentication service"
 status: 502
 title: "Third-party service failed."
 type: "http://librarysimplified.org/terms/problem/remote-integration-failed"
```

I've inspected the request and response headers on a successful 200 /loans request and an unsuccessful 502 /loans request. We seem to be sending the same request headers from the app, but the response headers are different between a 200 and 502 status. In a 200 status code response header, we see the presence of two headers that don't exist on a 502 status response header,  `cache-control: private, no-cache` and `last-modified: Wed, 22 Dec 2021 21:05:02 GMT`

### 502 status code response headers:
1. **Connection:** keep-alive
2. **Content-Encoding:** gzip
3. **content-type:** application/api-problem+json
4. **date:** Wed, 22 Dec 2021 21:15:26 GMT
5. **Keep-Alive:** timeout=5
6. **server:** nginx/1.14.0 (Ubuntu)
7. **Set-Cookie:** AWSALB=E6PN/fC7gj+OJb4Z7I3mjq3dSeTTFwSYfZiP/wwuAL9Sn4VlkkRWbssdrrHKEDy4WUgVlswV5Zbetm2r8gpyDdiLkogUVPt3CptM4HJQgrTccQhuGxaIHGs67jpg; Expires=Wed, 29 Dec 2021 21:15:26 GMT; Path=/
8. **Set-Cookie:** AWSALBCORS=E6PN/fC7gj+OJb4Z7I3mjq3dSeTTFwSYfZiP/wwuAL9Sn4VlkkRWbssdrrHKEDy4WUgVlswV5Zbetm2r8gpyDdiLkogUVPt3CptM4HJQgrTccQhuGxaIHGs67jpg; Expires=Wed, 29 Dec 2021 21:15:26 GMT; Path=/; SameSite=None; Secure
9. **Transfer-Encoding:** chunked
10. **Vary:** Accept-Encoding

### 200 status code response headers
1. **cache-control:** private, no-cache
2. **Connection:** keep-alive
3. **content-encoding:** gzip
4. **content-type:** application/atom+xml;profile=opds-catalog;kind=acquisition
5. **date:** Wed, 22 Dec 2021 21:15:53 GMT
6. **Keep-Alive:** timeout=5
7. **last-modified:** Wed, 22 Dec 2021 21:05:02 GMT
8. **server:** nginx/1.14.0 (Ubuntu)
9. **Set-Cookie:** AWSALB=kvVQkRzWkuyF6RsSZzZqR0QVEbEaEdKZuiUG2gptjlwqkwS4p7vcD6/YYwBF/XK++Hfp6aaSzkNcUBR4wFeT7urG8lTCdL86M/iwN3paQNGCAdUJ03jOv4U72eh/; Expires=Wed, 29 Dec 2021 21:15:53 GMT; Path=/
10. **Set-Cookie:** AWSALBCORS=kvVQkRzWkuyF6RsSZzZqR0QVEbEaEdKZuiUG2gptjlwqkwS4p7vcD6/YYwBF/XK++Hfp6aaSzkNcUBR4wFeT7urG8lTCdL86M/iwN3paQNGCAdUJ03jOv4U72eh/; Expires=Wed, 29 Dec 2021 21:15:53 GMT; Path=/; SameSite=None; Secure
11. **Transfer-Encoding:** chunked
12. **Vary:** Authorization, Accept-Encoding

2021-12-24 16:28 UTC, kristojorg commented on src/hooks/useMounted.ts
> +export default function useMounted() {
Good question. This is being used because we need the server-side render and the _first_ client-side render to result in the same HTML in order for react's hydration function to work properly. What was happening was that the render would result in something ever so slightly different depending if you were on the server or the client. For example, in `useLogin`, we had a line here: https://github.com/NYPL-Simplified/circulation-patron-web/blob/99671fcfa8b183daa01586c7d6c129afcff22e49/src/auth/useLogin.ts#L34 that would change the `nextUrl` query parameter of the login button depending if we were server side or client side. This was due to a detail with how those the `router`'s `asPath` worked. Anyways, it meant that the login button on the server had no `nextUrl` and then it did in the first render on the client, which caused a hydration mismatch and forced react to throw out the whole dom and replace it. Instead, we now use `useMounted` to know if it is the first render or not, and only set the `nextUrl` on the second render and beyond. 

Thinking about it, another way we could handle this is to add some logic that makes the `asPath` the same on both client and server. Then we wouldn't have to worry about this.

2021-12-24 16:48 UTC, kristojorg commented
Ok so some notes for myself:
- [ ] when credentials are invalid and that is caught in the middleware, we need to clear them from the client. We can do this either by sending a set-cookie from the middleware during login redirect, or in the client upon reaching login page. Probably best done in the server if possible. Would also be good to send the error message from the server to the client in a query param so it can be displayed. This will stop the infinite login page redirection (hopefully it's the only cause).
- [ ] Need to make `loginError` display properly in the login page. This is not happening because login is statically generated and doesn't account for the query string currently. We need to somehow account for it in our static generation.
- [ ] Figure out infinite loans loading
- [ ] Figure out random login redirect when clicking book...

2021-12-27 19:43 UTC, kristojorg commented
@samanthaandrews let me know if you're seeing any more of those errors. Also @samanthaandrews @Toxiapo can you check for either of these two things I've seen in the past but not recently:

- Infinite loading screen on the `/loans` page (or anywhere for that matter)
- Randomly being redirected to login (you will correctly see this however if we get a 502 error in the middleware)
- The root lane being flashed briefly when navigating (or any page flashing one thing for a second then transitioning to the correct content briefly after)

2021-12-27 20:40 UTC, kristojorg commented
@samanthaandrews @Toxiapo I'm moving this back to a draft as I've found some issues... : (

2021-12-28 06:21 UTC, kristojorg commented
@samanthaandrews @Toxiapo this is back to ready for review. I think I've resolved the errors I was seeing and the ones sam found. It feels pretty stable to me now in my testing (and pretty fast : ) ). LMK if you find any issues here!

2021-12-28 16:43 UTC, samanthaandrews commented
Ok two things, one of which I think you mentioned seeing before in a previous comment.

It seems I can sometimes get stuck when clicking on a book link. I see the loading bar at the top, but it never reaches "100%" and I have to reload the page in order to get unstuck. I saw this happen a couple times in my testing.

https://user-images.githubusercontent.com/34348332/147587737-b40406bf-500a-4b28-8152-700d6f877226.mov

Even just after successfully logging in, I will randomly get redirected to the login page with the "Error in authentication service" error message. This seems to consistently happen when clicking a book link as shown in the video below. Perhaps this issue and the other one I just mentioned are related?

https://user-images.githubusercontent.com/34348332/147587865-38e17e57-ae97-46fd-b488-7a3fc0cab460.mov

2021-12-28 17:54 UTC, Toxiapo commented
> Ok two things, one of which I think you mentioned seeing before in a previous comment.
> 
> It seems I can sometimes get stuck when clicking on a book link. I see the loading bar at the top, but it never reaches "100%" and I have to reload the page in order to get unstuck. I saw this happen a couple times in my testing.
> 
>  bug-on-book-link.mov 
> Even just after successfully logging in, I will randomly get redirected to the login page with the "Error in authentication service" error message. This seems to consistently happen when clicking a book link as shown in the video below. Perhaps this issue and the other one I just mentioned are related?
> 
>  Screen.Recording.2021-12-28.at.9.30.13.AM.mov
@samanthaandrews That's really weird, I can't reproduce these errors. Does this only happen with Clever login or both?

2021-12-28 18:00 UTC, samanthaandrews commented
I've only tested with FirstBook login and using this preview url: https://open-ebooks-web-git-oe280-auth-middleware-nypl.vercel.app/

2021-12-28 18:04 UTC, Toxiapo commented
> I've only tested with FirstBook login and using this preview url: https://open-ebooks-web-git-oe280-auth-middleware-nypl.vercel.app/

Oh yeah, I can reproduce both the bugs with this link but not with the latest [preview](https://open-ebooks-web-95rl301md-nypl.vercel.app/).

2021-12-28 18:13 UTC, samanthaandrews commented
I was under the impression that the initial preview url updated with each commit! Am I wrong?

I did some initial testing with the url that @Toxiapo posted, and have still run into the issue with hitting the third party authentication error when clicking a book. It doesn't happen with every book, but once I've clicked around enough I eventually hit it.

2021-12-28 18:36 UTC, kristojorg commented
> Even just after successfully logging in, I will randomly get redirected to the login page with the "Error in authentication service" error message. This seems to consistently happen when clicking a book link as shown in the video below. Perhaps this issue and the other one I just mentioned are related?

This is the auth error we are waiting for the Circ Manager oAuth work to resolve. We should try to find a better way to handle it, but I think that's for a separate ticket. This isn't a new error originating from this code, we are just checking auth status a bit more frequently now, and thus running in to this error more frequently.

> I was under the impression that the initial preview url updated with each commit! Am I wrong?

This is true, but you might have to do a hard refresh to get the latest update. Do you mind trying with a hard refresh and letting me know if you still see that bug on book links?

2021-12-28 18:44 UTC, samanthaandrews commented
@kristojorg I haven't seen it after hard refresh, just the authentication issue. I definitely think these changes give the app a big performance boost, but dang that auth issue results in a pretty poor user experience! I know the backend team is working on the oauth stuff currently, but we should probably let Miguel know that this issue will arise more frequently with these changes. I think it's ok since the app is still in beta, but definitely crucial to fix before taking it out of beta.

I'll review the code later this evening! Going to be offline for the next few hours.

Another good thing is that since these changes make the app run faster, Cypress tests also seem to be running more quickly 🏃

2021-12-29 03:16 UTC, samanthaandrews requested changes
Just a few very small things! Looks really great. I'm excited about these changes.

I'm thinking we should just merge with the failing Cypress tests for now. I think as an admin you can do that? I'll have a PR soon with the refactored tests.

2021-12-29 03:16 UTC, samanthaandrews commented on src/utils/auth.ts
>  }
nit: Just realized there is a duplicate function in the code base inside `src/auth` called `generateToken()` that we could probably use here instead of `generateCredentials()`.

2021-12-29 20:35 UTC, kristojorg commented on src/auth/useCredentials.ts
> +  const [hasLoaded, setHasLoaded] = React.useState(false);
Done!

2021-12-29 20:37 UTC, kristojorg commented on src/components/Collection.tsx
> +        <title>{collection.title}</title>
Yea they should all have titles, that's part of the OPDS contract. Previously we had this weird page at /app where you were viewing a collection but had a different title. I just removed that.

2021-12-29 20:39 UTC, kristojorg commented on src/components/context/UserContext.tsx
> +    router.reload();
Yea this is something I noticed too and resolved in my new auth pages PR that follows this one up.

2021-12-29 20:41 UTC, kristojorg commented on src/components/context/__tests__/UserContext.test.tsx
> +  expect(Cookie.remove).toHaveBeenCalledTimes(2);
Yea I was getting a bug where sometimes a cookie wouldn't be removed, and it seemed to be mitigated by simply calling it twice haha... I can try removing and re-testing though to see if it was some other issue

2021-12-30 02:45 UTC, samanthaandrews approved these changes

2021-12-30 02:48 UTC, samanthaandrews commented
I will fix these failing remaining Cypress tests now, or comment out the ones that are consistently failing (navigating directly to a book is pretty much always hitting the 502 error, which i will resolve in a subsequent PR).

2021-12-30 03:52 UTC, samanthaandrews commented
These tests are all failing due to the 502 third party errors that are preventing navigating around the app as expected. I'm working on mocking the nextjs server so we can mitigate this. In the meantime, I am ok with disabling the Cypress status check in order to merge these changes. Or we can wait for my subsequent PR.

2021-12-30 04:00 UTC, kristojorg commented
@samanthaandrews I've moved this to ready for QA and am awaiting a QA approval before I merge, so we can wait on your PR for now.

2022-01-24 19:51 UTC, hokei commented
> Update from convo with leonard:
> 
> * We can make a HEAD request to a collection to determine if a user can access it.
> * Only the root lane changes per patron. We can fetch the root lane for the user and get the redirect that the server sends and redirect the user there.
> * There would be no such thing as `/app` then. You would always get redirected to your specific root lane.

Thinking about stuff that might be coming up - if the school system wanted to have a collection for everyone, would that be a thing that CPW isn't concerned with?  AKA it would be reflected in the root lane response that's from the circulation manager?

2022-01-26 00:03 UTC, merged