OE-313: add nock and configure with Cypress
NYPL-Simplified/circulation-patron-web pull request #333
Opened 2022-01-03 07:33 UTC by samanthaandrews

https://www.youtube.com/watch?v=33Hq41O0bvU

2022-01-03 07:44 UTC, samanthaandrews commented
I followed the recommended way to stub network calls in Next.js in the getServerSideProps method from this [YouTube video](https://www.youtube.com/watch?v=33Hq41O0bvU) and [blog post](https://glebbahmutov.com/blog/mock-network-from-server/), which uses a library called `nuxt`. I can confirm that the Next server is being run locally within Cypress, however I'm struggling to actually see the intercepted network calls return the mocked data.

I _think_ that once we get this working, we will be able to intercept the redirects and always return the appropriate data after we hit the `patrons/me` endpoint, but honestly I'm unsure. Cypress doesn't seem to know that we are ever hitting that endpoint, as it's never shown in the Cypress interface when the tests run. It only knows that we are sometimes being redirected to a different page, and that's what I'm hoping to control by adding `nuxt` to intercept these calls.

Maybe we can pair on this @kristojorg because right now I'm unsure if this is the right approach and if so, if I'm somehow missing something about the way `nuxt` is intercepting data.

2022-01-04 23:43 UTC, samanthaandrews commented
For some reason, after successfully mocking routes all day, I am now unable to build the app with MSW, getting the following error:

`ApplicationError: App Startup Failure: App Startup Failure: FetchError: request to https://qa-circulation.openebooks.us/USOEI/authentication_document failed, reason: Unexpected MODIFIER at 87, expected END`

Going to log off for the day and come back to this tomorrow.

2022-01-08 02:07 UTC, samanthaandrews commented on cypress/support/commands.ts
> +export const isEnd2EndTest =
I added this check to only add Cypress intercepts and waits if `msw` is off or if we are running against the qa-web url. This makes it easier to run these end-to-end tests also when `msw` is enabled if we ever decide we want that functionality. However, it is maybe annoying to see it sprinkled around these tests. Lmk if you think it's ok or if I should remove it.

2022-01-08 02:07 UTC, samanthaandrews commented on cypress/support/commands.ts
> +    Cypress.config().baseUrl === "http://localhost:3000");
I added this check to only add Cypress intercepts and waits if msw is off or if we are running against the qa-web url. This makes it easier to run these end-to-end tests also when msw is enabled if we ever decide we want that functionality. However, it is maybe annoying to see it sprinkled around these tests. Lmk if you think it's ok or if I should remove it.

2022-01-08 02:10 UTC, samanthaandrews commented on cypress/tests/open-ebooks/integration/web-reader/read-books.ts
> +  it("Can turn Almost Midnight pages in paginated mode & scroll in scrolling mode", () => {
I changed this test to also use the Almost Midnight book just because I didn't want to have to add more mocked data at this time. But for future tests I think adding different books to mock is worthwhile.

2022-01-08 02:11 UTC, samanthaandrews commented on cypress/tests/open-ebooks/server-e2e/borrow-read-return/borrow-read-return.ts
> +    cy.checkoutAllAccessBook(ALMOST_MIDNIGHT_REVOKE_URL);
I changed this test to also use the Almost Midnight book to also reduce the number of mocks I was adding for books that were opened in the web reader. Once again, I think we can add additional books as we move forward.

2022-01-08 02:12 UTC, samanthaandrews commented on cypress/tests/open-ebooks/server-e2e/borrow-read-return/borrow-read-return.ts
> +    // FIXME: navigating back to root with the back button in the web reader
I noticed this issue where clicking the "Back to open ebooks" button sometimes doesn't navigate you back to the root collection, but it seems to only be happening in development. I think we should create a ticket to look into this.

2022-01-08 02:17 UTC, samanthaandrews commented on msw/handlers/index.ts
> +  }),
When I mocked this with a 200 response, it was causing an infinite redirect loop when logging in with `msw` enabled. Not mocking this one request solves the issue, and thus far I haven't seen any 502 errors in development.

2022-01-08 02:18 UTC, samanthaandrews commented on public/mockServiceWorker.js
> + * - Please do NOT serve this file on production.
It seems we are not supposed to serve this file on production. Should I remove it from git and instead add a step in the README and in the CI with a command that instantiates it?

2022-01-08 02:22 UTC, samanthaandrews commented
Currently two suites are failing due to Cypress not being able to install the decryptor: `> Decryption Error: Attempting to instantiate a WebpubDecryptor without access to @nypl-simplified-packages/axisnow-access-control-web.`

2022-01-11 15:58 UTC, kristojorg commented on cypress/tests/open-ebooks/server-e2e/borrow-read-return/borrow-read-return.ts
> +    // FIXME: navigating back to root with the back button in the web reader
Nice, yea let's make a ticket for that

2022-01-11 16:00 UTC, kristojorg commented on public/mockServiceWorker.js
> + * - Please do NOT serve this file on production.
Hmmm good question. And it needs to be in `/public`? I thought there was a way without putting it there

2022-01-11 16:02 UTC, kristojorg commented
> Currently two suites are failing due to Cypress not being able to install the decryptor

Ah yes, this was part of the reason I initially liked having the tests run against vercel. But we can make it work. We need to put a `.npmrc` file in github secrets and use that when installing in CI

2022-01-11 22:54 UTC, samanthaandrews commented
I have tried so many configs and none of them seem to installing the decryptor! You'll see in the `.github/workflows/oe-integration-cypress.yml` file I've tried using the `actions/setup-node@v2` way and manually setting the .npmrc file with this command `echo "@nypl-simplified-packages:registry=https://npm.pkg.github.com/nypl-simplified-packages\n//registry.npmjs.org/:_authToken=${{ secrets.AXIS_NOW_ACCESS_TOKEN }} > ~/.npmrc`

Maybe we can look at this together tomorrow morning after our Open Ebooks meetings? @kristojorg

2022-01-12 05:31 UTC, kristojorg commented
Yep let's do that @samanthaandrews !

2022-01-12 16:17 UTC, samanthaandrews commented on cypress/tests/open-ebooks/server-e2e/borrow-read-return/borrow-read-return.ts
> +    // FIXME: navigating back to root with the back button in the web reader
https://jira.nypl.org/browse/OE-320

2022-01-13 23:12 UTC, samanthaandrews commented on package.json
> +    "build-for-cypress-integration-tests": "APP_ENV=test npm run build",
I tried setting NODE_ENV=test here (which is a value allowed by Next), but it wasn't always getting to set to `production` when running npm run build. This is because Next enforces this value to be `production` when running the build command. Here is the [thread](https://github.com/vercel/next.js/issues/17032) about it, which recommends using APP_ENV instead.

We could instead change this to be a boolean labeled by IS_CYPRESS_TEST_ENV or something similar. Lmk if you think that's better.

2022-01-13 23:13 UTC, samanthaandrews commented on public/mockServiceWorker.js
> + * - Please do NOT serve this file on production.
It does need to be in `/public`. If it's not there, the app can't find it and won't build.

2022-01-13 23:16 UTC, samanthaandrews commented on .github/workflows/oe-integration-cypress.yml
> +      - name: Authenticate with the Github Package Registry
I ended up putting everything into one command instead of running the build and install steps separately. This is because whenever I started the app in the separate step, the decryptor was not available, despite it being available in the previous install step. I really don't know why this is the case, but I think this is also cleaner and the tests only take about 4 to 5 minutes to run, which seems reasonable. Also, this config is now a lot simpler.

2022-01-14 15:31 UTC, kristojorg commented on .github/workflows/oe-integration-cypress.yml
> +      - name: Authenticate with the Github Package Registry
Do you mean it's not parallel now?

2022-01-14 15:31 UTC, kristojorg commented on cypress/support/commands.ts
> +    Cypress.config().baseUrl === "http://localhost:3000");
You could maybe add a command or overwrite the intercept and wait commands to be enabled only when running not as e2e? That way we don't need to if/else in the test body itself.

I'd probably add a new command so it's clear to a new dev what it's doing (not always intercepting)

2022-01-14 20:28 UTC, samanthaandrews commented on .github/workflows/oe-integration-cypress.yml
> +      - name: Authenticate with the Github Package Registry
nvm i figured this out. build/install step is now still separate and occurs before the tests run.

2022-01-18 19:49 UTC, samanthaandrews commented on cypress/support/commands.ts
> +    Cypress.config().baseUrl === "http://localhost:3000");
I have a fix for this I'm just waiting to test it once the fixed auth_document issue is deployed to qa.

2022-01-24 18:10 UTC, kristojorg requested changes
Just a few things

2022-01-24 18:10 UTC, kristojorg commented on cypress/tests/open-ebooks/integration/login/login-navigation.ts
> +  it.only("redirects logged in user to nextUrl present", () => {
Stray .only

2022-01-24 18:10 UTC, kristojorg commented on cypress/tests/open-ebooks/integration/web-reader/read-books.ts
> +  it("Can turn Almost Midnight pages in paginated mode & scroll in scrolling mode", () => {
Yea makes sense. We can do that explicitly in tests for multiple books

2022-01-24 18:10 UTC, kristojorg commented on cypress/tests/open-ebooks/server-e2e/borrow-read-return/borrow-read-return.ts
> +    cy.checkoutAllAccessBook(ALMOST_MIDNIGHT_REVOKE_URL);
👍

2022-01-24 18:10 UTC, kristojorg commented on cypress/tests/open-ebooks/server-e2e/login/firstbook-login.ts
> +    cy.intercept("GET", `${SERVER_URL}/loans`).as("loans");
Do we want to be intercepting any requests in e2e tests?

2022-01-24 18:10 UTC, kristojorg commented on cypress/tests/open-ebooks/server-e2e/login/firstbook-login.ts
> +    cy.intercept("GET", `${SERVER_URL}/loans`).as("loans");
Oh nvm it's so confusing in the api language that this is just aliasing it.

2022-01-24 18:10 UTC, kristojorg commented on msw/fixtures/open-ebooks/fulfillmentInfoAlmostMidnight.json
> +}
These should be fake info, although that admittedly makes it impossible to read the actual book. We would need to provide the book as a fixture also. Annoying. But we can't have this data in the repo unfortunately.

2022-01-24 18:10 UTC, kristojorg commented on package.json
> +    "build-for-cypress-integration-tests": "APP_ENV=test npm run build",
I think a boolean is more clear, but also should be `NEXT_PUBLIC_` otherwise it is only available server side. I would also rename this to `build:cypress:ci` or something in line with our other names

2022-01-24 18:10 UTC, kristojorg commented on src/middleware/check-auth.ts
> -          "502 Error while checking patrhon auth. Redirecting to login."
Lol thanks for fixing these

2022-01-24 18:51 UTC, samanthaandrews commented on cypress/fixtures/example.json
> +}
Ah yeah, let's just keep it there

2022-01-24 19:03 UTC, samanthaandrews commented on cypress/tests/open-ebooks/integration/browse/browse.ts
> +    cy.visit(ALL_ACCESS_ROOT_COLLECTION_PATH);
Yeah I think you're right. I'll change it back!

2022-01-24 19:10 UTC, samanthaandrews commented on README.md
> +To turn off MSW in development, you can set NEXT_PUBLIC_API_MOCKING=false in your `.env.local` file, which is not added to git. However, if you're running any of the tests in this folder `cypress/tes
I'm not sure it should _always_ be enabled in Cypress, though. It should always be enabled for test files in the `integration` directory, but never in the `server-e2e` directory. If I want to debug something in the server-e2e folder locally, then I should be able to easily turn msw off. I could make an event that runs on a before hook in each file in the `integration` directory? We'd just have to remember to use this command in all future test suites in that directory.

2022-01-24 21:36 UTC, samanthaandrews commented on msw/fixtures/open-ebooks/fulfillmentInfoAlmostMidnight.json
> +}
I could add these values as secrets in GH Actions. Would that be an appropriate fix? I tried not mocking this call at all and the tests fail if we don't include this fixture.

2022-01-25 22:37 UTC, kristojorg approved these changes
Let's do this thing yeehaw

2022-01-25 22:37 UTC, merged