OE-341 dockerize
NYPL-Simplified/circulation-patron-web pull request #387
Opened 2022-03-14 20:50 UTC by hokei

2022-03-14 22:23 UTC, mwbenowitz approved these changes
This looks good to me! I have a few questions/comments but this should get us a QA instance in ECS. 👍

2022-03-14 22:23 UTC, mwbenowitz commented on .github/workflows/release-qa.yml
> +    types: [opened, synchronize, reopened]
Just want to confirm that we want to run this on all of these actions since it will result in a decent number of builds. (Nothing wrong with this will just make the CI/CD run slower!)

2022-03-14 22:23 UTC, mwbenowitz commented on Dockerfile
> +
In the previous version (the one we were working on), there was an `apk add git` step here. Did that turn out to be unnecessary? I was running into issues without it

2022-03-14 22:23 UTC, mwbenowitz commented on next.config.js
> +  execSync("git rev-parse HEAD").toString().trim();
oh, I see, I bet this is why `git` isn't necessary in the docker build process

2022-03-14 22:23 UTC, mwbenowitz commented on Dockerfile
> +ENV PORT 3000
I'd just move this up to be with the other `ENV` variables just for consistency/clarity.

2022-03-15 13:43 UTC, hokei commented on .github/workflows/release-qa.yml
> +    types: [opened, synchronize, reopened]
No, this is just for me to test right now.  I'm going to have to ask you again about how to get Tugboat up, because we will want that for all actions.

2022-03-21 11:06 UTC, kristojorg commented on .github/workflows/release-qa.yml
> +          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA=$IMAGE_TAG_SHORT --build-arg NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF=$IMAGE_TAG_SHORT --buil
How do these environment variables get in here?

2022-03-21 11:08 UTC, kristojorg commented on .tugboat/config.yml
> +        - npm run start &
Do we need to set all env vars here? Or are they read from `.env` file? Also, we should set these env vars when running `npm run build` as well, as it depends on them.

2022-03-21 11:10 UTC, kristojorg commented on Dockerfile
>  RUN apk add git
I don't think we need this anymore. We add the git commit sha and ref when running the build command unless I'm mistaken.

2022-03-21 13:37 UTC, mwbenowitz commented on .tugboat/config.yml
> +        - npm run start &
looks like the `CONFIG_FILE` var is set in the .env file, so that can probably get skipped. The other two might need to change depending on environment, so I think it's better to have them here. They can definitely get set before the build phase though!

2022-03-22 14:49 UTC, kristojorg commented on .tugboat/config.yml
>          - npm run start &
Is this supposed to have an ampersand at the end of it?

2022-03-22 14:53 UTC, kristojorg commented on .github/workflows/release-qa.yml
> +  publish_qa:
Is there a corresponding way to release production?

2022-03-22 15:54 UTC, hokei commented on .github/workflows/release-qa.yml
> +  publish_qa:
yeah I'm gonna copy this over to a `release-production.yml` once we have that set up

2022-03-22 16:54 UTC, mwbenowitz commented on .tugboat/config.yml
>          - npm run start &
it is! It's a quirk in Tugboat, it needs it to keep that process up and running, otherwise it exits the container for some reason

2022-03-30 16:34 UTC, kristojorg commented
@hokei is this ready to merge or still in progress? Just for the sake of my notifications, can we move it to draft status until it's ready to review (unless it is now)?

2022-04-15 14:21 UTC, samanthaandrews commented on Dockerfile
> +ENV CONFIG_FILE app_config/opene.yml
Since we have been removing multi-library setup in recent weeks, we no longer need this CONFIG_FILE env var. The app is now fetching the open ebooks authentication_document at build time.

Because of this, there are a few other additions to the env vars, which are in the current `.env` file. I'm not sure if this docker file picks up variables from that file?

We do need to add the following env vars to the production build script:

NEXT_PUBLIC_CM_URL=https://circulation.openebooks.us
NEXT_PUBLIC_GTM_ID=XXXXXX @kristojorg do you know if this google tag manager id is somewhere in our Vercel builds? if not i don't think we need to include it
NEXT_PUBLIC_BUGSNAG_API_KEY=XXXXXX @kristojorg should be able to get you this key

and potentially NEXT_PUBLIC_ENABLE_MSW=false only if this setup isn't picking up variables from the `.env` file directly.

2022-04-15 14:25 UTC, samanthaandrews requested changes
We've changed env vars in recent weeks 😣, so that is the only thing I see that needs to be changed!

2022-04-15 17:33 UTC, hokei commented on Dockerfile
> +ENV CONFIG_FILE app_config/opene.yml
Ah I was going to comment that it was interesting that the staging deploy was working without these env variables but Jiayong noticed that we can't read books, which makes sense!  I'm gonna put this PR back into draft mode until I meet with Greg on Monday to fix the env variables on the CF template.

2022-04-18 13:57 UTC, samanthaandrews commented
I'm thinking we should also update the README with the latest deploy to prod instructions. I'm also curious about what the rollback process looks like, and if possible let's include these instructions in the README too.

2022-05-11 22:36 UTC, hokei commented on README.md
> +  - [Community Demo](#community-demo)
I'm not quite sure how this ToC is being generated?  Deleting stuff from this only results it stuff being added back on save.

2022-05-11 22:39 UTC, hokei commented
@samanthaandrews this is ready for review again.  Can you also verify that the deploy to https://staging-docker.openebooks.org/ contains the latest Staging?

2022-05-12 15:03 UTC, samanthaandrews commented on README.md
> +  - [Community Demo](#community-demo)
I think this ToC is auto-generated based on whatever headings exist in the README.md? But I could be wrong about that

2022-05-12 15:37 UTC, samanthaandrews commented on Dockerfile
> +RUN if [ "$NODE_ENV" = "production" ]; \
Does this `$NODE_ENV` get set to production only in the `release-prod.yml` github action? Just curious because I know that anytime we run `npm run build`, the NODE_ENV is set to `production` by default. That doesn't seem to be what's happening here, since on https://staging-docker.openebooks.org/ I see we are hitting qa-circulation endpoints, but just want to be sure.

2022-05-12 15:39 UTC, samanthaandrews commented on Dockerfile
> +RUN if [ "$NODE_ENV" = "production" ]; \
Ah i see that we're not running the build:docker command until after setting NEXT_PUBLIC_CM_URL, so yeah that NODE_ENV must be getting set in the release-prod.yml action.

2022-05-12 15:41 UTC, samanthaandrews approved these changes
Confirmed that the code running on https://staging-docker.openebooks.org/ is the most up to date, since I can see this page https://staging-docker.openebooks.org/contribute.html is correctly getting redirected to `https://staging-docker.openebooks.org/partners` which is a recent change that we merged to staging.

2022-05-12 18:03 UTC, hokei commented on Dockerfile
> +RUN if [ "$NODE_ENV" = "production" ]; \
NODE_ENV gets set here, I think: https://github.com/NYPL-Simplified/circulation-patron-web/pull/387/files#diff-7c7339ed739b954dcbb42e0ce08bfb4425576f550e3e6a06204ef9bcc96ac102R54

2022-05-12 18:08 UTC, merged

2022-05-16 12:39 UTC, kristojorg commented on Dockerfile
> +RUN if [ "$NODE_ENV" = "production" ]; \
I would rather we not change the `NODE_ENV` variable when running in a "production like" environment. We currently rely on this env var being "production" in quite some places, and I know that in some environments (such as a real testing env) it's difficult if not impossible to actually change the `NODE_ENV`. I think instead of this if/else we can simply pass in the `NEXT_PUBLIC_CM_URL` as an env variable itself

2022-05-16 12:44 UTC, kristojorg commented on README.md
> +  - [Community Demo](#community-demo)
I also don't remember haha

2022-05-16 13:02 UTC, hokei commented on Dockerfile
> +        else NEXT_PUBLIC_CM_URL=https://qa-circulation.openebooks.us npm run build:docker; fi
I'll make a follow up!

2022-05-16 18:17 UTC, hokei commented on Dockerfile
> +        else NEXT_PUBLIC_CM_URL=https://qa-circulation.openebooks.us npm run build:docker; fi
I wasn't able to get this done before meetings started up today. Thanks Kristo for filing https://jira.nypl.org/browse/OE-501