OE-409: Remove `withAppProps` and `LibraryContext`
NYPL-Simplified/circulation-patron-web pull request #396
Opened 2022-03-27 03:11 UTC by samanthaandrews

https://jira.nypl.org/browse/OE-409

2022-03-28 18:37 UTC, samanthaandrews commented on src/utils/auth.ts
> -export function flattenAuth(authDoc: OPDS1.AuthDocument): AppAuthMethod[] {
Moved this to `src/dataflow/getLibraryData.ts` (where it is being called) because it cannot exist in a file that also accesses the env constants before they're initialized. This is because `getLibraryData()` is now being called at build time.

2022-04-01 12:19 UTC, kristojorg commented on cypress/support/utils.ts
> +    path: `${READ_PATH}/${encodeURIComponent(GN_FULFIL_ENDPOINT)}`,
nit: spelling

2022-04-01 12:19 UTC, kristojorg commented on cypress/support/utils.ts
> +    path: `${READ_PATH}/${encodeURIComponent(GN_FULFIL_ENDPOINT)}`,
nvm apparently they are both correct spellings I just looked it up lol

2022-04-01 12:42 UTC, kristojorg requested changes
Yeeehaw this is nice! Just a couple comments

2022-04-01 12:42 UTC, kristojorg commented on src/components/Error.tsx
> +          <Link href={`/app ?? ""}`}>
I don't think we need the `??` here anymore. Should just link to `/app`

2022-04-01 12:42 UTC, kristojorg commented on src/pages/app/collection/[collectionUrl].tsx
> +    };
Maybe we should extract this into a utility or something?

2022-04-01 21:41 UTC, samanthaandrews commented on src/pages/app/collection/[collectionUrl].tsx
> +    };
done!

2022-04-01 22:21 UTC, samanthaandrews commented on src/components/WebReader.tsx
>    if (!bookUrl) {
I noticed Cypress errors in the useSwr test, and after fixing some of those paths and endpoints, I realized the test failure was actually identifying a bug where the `query` from `useRouter()` is undefined upon first render, triggering this bookUrl to be undefined. This doesn't happen if you navigate to the page from the Read button, but it does happen if I reload `read` the page directly, as described in this [question](https://stackoverflow.com/questions/69412453/next-js-router-query-getting-undefined-on-refreshing-page-but-works-if-you-navi) on StackOverflow.

We weren't hitting this error in the past because we were previously running `getStaticProps(`) on the component that calls this `<WebReader />` component. According to the [Next docs](https://nextjs.org/docs/advanced-features/automatic-static-optimization#how-it-works) it looks like this means we might want to be leveraging this router.isReady object, but I wanted to check to make sure this is the approach we want to use? Alternatively we could use getServerSideProps to return context.query.

2022-04-03 18:45 UTC, samanthaandrews commented on src/components/WebReader.tsx
>    if (!bookUrl) {
I ended up using getServerSideProps because the code seemed more readable than using `router.isReady` and putting another useEffect hook in the WebReader component. Lmk what you think.

2022-04-04 14:34 UTC, kristojorg commented on src/components/WebReader.tsx
>    if (!bookUrl) {
So the downside to this is that it means we have to run server-side code for every time we view a web reader page, whereas previously it was statically generated on the server and then the client runs code to fetch the resources it needs. I do hear you that this is more readable, but it also seems like a silly thing to use server side rendering for.

It's annoying that the router object isn't ready on first render, but we have had this problem in other places as well and resorted to `router.isReady`. So I think we should do the same here. I would like the eventually statically render the web-reader's nicer loading indicator here so that users only have one loading screen they see immediately when they request a reader page.

2022-04-04 16:42 UTC, samanthaandrews commented on src/components/WebReader.tsx
>    if (!bookUrl) {
Ok this makes sense. I updated it to use `router.isReady` instead of `getServerSideProps()`.

2022-04-07 12:08 UTC, kristojorg approved these changes
Awesome!

2022-04-07 12:08 UTC, merged