OE-404: Refactor refresh token logic
NYPL-Simplified/circulation-patron-web pull request #405
Opened 2022-04-08 15:25 UTC by samanthaandrews

Refactors refresh token logic into a `verifyToken(credentials)` utility that can be called on the browser or server-side. On the browser side, this function is being called inside a new hook called `useGetCredentials()` which is currently only being called within the UserContext. I created a hook to keep this logic separate and readable instead of adding another `useEffect hook` within the UserContext itself.

This means that First Book tokens are now potentially refreshed (if within 5 minutes of expiration) on each page load (via middleware) or on every component mount that uses the `token` from the UserContext.

2022-04-08 15:59 UTC, samanthaandrews commented
@kristojorg There is one edge-case that I haven't yet handled, but would like to in this PR, with your input on the best way forward. The `verifyToken()` function is currently being run in middleware anywhere `getCredentials()` is happening. It's also being run anywhere the `token` is accessed via the UserContext. This catches most of the places, and has been working well in all of my manual testing.

But let's say a user leaves the open ebooks tab open for a few hours, and then returns to it and immediately clicks the "borrow" or "return" buttons. At that point, the token from the UserContext has expired, so they receive the error that the token has expired.

Paths forward:
1. Run the verifyToken() function again within the borrow/return hook.
2. Let users hit this edge case, but encourage them to reload the page to try again if they hit this error by adding a "Refresh" button.

Number 1 is nice because it means users probably won't ever see the token expiration error, but I hesitate to scatter verifyToken() in too many places throughout the app. In this case, though, perhaps it makes sense.

2022-04-08 20:41 UTC, Toxiapo commented
> 1. Run the verifyToken() function again within the borrow/return hook.
> 2. Let users hit this edge case, but encourage them to reload the page to try again if they hit this error by adding a "Refresh" button.
> 
> Number 1 is nice because it means users probably won't ever see the token expiration error, but I hesitate to scatter verifyToken() in too many places throughout the app. In this case, though, perhaps it makes sense.

FWIW, an expiration error message is reasonable for apps that require authentications, but since we are going to make FB users stay logged in _indefinitely_, Number 1 sounds like the approach here.

2022-04-11 13:52 UTC, kristojorg commented
I think we should do option 1. I would say we should actually just make it so that the only way we ever access the token is by calling an async function like `getToken` which internally verifies and possibly refetches it. I would pass that down in context from `UserContext` instead of the `token` itself.

2022-04-11 14:04 UTC, kristojorg reviewed
Just a couple thoughts

2022-04-11 14:04 UTC, kristojorg commented on src/utils/auth.ts
> +  }
I would probably make this return the original credentials if they don't need to be refreshed so that consumers of the function don't need to have the added step of checking for undefined

2022-04-11 16:55 UTC, samanthaandrews commented on src/utils/auth.ts
> +  ).toUTCString();
`new Date()` creates a date object in the user's time zone, and `toUTCString()` is the most straightforward way to convert that value to UTC that is a human readable value and not just a number in milliseconds. since I didn't want to be concerned with a user's time zone at all, this seemed like the best value to pass through. ultimately all we need is a value in UTC milliseconds anyway since that's what we use to compare when we verify the token.

i will update to use `expiresAt` i agree it is more explicit!

2022-04-14 14:29 UTC, kristojorg requested changes

2022-04-14 14:29 UTC, kristojorg commented on src/hooks/useBorrowOrReturn.ts
> +    const currentCredentials = getCredentialsBrowser();
Should we just use `useVerifyToken` here instead of manually verifying it before using it?

2022-04-14 14:29 UTC, kristojorg commented on src/hooks/useBorrowOrReturn.ts
> +      const updatedCredentials = await verifyToken(currentCredentials);
This is the duplication I mean. I can see this easily being forgotten. Seems it would be better to have only one blessed way to access the token and it automatically verifies it

2022-04-14 14:29 UTC, kristojorg commented on src/hooks/useVerifyToken.ts
> +    console.log("credentials have changed inside useEffect hook");
Stray log

2022-04-14 14:29 UTC, kristojorg commented on src/utils/auth.ts
> +  console.log("fetchFirstbookJWT");
Stray log

2022-04-14 14:29 UTC, kristojorg commented on src/utils/auth.ts
> +        console.log("!IS_SERVER");
stray logs

2022-04-14 14:29 UTC, kristojorg commented on src/utils/auth.ts
> + * existing credentials
Should note here that in browser context it will also update the cookie. In server context it will simply return the new credentials

2022-04-14 15:51 UTC, samanthaandrews commented on src/hooks/useBorrowOrReturn.ts
> +    const currentCredentials = getCredentialsBrowser();
Yes this is the crux of the issue that I've been thinking about and I agree with you 100%. I created `useVerifyToken()` as a hook to wrap the `verifyToken()` async function so that tokens will be verified whenever we need to access the token within the top-level of a React component the same way we've always done it. `useVerifyToken()` is being called in UserContext, so a token is verified whenever a component mounts. But this doesn't cover the edge-case for when a component has mounted and been sitting for over 55 minutes. In that case, it needs to be verified again when a user clicks the "Borrow" or "Return" buttons.

So now I'm thinking I should more change the way we access tokens within React components. Perhaps it's best to  only verify & pass the token through to a fetch function directly, instead of verifying it on component mount. I think it would help me to can talk it through with you tomorrow or whenever you're feeling better!

2022-04-22 20:28 UTC, samanthaandrews commented on src/components/__tests__/BookListItem.test.tsx
> -  test("shows loading state when borrowing, borrows, and revalidates loans", async () => {
Removed some of these assertions in favor of testing this logic directly in the <Borrow> component tests.

2022-04-22 20:29 UTC, samanthaandrews commented on src/components/__tests__/Return.test.tsx
> +import {
Added a similar set of tests for <Return />

2022-05-02 03:08 UTC, Toxiapo approved these changes
The code looks good to me, I think we can pass this to QA.

2022-05-02 13:44 UTC, kristojorg commented on src/hooks/useGetCredentials.ts
> +  }, []);
Ok my one question here is whether we need to do anything to this react state when the credentials in the cookie change? Or are we sure that the only time we do that is before a browser refresh? I think that is true, like in login and logout, but am not 100% positive.

2022-05-02 13:47 UTC, kristojorg reviewed
Just the one question, but otherwise I think this is good!

2022-05-02 20:24 UTC, samanthaandrews commented on src/hooks/useGetCredentials.ts
> +  }, []);
I don't think we need to do anything to this state when the credentials in the cookie change. I see what you're saying though, like if there are instances where within a component we are setting or clearing the credentials using js-cookie we would probably need to account for that in this hook. But currently we are only setting & unsetting auth cookies on login and logout.

2022-05-04 21:43 UTC, kristojorg approved these changes
Looks good!

2022-05-04 21:45 UTC, merged