Start server within cypress
NYPL-Simplified/circulation-patron-web pull request #421
Opened 2022-05-05 21:00 UTC by Toxiapo

2022-05-10 14:54 UTC, Toxiapo commented on cypress/support/commands.ts
> +      signin(userType: UserType, appType?: AppType): void;
I created this new command to sign in using the GUI and used it throughout the integration tests because MSW doesn't intercept the cy.requests  used in `signinByApi`.

2022-05-10 14:55 UTC, Toxiapo commented on cypress/support/utils.ts
> -export const GN_BOOK_ENDPOINT = `${SERVER_URL}/works/Axis%20360%20ID/0020037525`;
We can finally remove this blob of code now that intercept works : )

2022-05-10 14:56 UTC, Toxiapo commented on cypress/tests/open-ebooks/integration/browse/breadcrumb-navigation.ts
> +  });
This is really annoying because sometimes cypress doesn't clear the cookie even though by default it should. So I am just explicitly removing these cookies for now.

2022-05-11 21:28 UTC, samanthaandrews commented on msw/handlers/index.ts
> +  // }),
Can we remove this?

2022-05-11 21:56 UTC, samanthaandrews requested changes
This looks so good! Just a few questions & some small cleanup stuff. Let's sync up tomorrow after standup and talk through the `signin` command bc I just want to make sure I understand it and consider what the `e2e` tests will need to change (if anything).

2022-05-11 21:56 UTC, samanthaandrews commented on msw/handlers/index.ts
> +  // }),
Can we remove this?

2022-05-11 21:56 UTC, samanthaandrews commented on src/components/Error.tsx
> -    //Instead, we display a PageLoader to avoid the undesirable display of an error screen while the user waits for that redirect to occur
Is this no longer the case?

2022-05-11 21:56 UTC, samanthaandrews commented on cypress/plugins/index.ts
We can remove all references to this env var, right? And the unused `cypress:ci:build` and `cypress:ci:start` commands within the `package.json` too. There are several references to `NEXT_PUBLIC_ENABLE_MSW` in the code and I just want to confirm it either needs to be there or it can be removed.

Also we should probably update the README to include info about how to run Cypress tests. When I pulled down your PR I defaulted to building and starting the app, and then realized that I Cypress was now controlling the `start` process so I didn't need to do that.

2022-05-12 18:53 UTC, samanthaandrews commented on cypress/plugins/index.ts
Maybe we should also remove the reference to `NEXT_PUBLIC_ENABLE_MSW` in the `.env` file since it no longer needs to be set at that level and we aren't running the risk of that module getting bundled in production. I'm also wondering if we can delete the `mockServiceWorker.js` file or if it's still necessary.

2022-05-12 19:09 UTC, samanthaandrews commented on cypress/plugins/index.ts
Wait I am wrong about `mockServiceWorker.js`. We still need that.

2022-05-12 19:13 UTC, samanthaandrews commented on cypress/plugins/index.ts
But we can remove `NEXT_PUBLIC_ENABLE_MSW` in `.env`. I ran `ANALYZE=true npm run build` on your branch and confirmed that msw is being tree-shaken out of production builds, so that's good.

2022-05-12 19:34 UTC, samanthaandrews commented on next.config.js
> -  NEXT_PUBLIC_ENABLE_MSW,
Realizing we actually might need to still pass this through in order for Cypress to pick up this env var

2022-05-12 19:57 UTC, Toxiapo commented on next.config.js
> -  NEXT_PUBLIC_ENABLE_MSW,
ahhh, maybe that's why the tests are failing! I will give this a try.

2022-05-12 20:08 UTC, Toxiapo commented on cypress/plugins/index.ts
 Done

2022-05-12 20:51 UTC, Toxiapo commented on next.config.js
> -  NEXT_PUBLIC_ENABLE_MSW,
nvm, it was because I named the env variable wrong!

2022-05-12 21:25 UTC, samanthaandrews commented on cypress/plugins/index.ts
> +    // onUnhandledRequest: "bypass"
Do we need this to bypass or should we remove it?

2022-05-12 21:28 UTC, samanthaandrews approved these changes
One small question about the 'bypass' that was commented out. I think this is good to go.

2022-05-12 21:30 UTC, Toxiapo commented on cypress/plugins/index.ts
> +    // onUnhandledRequest: "bypass"
Oh yes, we can just turn it on now.

2022-05-12 21:39 UTC, merged