Setup chakraui base theme
NYPL-Simplified/circulation-patron-web pull request #430
Opened 2022-06-02 22:44 UTC by Toxiapo

2022-06-06 06:49 UTC, kristojorg requested changes
This looks good! The one thing I'm unsure about is if we should put more thought into our text styles. It looks like there is a standard size of headings on the non-home marketing pages (like FAQ etc). Should we try to come up with a set of text styles to fit those? Is the font size scale we have here going to fit the font sizes used in the designs?

A few other small things. But otherwise I think this gets us ready to roll out some new designs!

2022-06-06 06:49 UTC, kristojorg commented on src/marketing/theme/foundations/color.ts
> +        "60%": "#0A99A0"
I suggested on figma that we use the 300 version of each color instead of the opacities, so I don't think we need this necessarily. I think we can just use `teal.300` in these places

2022-06-06 06:49 UTC, kristojorg commented on src/marketing/theme/foundations/color.ts
> +    lightGray: "#D9D9D9",
Should this be added to the `gray` scale?

2022-06-06 06:49 UTC, kristojorg commented on src/marketing/theme/components/button.ts
> +    py: "7px",
I think we should avoid using hard coded specific pixel spacing that doesn't fall onto the spacing scale. Let's just choose a value on the scale that appears to fit as best as possible

2022-06-06 06:49 UTC, kristojorg commented on src/marketing/theme/foundations/shadow.ts
> +  gridBook: "0px 3px 2px rgba(0, 0, 0, 0.3), 0px 1px 3px rgba(0, 0, 0, 0.15)"
If these are only used in those places, I don't think we necessarily need to define them in the theme, they can just be inline styles on that component. That said, it's also not a huge problem to define them here if you prefer

2022-06-06 06:49 UTC, kristojorg commented on src/marketing/theme/foundations/raddi.ts
> +  button: "50px",
Is the button not "full" radii?

2022-06-06 06:49 UTC, kristojorg commented on src/marketing/theme/foundations/global.ts
> +    color: "ui.bodyText"
I think the `color` we should apply in a global style to the whole page to all text, if all text is supposed to be that color. Can also be defined here too, but just a note that we should do that

2022-06-06 06:49 UTC, kristojorg commented on src/marketing/theme/components/link.ts
> +}
So it looks like you're doing both the mobile menu and the desktop nav links here, but I think we will render them as separate components so I don't think we need to make the styles adapt like this, they can be separate. 

I am also wondering if this should be a `Button` style, and then to render a link version we use `<Button as={Link}>`. That way we can use these same styles for buttons and buttons that look like links (unless we don't need that, you tell me)

2022-06-06 06:49 UTC, kristojorg commented on src/marketing/theme/components/button.ts
> +        fontSize: "32px",
Same with the font size, I think we should avoid hard coding a specific pixel value but use a value from the scale instead. I tried to write out all the font sizes and weights we need in the TAD, and I think this one would have been in there

2022-06-06 06:49 UTC, kristojorg commented on src/marketing/theme/components/button.ts
> +        py: "17px",
I don't think an explicit width or height are necessary, the button should size correctly if we simply put the correct padding and fontSize, and then add some text inside. This way it will grow for longer words, shrink for shorter. The padding should also come from the theme scale. And this goes for everywhere in the designs. We shouldn't just use the specific padding in the designs, but choose whatever padding is closest from our theme scale

2022-06-06 06:49 UTC, kristojorg commented on src/marketing/theme/components/button.ts
> +    case "teal":
I don't see where the teal and magenta buttons are used, can you point me to them?

2022-06-06 13:51 UTC, Toxiapo commented on src/marketing/theme/foundations/raddi.ts
> +  button: "50px",
oh, that's right!

2022-06-06 14:00 UTC, Toxiapo commented on src/marketing/theme/components/button.ts
> +        fontSize: "32px",
Oh yes, I do have this defined, will update it now!

2022-06-06 14:39 UTC, samanthaandrews commented on src/marketing/asset/top10-teal.svg
> +<svg width="179" height="179" viewBox="0 0 179 179" fill="none" xmlns="http://www.w3.org/2000/svg">
I noticed the kerning between the 1 and the 0 doesn't match the other two Top 10 badges. Going to reach out to Jenn in the Figma file to get this fixed.

2022-06-06 14:46 UTC, Toxiapo commented on src/marketing/theme/components/button.ts
> +    case "teal":
I made an "auth" variant for the button and they are being used for the "How it works" section and the contact page form, but now that we don't have the contact page, I am wondering if I even need this variant.

I think I will keep the style for the magenta, but without the colorscheme, and remove the teal for now.

2022-06-06 15:23 UTC, Toxiapo commented
> This looks good! The one thing I'm unsure about is if we should put more thought into our text styles. It looks like there is a standard size of headings on the non-home marketing pages (like FAQ etc). Should we try to come up with a set of text styles to fit those? Is the font size scale we have here going to fit the font sizes used in the designs?

Yeah, agree. I thought defining the h1-h5 styles in global would work here, but those will get overridden if we use chakra's Heading component. i.e.`<Heading as="h1">`

I would name the heading styles `h1, h2, h3, etc`, and the subtitles with a more descriptive name like `bookTitle` in the textStyles theme,  what do you think? @samanthaandrews @kristojorg

2022-06-06 16:32 UTC, kristojorg commented on src/marketing/theme/foundations/color.ts
> +    lightGray: "#D9D9D9",
Nice yea I think let's do that to start. It's also fine to have just `gray.light` and `gray.xxlight` to start if you want

2022-06-06 16:34 UTC, kristojorg commented on src/marketing/theme/components/button.ts
> +    case "teal":
Okay yea I think we can just name this the primary variant and have these different colors. That seems fine to me

2022-06-06 16:34 UTC, kristojorg commented
> I would name the heading styles h1, h2, h3, etc, and the subtitles with a more descriptive name like bookTitle in the textStyles theme, what do you think?

That seems great to me!

2022-06-06 20:28 UTC, Toxiapo commented on src/marketing/theme/components/link.ts
> +}
Per our discussion, we don't necessary need to create this in the base theme, but rather just create the react comment for them. e.g. <HeaderLink>, <MobileMenuLink>

2022-06-06 20:47 UTC, Toxiapo commented on src/marketing/theme/foundations/shadow.ts
> +  gridBook: "0px 3px 2px rgba(0, 0, 0, 0.3), 0px 1px 3px rgba(0, 0, 0, 0.15)"
Let's keep them now, but we can delete them if it's just for one place. I think we will need a few instances for the carouselBook.

2022-06-07 12:48 UTC, kristojorg commented on src/marketing/theme/foundations/color.ts
> +        primary: magentaPrimaryGradient
Out of curiosity, why are these ones primary and the purple one is secondary?

2022-06-07 12:50 UTC, kristojorg commented on src/marketing/theme/types.ts
> +export declare type Dict<T = any> = Record<string, T>;
I think we already have a Dict type declared somewhere, but could be wrong

2022-06-07 12:50 UTC, kristojorg approved these changes
This looks great!

2022-06-07 14:01 UTC, Toxiapo commented on src/marketing/theme/types.ts
> +export declare type Dict<T = any> = Record<string, T>;
Not in CPW, but we could import it from the webreader.

2022-06-07 14:02 UTC, Toxiapo commented on src/marketing/theme/foundations/color.ts
> +        primary: magentaPrimaryGradient
Oh! I kept the name that was defined in the Figma file.

2022-06-13 10:19 UTC, kristojorg commented on src/marketing/theme/types.ts
> +export declare type Dict<T = any> = Record<string, T>;
Oh then I think I would put this under `interfaces.ts`. The only thing we need to keep separate in the `marketing` folder are the ChakraUI components themselves that can't be mixed with the ThemeUI ones.

2022-06-24 13:50 UTC, Toxiapo commented on src/marketing/components/Header.tsx
> +      window.location.href = new URL("/", window.location.origin).toString();
Unfortunately, I can't re-use the signout function from `auth.ts` because I need to refresh the page after the user pressed the signout button on the homepage.

2022-06-24 14:41 UTC, kristojorg commented on src/marketing/components/Header.tsx
> +      window.location.href = new URL("/", window.location.origin).toString();
Huh, interesting. Why do you need to refresh the page?

2022-06-24 16:38 UTC, Toxiapo commented on src/marketing/components/Header.tsx
> +      window.location.href = new URL("/", window.location.origin).toString();
The signout API does a redirect to the homepage after signing out, but we are on the homepage so it's not performing any page updates. I needed a trigger to toggle the auth button to show Sign in/ Sign out.

2022-06-24 18:01 UTC, samanthaandrews commented on src/marketing/mdx/MDXComponents.tsx
> +      // accommodates the height of the sticky nav when jumping using FAQ table of contents
@kristojorg This `_before` object is to accommodate the height of the sticky nav on the FAQ page. I added a comment for clarity.

2022-06-24 18:13 UTC, samanthaandrews commented on src/marketing/components/Layout.tsx
> +      <SiteHead />
@kristojorg I removed the `<MarketingPage />` component i had created previously and just put the SiteHead here. You're right I don't think it makes sense for it to be a separate component.

2022-07-15 12:08 UTC, merged