OE-553: homepage redesign
NYPL-Simplified/circulation-patron-web pull request #436
Opened 2022-06-17 18:47 UTC by Toxiapo

Assemble homepage components and finish the rest of the homepage design.

Preview: /homepage

2022-06-22 16:43 UTC, samanthaandrews requested changes
super small things i noticed. re-request review once you make updates and I'll approve!

2022-06-22 16:43 UTC, samanthaandrews commented on src/pages/homepage/index.tsx
> +            <br />
Having the `<br />` here matches the mockup but semantically I don't think it makes sense. Can we instead give this text a max width?

2022-06-22 16:43 UTC, samanthaandrews commented on src/pages/homepage/index.tsx
> +        // maxW="1280px"
Stray unused code

2022-06-22 16:43 UTC, samanthaandrews commented on src/pages/homepage/index.tsx
> +        }}
nice!

2022-06-22 18:28 UTC, samanthaandrews commented on src/pages/homepage/index.tsx
> +    description: "Sign In"
In this context, since it's not a button or heading I think this should be "Sign in"

2022-06-22 19:15 UTC, samanthaandrews commented on src/pages/homepage/index.tsx
> +      <Image
I noticed @kristojorg using `next/image` in the grid and carousel components. Should we be using that here? When should we be using one over the other?

2022-06-23 13:44 UTC, kristojorg commented
The mobile phone images look a little blurry to me. Maybe we need to export them in higher quality?

2022-06-23 14:04 UTC, kristojorg commented on src/marketing/theme/foundations/spacing.ts
> +  "-1": 0,
Shouldn't 0 be 0?

2022-06-23 14:05 UTC, kristojorg commented on src/pages/homepage/index.tsx
> +      <Image
I think we should use next/image always from now on basically

2022-06-23 14:13 UTC, Toxiapo commented on src/marketing/theme/components/button.ts
> +        fontWeight: { base: "black", md: "bold" },
Okay! Thank you

2022-06-23 14:43 UTC, kristojorg commented on src/marketing/icon/hand.tsx
> +  props: React.SVGProps<SVGSVGElement> & StyleProps
If you are using what in the component? I guess let me back up and ask what you want to accomplish by adding the `StyleProps` type to this

2022-06-23 14:47 UTC, Toxiapo commented on src/marketing/icon/hand.tsx
> +  props: React.SVGProps<SVGSVGElement> & StyleProps
The message got cut off for some reasons...

`Would this be okay tho if I am using this in the <Icon as={HandIcon} /> component?`

So the goal was to make it so that it accepts all chakra style props.

2022-06-23 15:49 UTC, Toxiapo commented on src/pages/homepage/index.tsx
> +      <Image
AFAIK the `next/image` forces you to either specify the width and the height of the image or use "layout=fill", which essentially still need the width/height in the parent container.

I could just hard code the width and the height of the images, but do you guys know a way to make it so that you don't need to do that and make it render what ever the size of the image?

2022-06-23 16:07 UTC, samanthaandrews commented on src/pages/homepage/index.tsx
> +      <Image
I think you can use `layout="fixed"` which should behave like the native `<img>` element.

2022-06-23 17:52 UTC, Toxiapo commented on src/pages/homepage/index.tsx
> +      <Image
This is what I get: `Error: Image with src "img/apple-screenshot.png" must use "width" and "height" properties or "layout='fill'" property.`

2022-06-23 19:10 UTC, Toxiapo commented on src/pages/homepage/index.tsx
> +      <Image
It's strange to me that we there's no easy way to make this responsive with just the Image component. I will just use the AspectRatio component for now and set the size based on their maximum size like how I did it for the hero image. Thanks, Sam.

2022-06-23 19:35 UTC, samanthaandrews approved these changes

2022-06-23 19:35 UTC, merged

2022-06-24 06:56 UTC, kristojorg commented on src/marketing/icon/hand.tsx
> +  props: React.SVGProps<SVGSVGElement> & StyleProps
You could pass it to `Icon` without the `StyleProps` type set on the props. You could then style the `Icon` normally with style props. If you want to use it as a chakra component itself (`<HandIcon maxWidth={2} />`), then you have to use the chakra factory setup to do that, and you don't need to pass the component the `StyleProps` type