Static page cleanup
NYPL-Simplified/circulation-patron-web pull request #440
Opened 2022-06-23 19:42 UTC by samanthaandrews

- Addresses a few content updates from Miguel
- Merges the new Header & Footer into the MDX pages

2022-06-23 20:09 UTC, Toxiapo requested changes
Just that one style update otherwise this is good to go!

2022-06-23 20:09 UTC, Toxiapo commented on src/marketing/mdx/MDXComponents.tsx
> +      textStyle="h4"
the h4 style is much bigger than h2 here, this is due to the fact that I didn't specify the style for the mobile screens.

2022-06-24 01:04 UTC, samanthaandrews commented on src/marketing/mdx/MDXComponents.tsx
> +      textStyle="h4"
you're right. fixed!

2022-06-24 01:48 UTC, Toxiapo approved these changes

2022-06-24 07:31 UTC, kristojorg approved these changes
A couple questions, but I'm going to merge this and we can discuss on the base theme PR

2022-06-24 07:31 UTC, kristojorg commented on src/marketing/components/MarketingPage.tsx
> +const MarketingPage: React.FC = ({ children }) => {
Why have this as separate from `MarketingPageLayout`?

2022-06-24 07:31 UTC, kristojorg commented on src/marketing/components/MarketingPage.tsx
> +        <UserProvider>{children}</UserProvider>
I'm actually wondering if we should use the `<UserProvider>` here or the `<CredentialsProvider>`. We are only trying to determine the auth state of the user. The user provider has to fetch loans (takes forever) to do that, whereas we could also just assume that if the credentials are defined and set then the user is logged in... if they turn out to be wrong or something then the user will get redirected to login anyway once they try to go to the /app page

2022-06-24 07:31 UTC, kristojorg commented on src/marketing/icon/BackToTop.tsx
> +  <Icon
Oh this is good to know! I hadn't realized we could just use the `Icon` component this way

2022-06-24 07:31 UTC, kristojorg commented on src/marketing/mdx/MDXComponents.tsx
> +      }}
What is this for?

2022-06-24 07:31 UTC, merged