OE-600: Detail page redesign
NYPL-Simplified/circulation-patron-web pull request #494
Opened 2022-10-05 22:32 UTC by Toxiapo

2022-10-12 15:12 UTC, kristojorg commented
I think we need to use `dangerouslySetInnerHTML` for the book description, as it is sometimes HTML content: 
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/4398775/195381064-c2251ea6-d153-467c-8ae9-b51df372fb35.png">

2022-10-12 15:21 UTC, kristojorg commented
I think there could also be a bit more vertical padding added to the recommendations section. It looks like there is a little more in the designs than in the developed version

2022-10-13 17:13 UTC, kristojorg commented
> We are using dangerouslySetInnerHTML for the description. I think this is just a bug we need to fix in the backend. https://jira.nypl.org/browse/OE-115

Hmm interesting. I don't totally understand how the html is getting in there then. That actually doesn't seem like a backend issue but I'm curious what the string looks like

2022-10-13 17:29 UTC, Toxiapo commented
> > We are using dangerouslySetInnerHTML for the description. I think this is just a bug we need to fix in the backend. https://jira.nypl.org/browse/OE-115
> 
> Hmm interesting. I don't totally understand how the html is getting in there then. That actually doesn't seem like a backend issue but I'm curious what the string looks like

These were originally HTML entities from the server(i.e `&nbsp`, `&gt;`), I think we could do a conversion like how [this post](https://stackoverflow.com/a/42182294/17573442) does it before putting it in the `dangerouslySetInnerHTML` prop

2022-10-17 14:45 UTC, kristojorg reviewed
Haven't totally finished, but a few comments so far

2022-10-17 14:45 UTC, kristojorg commented on src/hooks/useHtmlDecode.ts
> +  }, [html]);
Can you send me what the description string looks like for a book that ends up showing html tags in the description?

2022-10-17 15:13 UTC, Toxiapo commented on src/components/chakra-ui/theme/components/button.ts
> +  | "tealNav"
I believe the last one was a merge from the header design, I can double-check.

2022-10-17 15:14 UTC, Toxiapo commented on src/hooks/useHtmlDecode.ts
> +  }, [html]);
Yeah, we get none-HTML characters from the API response. I will find an example.

2022-10-17 15:17 UTC, Toxiapo commented on src/components/chakra-ui/BookDetail/BookCover.tsx
> +import LazyImage from "../LazyImage";
OK yeah, I think that's a good idea. I remember I was having trouble dealing with sizes for the next/image when I was working on the homage., I had to use the aspect ratio property to get them properly show up. I will take a look at the BookCard component!

2022-10-17 15:17 UTC, Toxiapo commented on .github/workflows/integration-cypress.yml
> +    if: ${{ false }} # Disable cypress for now
Good catch, and yes!

2022-10-17 15:34 UTC, Toxiapo commented on src/hooks/useHtmlDecode.ts
> +  }, [html]);
`...won't it remove valid html and give us a basic string`
The txt.value would still give us the valid HTML tag.

2022-10-17 15:49 UTC, samanthaandrews commented on src/components/chakra-ui/theme/components/button.ts
> +  | "tealNav"
There is another button style that Jen added for the sign in / out button in the header nav and it is different than the one we have used for other teal buttons such as the one in the contact form.

2022-10-17 19:30 UTC, kristojorg commented on src/components/chakra-ui/theme/components/button.ts
> +  | "tealNav"
Okay, let's try to ask jen if that was intentional? When I look at the header designs it looks like teal/400 is used for the sign in button. In any case, it's not for this PR but I think we should try to get a single set of colors from Jen if possible

2022-10-17 19:32 UTC, kristojorg commented on src/hooks/useHtmlDecode.ts
> +  }, [html]);
Okay personally I think we should leave this for the backend to do. It feels hacky to have to use state and create textareas to display the right text ya know?

2022-10-18 14:16 UTC, kristojorg commented on src/hooks/useHtmlDecode.ts
> +  }, [html]);
Alright I've reviewed some of what the internet says about this. I think we should do two things:

1. Make a ticket to fix this in the backend or contact the vendor to let them know this is incorrect. I don't know if the source of it is our backend or their content.
2. Use your textarea approach, but without state. You should be able to call this function during the render cycle of the react component rendering the description. We should also extract it to a utility, because we'll need to use it in the BookList as well.

The one downside to this is that if a book _intends_ to have these entities as strings in their descriptions, we will undo that and might get invalid HTML. This should be noted in the server ticket

2022-10-18 18:13 UTC, samanthaandrews requested changes
A few small cleanup things and questions I have. We will have to decide whether we should merge this into the header app nav first or breadcrumbs first. I don't think it matters much either way.

2022-10-18 18:13 UTC, samanthaandrews commented on src/components/chakra-ui/BookStatus.tsx
> +          </svg>
Nit: we could pull this out into an icons file

2022-10-18 22:01 UTC, Toxiapo commented on src/hooks/useHtmlDecode.ts
> +  }, [html]);
[Discussion Thread](https://nypl.slack.com/archives/C0153AFA1RS/p1666120154052629)

2022-10-19 01:39 UTC, Toxiapo commented on src/components/chakra-ui/BreadcrumbBar.tsx
> +export default BreadcrumbBar;
yeah, I agree, hopefully this is easy.

2022-10-19 01:50 UTC, Toxiapo commented on src/components/chakra-ui/Link.tsx
> +        <chakra.a
Good question, I'm not totally sure tbh, the goal here is to make it accept chakra props, so either one works for this use case. I _think_ if you use the `<Link />`, it will pick up the defined styles in the /theme folder defined for the Link component, like the variant, whereas chakra.a uses the default styles from chakra and accepts all the chakra props

2022-10-19 16:49 UTC, samanthaandrews approved these changes

2022-10-20 14:53 UTC, samanthaandrews commented on src/components/chakra-ui/theme/components/button.ts
> +  | "tealNav"
I created this issue and assigned it to myself to clean up this `tealNav` button style https://jira.nypl.org/browse/OE-695

2022-10-20 19:40 UTC, kristojorg reviewed
Sweet! Just a few things

2022-10-20 19:40 UTC, kristojorg commented on src/components/chakra-ui/Link.tsx
> +export const buildLinkFromProps = (props: LinkProps) => {
We should, in general, start to deprecate this since we don't have multiple libraries anymore and we can simplify. Just a note for the future

2022-10-20 19:40 UTC, kristojorg commented on src/components/theme-ui/__tests__/__snapshots__/Button.test.tsx.snap
> +  font-family: Roboto,sans-serif;
Is roboto our font now?

2022-10-20 19:40 UTC, kristojorg commented on src/components/theme-ui/theme/typography.ts
> +    body: "Roboto, sans-serif",
We might need to include it as a webfont in that case?

2022-10-20 19:47 UTC, kristojorg commented on src/components/theme-ui/theme/typography.ts
> +    body: "Roboto, sans-serif",
let's add this link to the _document head with all Roboto styles for now: 
```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
```

2022-10-20 19:59 UTC, Toxiapo commented on src/components/chakra-ui/Link.tsx
> +export const buildLinkFromProps = (props: LinkProps) => {
I will add a TODO to that function.

2022-10-20 20:08 UTC, Toxiapo commented on src/components/chakra-ui/Carousel/index.tsx
> +export const BOOK_HEIGHT = 365;
That's a good question, I pulled this from the BookCover component, but I don't think we are using this anywhere.

2022-10-20 20:09 UTC, Toxiapo commented on src/components/chakra-ui/BookDetail/index.tsx
> +      onClick={handleBackButton}
I should also add a TODO comment here, but I am not sure how ya feel about having these comments around.

2022-10-20 20:14 UTC, kristojorg commented on src/components/chakra-ui/BookDetail/index.tsx
> +      onClick={handleBackButton}
Fine by me

2022-10-20 20:19 UTC, kristojorg approved these changes
Sweet LGTM!

2022-10-20 21:04 UTC, merged