OE-655: Chakra breadcrumbs
NYPL-Simplified/circulation-patron-web pull request #497
Opened 2022-10-13 01:06 UTC by samanthaandrews

- Updates breadcrumbs to use chakra and removes the old theme-ui breadcrumb component
- Renders the breadcrumb bar in the <AppHeader> component
- Minor changes to `computeBreadcrumbs()` to make them slightly more useful for users until the data that we need is returned from the server and we can do a more meaningful update
- Updates and adds unit tests

Note: I spent a lot of time trying to create a working unit test for the `<BookDetails />` page and ran into issues with the child component `<ReportAProblem>` modal needing to be thoroughly mocked. Since `<ReportAProblem />` is currently getting re-designed, I think we should save adding the unit test for <BookDetails /> in that PR. This is the ticket that is next up in my sprint after the Nextjs one.

2022-10-13 16:00 UTC, kristojorg commented
Small issue on mobile where breadcrumbs cover the mobile menu: 
<img width="360" alt="image" src="https://user-images.githubusercontent.com/4398775/195646929-1cdfacf0-ab4d-4226-bdce-66edc19cb0b7.png">

2022-10-13 17:10 UTC, kristojorg requested changes
Looks and works well, just a few small things!

2022-10-13 17:10 UTC, kristojorg commented on src/components/chakra-ui/__tests__/BreadcrumbBar.test.tsx
> +test.only("shows clicklable breadcrumbs", () => {
stray .only

2022-10-13 17:39 UTC, samanthaandrews commented on src/components/chakra-ui/__tests__/AppHeader.test.tsx
> +  const allBooksLink = queryByText(header as HTMLElement, "All books");
For some reason the `getByRole("link", { name: All books})` fails and I can't figure out why RTL isn't recognizing the element as a link. It prints the element in the "ignored nodes" section instead of pulling it out into the accessible elements. I've tried adding awaits and adding `aria-label` to the element explicitly and nothing seems to work. Strangely, in Cypress, the same assertion works using `getByRole()`. Maybe I should make a ticket to investigate, but for now I think this workaround is better than nothing.

2022-10-13 17:39 UTC, samanthaandrews commented on src/components/chakra-ui/BreadcrumbBar.tsx
> +      top="64px"
good idea!

2022-10-13 17:41 UTC, samanthaandrews commented on cypress/tests/browse/breadcrumb-navigation.ts
> +    cy.get("@breadcrumbsList").should("have.lengthOf", 2);
good catch. looks like Chakra adds that aria-role by default i just didn't notice it! updating the cypress test now

2022-10-13 17:47 UTC, samanthaandrews commented on src/components/chakra-ui/BreadcrumbBar.tsx
> +      top="64px"
good idea, i added it to `constants.ts`

2022-10-13 18:09 UTC, samanthaandrews commented on src/components/theme-ui/__tests__/MyBooks.test.tsx
> +});
Agreed. I think knowing that I was going to disable Cypress tests in the next PR made me a little more focused on writing more granular unit tests. But I did go ahead and add a Cypress test to check for breadcrumbs on the loans page 👍

2022-10-13 18:28 UTC, Toxiapo requested changes
Looks great! Just a few comments.

2022-10-13 18:28 UTC, Toxiapo commented on cypress/tests/browse/breadcrumb-navigation.ts
> +    cy.get("[data-testid=breadcrumbs-list]")
Can we use `cy.findByRole("navigation", { name: "breadcrumb" })` instead of assigning it with a testid.

2022-10-13 18:28 UTC, Toxiapo commented on src/components/context/BreadcrumbContext.tsx
>  /** @jsxImportSource theme-ui */
I think we can remove this now.

2022-10-13 18:28 UTC, Toxiapo commented on src/components/theme-ui/MyBooks.tsx
> +  });
Missing dependencies.

2022-10-13 18:28 UTC, Toxiapo commented on src/components/theme-ui/SigninWrapper.tsx
>  /** @jsxImportSource theme-ui */
Should we convert this component to chakra-ui? This is being used on the sign-in page only. But if it's too much work, we can do it in a separate PR

2022-10-13 18:29 UTC, Toxiapo commented on src/components/chakra-ui/__tests__/AppHeader.test.tsx
> +  const allBooksLink = queryByText(header as HTMLElement, "All books");
RTL whyyy : \

2022-10-13 18:49 UTC, samanthaandrews commented on cypress/tests/browse/breadcrumb-navigation.ts
> +    cy.get("[data-testid=breadcrumbs-list]")
Yes, I was able to remove the test-id and use the `aria-role=breadcrumbs` instead!

2022-10-13 18:49 UTC, samanthaandrews commented on src/components/context/BreadcrumbContext.tsx
>  /** @jsxImportSource theme-ui */
good catch

2022-10-13 18:50 UTC, samanthaandrews commented on src/components/theme-ui/MyBooks.tsx
> +  });
why the heck didn't the linter pick this up?!? i've made sure all the deps arrays are there now...

2022-10-13 18:50 UTC, samanthaandrews commented on src/components/theme-ui/SigninWrapper.tsx
>  /** @jsxImportSource theme-ui */
i think this is a good idea and we should make a separate ticket for it!

2022-10-14 03:20 UTC, samanthaandrews commented on src/__tests__/getServerSideProps.test.tsx
> +  jest.spyOn(console, "error").mockImplementation();
Ok I fixed this in a follow-up PR here: https://github.com/NYPL-Simplified/circulation-patron-web/pull/498

2022-10-14 03:23 UTC, samanthaandrews commented on src/components/theme-ui/SigninWrapper.tsx
>  /** @jsxImportSource theme-ui */
Ok I created it here https://jira.nypl.org/browse/OE-684

2022-10-19 19:41 UTC, Toxiapo approved these changes

2022-10-19 19:42 UTC, merged