OE-648: Disable Cypress & Add middleware Jest tests
NYPL-Simplified/circulation-patron-web pull request #504
Opened 2022-10-25 21:50 UTC by samanthaandrews

- Adds more thorough unit testing for middleware
- Ensures credentials returned by `getCredentials` are sent along as a cookie in middleware responses so that updated credentials are always in the browser cookie

2022-10-25 21:55 UTC, samanthaandrews commented on src/middleware.ts
> +  console.log("COLLECTION RESPONSE!!", collectionResponse);
I was attempting to see when we get into this code path and wasn't ever getting collectionResponse.redirected to equal `true`. @kristojorg when you're back I'd like to chat it through to understand if this is a bug in the CM or if I'm misinterpreting what the conditions under which we would get here.

2022-10-27 14:30 UTC, kristojorg requested changes
Looks good to me! Just a stray console log mainly

2022-10-27 14:30 UTC, kristojorg commented on CHANGELOG.md
> +- Refactor: OE-648: upgrade to NextJS 12.3 and mode middleware into a single handler & add middlware unit tests
And disable Cypress I would mention also here

2022-10-27 14:30 UTC, kristojorg commented on src/__tests__/middleware.bookPath.test.tsx
> +    expect(nextResponseSpy).toHaveBeenCalledTimes(1);
Just a note for the future - I think a better way to test this would be to treat it as a pure function. Just given a certain input (request) do we get the output (response) we expect, instead of asserting on what happens inside the function itself. For example, instead of testing whether these were called, we should be able to test that the response url is the same as the input request url

Anyway, just a thought for the future

2022-10-27 14:30 UTC, kristojorg commented on src/middleware.ts
> +    return setAuthCookieServer(NextResponse.next(), credentials);
Interesting, so you had to re-set the credentials even when just calling `next`? Weird that it works that way

2022-10-27 14:30 UTC, kristojorg commented on src/middleware.ts
> +  if (isPathMatch(url, "/app/signin/method*")) {
Good catch

2022-10-27 14:30 UTC, kristojorg commented on src/middleware.ts
> +  console.log("COLLECTION RESPONSE!!", collectionResponse);
This should happen whenever a user requests the root lane directly: `/app/collection/:collectionUrl` where collection url is the all access root lane. 

So if you log in as an early grades user and request this path: `/app/collection/https%3A%2F%2Fqa-circulation.openebooks.us%2FUSOEI%2Fgroups%2F` you should hit this

2022-10-27 14:30 UTC, kristojorg commented on src/middleware.ts
> +  console.log("we are inside removeAuthCookie");
Stray console

2022-10-28 14:07 UTC, Toxiapo commented on src/__tests__/middleware.bookPath.test.tsx
> +    expect(nextResponseSpy).toHaveBeenCalledTimes(1);
@samanthaandrews I have a similar tests here fyi.
https://github.com/NYPL-Simplified/circulation-patron-web/blob/32b2be7d54ab8e29dd118e52554f84baf45b35af/src/__tests__/middleware.test.tsx#L75

2022-10-28 14:36 UTC, samanthaandrews commented on src/middleware.ts
> +    return setAuthCookieServer(NextResponse.next(), credentials);
From writing these test I learned that by default calling NextResponse.next() does not, by default, pass the cookies from the request. In our case, since we are calling `getCredentials()` in our middleware which makes a call to `verifyToken()` and sometimes returns a brand new token in the case the token is about to expire, we need to make sure that that new token is set in the cookie.

In short, when we are on the server and we call `getCredentials()`, we need to send the credentials that are returned as a cookie in the Next response. Otherwise the token that is already set in the browser could be an outdated token that is no longer valid.

2022-10-28 14:54 UTC, samanthaandrews commented on src/middleware.ts
> +  console.log("COLLECTION RESPONSE!!", collectionResponse);
Ok yes I think I've identified a bug (and it may be on the CM side), but when I am logged in as an early grades user, a middle grades user, or a high school user, and I navigate to that path you posted above ⬆️ I am indeed able to see all of the lanes. I am not able to click into each collection to _See more_ content (I hit a 404), but the lanes are visible. This is happening on production, so it is not a result of any of the latest changes made to middleware.

From my testing locally, we are checking that `collectionResonse.redirected` is true, but it is always returning false.

Jen noticed this issue on Thursday, October 20 and posted about it in Slack: https://nypl.slack.com/archives/C0153AFA1RS/p1666284666558289

I created https://jira.nypl.org/browse/OE-720 to investigate the issue. Any context you might have @kristojorg or @Toxiapo please put it in the ticket!

2022-10-31 17:27 UTC, Toxiapo approved these changes

2022-10-31 17:28 UTC, merged