move oew to /apps/oew
NYPL-Simplified/circulation-patron-web pull request #515
Opened 2022-11-09 11:08 UTC by kristojorg

Monorepo!

2022-11-24 10:35 UTC, kristojorg commented
@samanthaandrews can you check why the vercel build is failing for me? Thnx

Otherwise I think this is ready to go finally!

2022-11-28 21:29 UTC, samanthaandrews commented
@kristojorg Vercel is failing with the following error:

```
> Build error occurred
--
08:56:45.579 | Error: > Couldn't find a `pages` directory. Please create one under the project root
08:56:45.579 | at Object.findPagesDir (/vercel/path0/node_modules/next/dist/lib/find-pages-dir.js:86:19)
08:56:45.579 | at /vercel/path0/node_modules/next/dist/build/index.js:102:63
08:56:45.579 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
08:56:45.579 | at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:65:29)
08:56:45.605 | Error: Command "npm run vercel-build" exited with 1

```

2022-11-28 22:26 UTC, kristojorg commented
Yep ok we just need to tell it where to find the app. There should be a setting for the project root and we need to set it to apps/oew

2022-11-29 16:32 UTC, samanthaandrews commented
@kristojorg that makes sense. after the new sign in modal code is merged i'll make that change in Vercel.

2022-11-29 22:53 UTC, samanthaandrews requested changes
Just a few small things that I noticed related to code that was recently merged into `staging` and a couple questions. Once merging the new sign in modal code we should also make sure that gets correctly pulled into this monorepo branch.

2022-11-29 22:53 UTC, samanthaandrews commented on packages/jest-presets/package.json
> +  "version": "0.0.0",
does this need a version number?

2022-11-29 22:53 UTC, samanthaandrews commented on packages/jest-presets/base/jest-preset.js
> +    // "**/__tests__/**/*.[jt]s?(x)",
can we remove this commented out line?

2022-11-29 22:53 UTC, samanthaandrews commented on package.json
> +    "node": ">=16.0.0"
wow this is nice! is this a new entry for package.json files? how does it play with the `.nvmrc` file?

2022-11-29 22:53 UTC, samanthaandrews commented on apps/oew/src/utils/env.ts
> -export const AXISNOW_DECRYPT = process.env.AXISNOW_DECRYPT;
nice

2022-11-29 22:53 UTC, samanthaandrews commented on apps/oew/src/hooks/useComplaints/__tests__/actions.test.ts
> +import * as actions from "hooks/useComplaints/actions";
Everything related to the "Report a Problem" modal was removed in a recent PR: https://github.com/NYPL-Simplified/circulation-patron-web/pull/518

These `useComplaints` hook files must have snuck in here, but we should remove them.

2022-11-29 22:53 UTC, samanthaandrews commented on apps/oew/src/components/theme-ui/Head.tsx
> +import React from "react";
I think this file was moved to the `chakra-ui` directory in a recent PR, so we can probably remove this one if the other one is where it needs to be

2022-11-29 22:53 UTC, samanthaandrews commented on apps/oew/src/components/theme-ui/SigninOption.tsx
> +/** @jsxImportSource theme-ui */
These files were recently converted to `chakra-ui` by @oliviawongnyc so we just need to make sure her changes are here in the new monorepo and these ones can be removed

2022-11-29 22:53 UTC, samanthaandrews commented on apps/oew/cypress/tests/report-problem.ts
> +import {
This can also be removed

2022-11-29 22:53 UTC, samanthaandrews commented on apps/oew/cypress/fixtures/problemDoc.ts
> +const problemDoc = `http://librarysimplified.org/terms/problem/cannot-issue-loan
can remove this too

2022-11-29 22:53 UTC, samanthaandrews commented on apps/oew/next.config.mjs
> + */
Do we need to create a ticket to take action on these notes?

2022-11-29 22:53 UTC, samanthaandrews commented on apps/oew/src/components/chakra-ui/MarketingLayoutPage.tsx
> +import React from "react";
not sure why this file shows up as a new file instead of just being renamed but it looks ok!

2022-11-29 22:53 UTC, samanthaandrews commented on .github/workflows/release-prod.yml
> +          root: "./apps/oew"
do we need to add this to the `release-qa.yml` file too?

2022-12-01 16:27 UTC, kristojorg commented on .github/workflows/release-prod.yml
> +          root: "./apps/oew"
I don't think we use this step in release-qa since we don't tag a git version for QA

2022-12-01 16:29 UTC, kristojorg commented on apps/oew/next.config.mjs
> + */
Nope, my mistake, it was resolved

2022-12-01 16:38 UTC, kristojorg commented
Ok @samanthaandrews I think I addressed your comments, thanks for the detailed review!

2022-12-01 19:27 UTC, samanthaandrews commented on src/components/chakra-ui/__tests__/AuthButton.test.tsx
> -import { fixtures, render, waitFor, within } from "test-utils";
I think this file was accidentally deleted when it should be moved to `oew`

2022-12-01 19:33 UTC, samanthaandrews commented on apps/oew/CHANGELOG.md
> +- Breaking Change: OE-739: Make Axisnow decryptor a required package. Install will fail without access.
nit: move these up to "unreleased" section

2022-12-01 19:34 UTC, samanthaandrews approved these changes
Just those small things I noticed from the rebasing/merging but otherwise this looks great. This was a ton of work and I'm excited for our new monorepo endeavors!

2022-12-01 20:06 UTC, samanthaandrews commented
Vercel is building now, but failing with the following error:

```
Failed to compile.
-- 
./src/test-utils/index.tsx:9:34
Type error: Cannot find module 'jest-fetch-mock' or its corresponding type declarations.

```
Might just need to run npm install on `oew` again?

2022-12-02 09:03 UTC, kristojorg commented on src/components/chakra-ui/__tests__/AuthButton.test.tsx
> -import { fixtures, render, waitFor, within } from "test-utils";
Oh shoot thanks. Git told me it had been deleted downstream I thought, but looks like you're right!

2022-12-02 11:08 UTC, merged