OE-684: convert signin to chakra
NYPL-Simplified/circulation-patron-web pull request #520
Opened 2022-11-14 15:42 UTC by oliviawongnyc

This PR resolves Jira ticket [OE-684](https://jira.nypl.org/browse/OE-684), converting SigninOption and its descendants from theme-ui to chakra-ui components.

2022-11-14 19:25 UTC, samanthaandrews requested changes

2022-11-14 19:25 UTC, samanthaandrews commented on src/components/chakra-ui/theme/components/button.ts
> +    shadow: shadowVariant
I think we should rename this to something like "signInPicker" because it is very specific to the sign in selector component and likely won't be used elsewhere in the app. Other buttons in the app do have shadow which is why I think this might get confusing.

2022-11-14 19:25 UTC, samanthaandrews commented on src/components/chakra-ui/theme/components/heading.ts
> +  variants: {
Historically we have used the `text.ts` file to define our heading styles. For consistency I think we should continue to use the styles defined there. This means headings will be implemented like this instead of using the Chakra Heading component:

```
<Text textStyle="h1" as="h2">
    Heading text
</Text>
```
I am wondering if it would make sense to convert to using the chakra `<Heading />` component in a future ticket though? I'm not sure which is better tbh. @Toxiapo may have thoughts.

2022-11-14 19:25 UTC, samanthaandrews commented on src/components/chakra-ui/theme/components/link.ts
> +    navLink: navLinkVariant
maybe I'm missing it but I couldn't figure out where this is being used?

2022-11-14 20:51 UTC, oliviawongnyc commented on src/components/chakra-ui/theme/components/heading.ts
> +  variants: {
Okay, I updated. I am overriding the fontWeight and fontSize, however, based on the styles that are currently live.

2022-11-14 21:05 UTC, Toxiapo commented on src/components/chakra-ui/theme/components/heading.ts
> +  variants: {
Yeah, I would suggest using `text` if possible. It makes sense that we have to override some of the styles in there since this page was done before the design unification, so the base themes is a little different.

2022-11-14 21:11 UTC, Toxiapo commented on src/pages/app/signin/method/clever/callback.tsx
>  /** @jsxImportSource theme-ui */
We should be able to remove this now.

2022-11-14 21:20 UTC, Toxiapo commented on src/components/chakra-ui/SigninOption.tsx
> +const logoHeader = {
For CSS-related objects, we can use `SystemStyleObject` as the type, but we don't need to add it here, just an FYI.

2022-11-14 21:27 UTC, oliviawongnyc commented on src/components/chakra-ui/SigninOption.tsx
> +const logoHeader = {
Thank you!

2022-11-14 21:28 UTC, oliviawongnyc commented on src/components/chakra-ui/SigninOption.tsx
> +const logoHeader = {
I went ahead an added. Unless there's a reason why we wouldn't add here.

2022-11-14 22:23 UTC, Toxiapo commented on src/components/chakra-ui/SigninOption.tsx
> +const logoHeader = {
Yes it is good to add it!

2022-11-14 22:47 UTC, Toxiapo approved these changes
Looks good to me!

After @samanthaandrews approves this, can you pass this along with #519's bug to Ayan to QA?

2022-11-15 15:29 UTC, kristojorg commented on src/components/chakra-ui/theme/components/button.ts
> +    shadow: shadowVariant
IMO if a variant is only used in one place, it doesn't need to live in the theme. Maybe we can simply inline these styles into a button?

2022-11-15 18:31 UTC, samanthaandrews reviewed
Just one small thing! Looks great.

2022-11-15 18:31 UTC, samanthaandrews commented on src/components/chakra-ui/SigninOption.tsx
> +                color: "ui.blue.clever"
chakra has a convenience prop that we might be able to use here and in the First Book button `_hover={{ color: "ui.blue.clever" }}`

2022-11-15 19:53 UTC, oliviawongnyc commented on src/components/chakra-ui/SigninOption.tsx
> +                color: "ui.blue.clever"
I tried this, but it doesn't work. Not sure why!

2022-11-15 19:53 UTC, oliviawongnyc commented on src/components/chakra-ui/theme/components/button.ts
> +    shadow: shadowVariant
Sounds good!

2022-11-15 20:10 UTC, samanthaandrews approved these changes
🚀

2022-11-15 20:21 UTC, merged

2022-11-16 10:25 UTC, kristojorg commented on src/components/chakra-ui/theme/components/heading.ts
> +  variants: {
I think we didn't use the `Heading` component from Chakra initially because it was a bit confusing what it even did (as in how it was different from Text), so we just opted for Text