OE-666: New sign out modal
NYPL-Simplified/circulation-patron-web pull request #528
Opened 2022-11-22 21:09 UTC by samanthaandrews

This PR builds the new sign out modal using Chakra and removes the old theme-ui one

Pending visual QA by @jotten

2022-11-23 14:52 UTC, Toxiapo requested changes
This looks great!

I just have one question regarding accessibility. When I open the Sign Out popup with my keyboard, the focus was on the "x" text, should it be on the "Sign Out" button?

2022-11-23 14:52 UTC, Toxiapo commented on src/components/chakra-ui/header/Header.tsx
> +      zIndex="sticky"
I think this value should be higher than what's on the hamburger dropdown, which is `modal`, so then when the dropdown opens, it opens from the background instead of the header foreground

2022-11-23 14:52 UTC, Toxiapo commented on src/components/chakra-ui/theme/components/button.ts
> +    backgroundColor: "none",
Do we need this if it's just one style?

2022-11-23 14:52 UTC, Toxiapo commented on src/components/chakra-ui/theme/foundations/color.ts
> +    red: "#ED1C24",
I wonder if we should rename these brand colors to "ui.firstbook.red / ui.firstbook.blue / ui.clever.blue / ui.clever.black"? I am not sure how many reds will Jen use so this is just a thought.

2022-11-23 14:52 UTC, Toxiapo commented on src/utils/auth.ts
>  }
has the Clever signout bug been fixed with next13?

2022-11-24 12:03 UTC, kristojorg commented on src/components/chakra-ui/theme/components/button.ts
> +    backgroundColor: "none",
I think this depends on whether the designs will have ghost buttons from now own. I'd love to get a set of all the button variants, sizes and colors from jen so we can just put them in our theme and not need to wonder what should be a variant vs a one-off

2022-11-24 13:16 UTC, kristojorg commented on src/utils/auth.ts
>  }
In general for internal navigation I think we should use `next/router`

2022-11-24 13:24 UTC, kristojorg commented on src/components/theme-ui/AppLayout.tsx
> +        <SkipNavLink zIndex="skipLink">Skip to content</SkipNavLink>
I don't know that it's related, but I never see this appear anymore

2022-11-24 13:40 UTC, kristojorg commented on src/utils/auth.ts
>  }
But I do remember this being a tricky problem. Maybe things have progressed and there is a better way to sign people out than requesting a url and waiting for it to resolve?


Also, if we continue doing it this way we should consider adding a progress indicator to the spinner. It takes some time before the request to /signout resolves and looks like nothing is happening. We could move this code from `utils/auth` directly into the SignOut button because I don't think it is used anywhere else

2022-11-28 19:44 UTC, samanthaandrews commented on src/components/chakra-ui/theme/foundations/color.ts
> +    red: "#ED1C24",
I also wonder. This first book red wasn't actually being used anywhere except the first book logo SVG, and in that case it is not passed through from the theme anyway. I noticed Jen used the same color for this modal "Sign out" action though, so I figured it made more sense to just name it "red" instead of mentioning First Book at all.

2022-11-28 19:46 UTC, samanthaandrews commented on src/components/theme-ui/AppLayout.tsx
> +        <SkipNavLink zIndex="skipLink">Skip to content</SkipNavLink>
It's there! Navigate to the site and hit "tab" and it should pop up. Lmk if you don't see it though bc that is a bug that we should fix.
<img width="888" alt="Screen Shot 2022-11-28 at 2 45 33 PM" src="https://user-images.githubusercontent.com/34348332/204367121-ffc72d3c-36fc-42d2-8d60-1e5abc9a3417.png">

2022-11-28 19:59 UTC, samanthaandrews commented on src/components/chakra-ui/theme/components/button.ts
> +    backgroundColor: "none",
I'm going to bring this up to Jen and ask her to create these components when she has some down time. For now, I removed this from the variants list and just used an inline style for these modal buttons.

2022-11-28 19:59 UTC, samanthaandrews commented on src/components/chakra-ui/theme/foundations/color.ts
> +    red: "#ED1C24",
I did change the First Book and Clever names to match your suggestion, @Toxiapo 👍

2022-11-28 20:02 UTC, samanthaandrews commented on src/components/chakra-ui/header/MenuNav.tsx
> +        <DrawerOverlay zIndex="dropdown"/>
@Toxiapo i updated the drawer overlay to use "dropdown" so that all of these layers display correctly

2022-11-28 20:03 UTC, samanthaandrews commented on src/components/chakra-ui/header/Header.tsx
> +      zIndex="sticky"
You are correct, but I edited how the hamburger dropdown displays, so now it has a `zIndex="dropdown"`. I tagged you in the spot where I made that change.

2022-11-28 20:24 UTC, samanthaandrews commented on src/components/chakra-ui/AuthButton.tsx
> +  });
@kristojorg what do you think about this? instead of using the `/api/auth/signout` path, I just remove the cookie and then push users back to the homepage using the router. Then there's also no need for a loading spinner.

2022-11-28 20:26 UTC, samanthaandrews commented on src/utils/auth.ts
>  }
I updated this to not use an API call at all and just remove the cookie. Lmk what you think.

2022-11-29 20:15 UTC, samanthaandrews commented on src/components/chakra-ui/theme/foundations/color.ts
> +    danger: "#EC445A",
I spoke with @jotten and agreed we should replace any red/error color with one value, so that's what you see here. It's now called "danger".

2022-11-30 13:41 UTC, kristojorg commented on src/components/theme-ui/AppLayout.tsx
> +        <SkipNavLink zIndex="skipLink">Skip to content</SkipNavLink>
Huh, strange. It doesn't show up on safari, but now that I checked with chrome I do see it

2022-11-30 13:49 UTC, kristojorg commented on src/components/chakra-ui/AuthButton.tsx
> +  });
Ok tested and it works on safari and chrome at least. Should be fine. Wish I had a decision log so I could look back at why I originally converted from Cookie.remove to the api/auth/signout option

2022-11-30 13:54 UTC, kristojorg approved these changes
Looks good!

2022-11-30 13:54 UTC, merged