[WIP] Loads an encrypted ebook
NYPL-Simplified/circulation-patron-web pull request #93
Opened 2020-07-10 20:19 UTC by hokei

wipwip

2020-07-10 20:41 UTC, hokei commented on localhost-key.pem
> +-----BEGIN PRIVATE KEY-----
These are needed to run cpw in https in localhost.

2020-07-10 20:58 UTC, leonardr commented on src/pages/[library]/read/[bookUrl].tsx
> +  const bookManifestUrl = `https://node.axisnow.com/content/stream/9781599904993/META-INF/container.xml`;
By the time you merge this, this URL should be derived from bookUrl (maybe you even use bookUrl as is). Starting with container.xml rather than package.opf is the right move.

2020-07-10 20:59 UTC, leonardr commented
This is definitely the right approach.

2020-07-10 21:09 UTC, hokei commented on src/pages/[library]/read/[bookUrl].tsx
> +  const bookManifestUrl = `https://node.axisnow.com/content/stream/9781599904993/META-INF/container.xml`;
Is it ok to call 
baseUrl/library/reader?url=https://node.axisnow.com/content/stream/9781599904993/META-INF/container.xml or similar?  (@M0nica would it look like this or is there a fun next thing we can do to make it read)

2020-07-10 21:16 UTC, leonardr commented on src/pages/[library]/read/[bookUrl].tsx
> +  const bookManifestUrl = `https://node.axisnow.com/content/stream/9781599904993/META-INF/container.xml`;
Yeah, AxisNow does almost exactly that so it should be fine.

2020-07-11 16:02 UTC, kristojorg commented on .env
> +CONFIG_FILE=config/config.txt
Just an FYI you can define an `.env.local` which will override the `.env` file and will be ignored by git. I set up the `.env` file initially to just be examples. We shouldn't change the `.env` file that is in github

2020-07-11 16:02 UTC, kristojorg commented on .env
> +CONFIG_FILE=config/config.txt
Maybe I should make this more clear in the README

2020-07-13 13:09 UTC, hokei commented on .env
> +CONFIG_FILE=config/config.txt
aaaah it's there, I just missed it orzorz

2020-07-13 16:47 UTC, M0nica commented on package.json
> +    "dev": "CONFIG_FILE=config.txt node server.js",
Should there be two `dev` scrips configured? one for `next dev` nd one for `node server.js`?

2020-07-13 17:15 UTC, hokei commented on package.json
> +    "dev": "CONFIG_FILE=config.txt node server.js",
With this change it doesn't really make sense to run in dev without https so it does need to call  
https://nextjs.org/docs/advanced-features/custom-server

I can't figure out the exact command that `next dev` is running but my guess is that it was calling the default `server.js` so it's not necessary now

2020-07-13 17:15 UTC, kristojorg commented on package.json
> +    "dev": "CONFIG_FILE=config.txt node server.js",
If this gets merged I'd like to try and find a way to do it without the custom server, and also we definitely shouldn't set the config file env var here. But yes, `node server.js` takes the place of `next dev` in this case

2020-07-13 19:17 UTC, hokei commented on package.json
> +    "dev": "CONFIG_FILE=config.txt node server.js",
I think (something like) this is going to be merged eventually.  I guess the hope is that it can be run in http if the `AXIS_NOW_DECRYPT=false` but is there a way to make it run https without a custom server?

Yeah the config.txt doesn't need to be here...

2020-07-14 10:56 UTC, kristojorg commented on package.json
> +    "dev": "CONFIG_FILE=config.txt node server.js",
You're referring specifically to localhost right, because HTTPS should work in production by default. If it's only development we need this for, then I think it's totally fine. Let's just add a comment to the top of the file and maybe rename it `dev-server.ts` so that it's clear it isn't the production server?

2020-07-30 14:04 UTC, M0nica commented on src/utils/reader.ts
> +  //TODO: Check that the book is of type application/vnd.librarysimplified.axisnow+json
The type for the encrypted epub from @leonardr's test server is actually `"application/vnd.librarysimplified.web-epub;profile=axis-encryption"` instead of "application/vnd.librarysimplified.axisnow+json". If this is the format of actual encrypted docs then `FullfillmentCard.tsx` anf the types in `opds-web-client` will need to be updated to support loading this type in the online viewer.

2020-07-30 14:46 UTC, leonardr commented on src/utils/reader.ts
> +  //TODO: Check that the book is of type application/vnd.librarysimplified.axisnow+json
The format you'll be seeing on real (non-test) servers is always `application/vnd.librarysimplified.axisnow+json`.

2020-08-19 20:25 UTC, hokei commented
This isn't going to be able to be built until https://github.com/NYPL-Simplified/axisnow-access-control-web/pull/1 is merged.  (I also still haven't completely figured out the github actions piece, but will do it after the above PR is merged.)

2020-08-19 20:26 UTC, hokei commented
It would be super useful to have some help running this app with everyone's different configurations to make sure it still works.  (And also ideas on how to test that this works with all the different configurations)

2020-08-19 20:35 UTC, hokei commented on .github/workflows/ci.yml
> +      - name: clone submodule
this hasn't been tested.

2020-08-19 20:36 UTC, M0nica commented on package.json
> +    "library-simplified-webpub-viewer": "git://github.com/NYPL-Simplified/webpub-viewer#accessControl",
Reminder to update this once https://github.com/NYPL-Simplified/webpub-viewer/pull/164 is merged.

2020-08-20 17:02 UTC, M0nica commented on src/components/BookList.tsx
> +      let label: string;
Can this be rewritten a conditional without `let`?

2020-08-20 17:06 UTC, M0nica commented on src/components/BookList.tsx
> +          {getButtons("Borrow")}
Can "Borrow" but put into a constant since this `BorrowButtonType` is referenced in multiple places? To avoid issues if it is later renamed / reduce typos.

2020-08-20 17:09 UTC, M0nica commented on src/components/BookList.tsx
> +          {getButtons("Reserve")}
Can "Reserve" also be converted to a constant?

Maybe `const BUTTONTYPES = {RESERVE: "Reserve", BORROW: "Borrow}`

2020-08-20 17:12 UTC, M0nica commented on src/components/WebpubViewer.tsx
> +  const bookManifestUrl = `${bookUrl}`;
At some point are we going to rename manifestUrl in `circulation-patron-web` and `webpub-viewer` since the url now is a generic startUrl where the actual manifest url is extracted by webpub-viewer's internal logic?

2020-08-20 17:14 UTC, M0nica commented on src/components/__tests__/BookListItem.test.tsx
> +    // Both buttons have the "Borrowing..." text and are disabled
I think this behavior should potentially be revisited (in future work) as I think as a user if there are two buttons and I click one button, that only one would changed to loading/borrowing even if both are disabled.

2020-08-20 17:14 UTC, M0nica commented on src/components/__tests__/MyBooks.test.tsx
>    expect(bookNames[1]).toHaveTextContent("Book Title 10");
Why was` expect(bookNames[2]).toHaveTextContent("Book Title 0");` removed from the tests?

2020-08-20 17:20 UTC, M0nica commented on src/components/bookDetails/FulfillmentCard.tsx
> +                link.type === "application/vnd.librarysimplified.axisnow+json"
Should the AXIS_NOW environment variable also be a condition for the `ReadOnlineButton` to render for axisnow resources?

2020-08-24 12:51 UTC, kristojorg commented
In terms of testing how this works with all the different configs -- that's a general problem that we ideally want to address at some point, though I'm not sure how. We need to have a clearer idea of what the server config guarantees are so we can set up some automated testing for all of the various configs. Or alternatively we could lean on something more manual and have a single default config file that has a list of demo CMs with various configs and we can have a version of CPW published with that config file for every PR, which would allow us to at least manually test.

2020-08-24 14:31 UTC, kristojorg requested changes
okay this looks great! I made a few comments but otherwise looks good to me

2020-08-24 14:31 UTC, kristojorg commented on src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
> +  test("shows loading state on both buttons when borrowing", async () => {
one question that this brings up for me... what happens if a user has a book borrowed with two borrow links at the same time? do we know what this looks like in terms of response from the CM and in the UI?

2020-08-24 14:31 UTC, kristojorg commented on src/utils/__tests__/reader.test.ts
> +// });
should this be included or uncommented?

2020-08-24 14:31 UTC, kristojorg commented on src/utils/book.tsx
> +export type BorrowButtonType = "Borrow" | "Reserve";
I think in my suggested refactor we wouldn't need this type, but if we still need it i think it should be moved to `interfaces`

2020-08-24 14:31 UTC, kristojorg commented on src/utils/reader.ts
> +  decryptorParams?: any
does this need to be `any`? i don't fully understand how this works but what is the `initBookSettings` expecting?

2020-08-24 14:31 UTC, kristojorg commented on src/utils/reader.ts
> +  }
I don't think you need the wrapping `if (Decryptor)` statement here, so the `decryptor` can be a `const`.

2020-08-24 14:34 UTC, hokei commented on .env
> +# AXIS_NOW_DECRYPT=true
Gecause the Decryptor is private, there's no guarantee that every person who wants to use CPW has access to Decryptor.  As a good OSS project, we want to make sure that CPW still works if you want to use it with a circulation manager on an unencrypted feed and don't have access to Decryptor.

2020-08-24 14:36 UTC, hokei commented on src/utils/__tests__/reader.test.ts
> +// });
Yeah I still need to write these tests, 😬

2020-08-24 14:56 UTC, M0nica commented on src/components/WebpubViewer.tsx
> +  const bookManifestUrl = `${bookUrl}`;
Oh yeah now that the `bookManifestUrl` is the same value as `bookUrl` it probably makes more sense to pass it directly.

2020-08-24 15:04 UTC, M0nica commented
> The label "Borrow to read on a mobile device" seems very long for a button. I can't run this right now because I'm on a loaner computer, so I don't know how it looks, but maybe that would be better as a label above the button? 

@kristojorg for reference the last time I ran this branch the buttons on the book details page looked like this:

<img width="993" alt="Screen Shot 2020-08-24 at 11 03 12 AM" src="https://user-images.githubusercontent.com/6998954/91060931-905f3f00-e5f9-11ea-8020-d26f4d929060.png">

2020-08-24 15:07 UTC, M0nica commented on src/components/WebpubViewer.tsx
>      if (typeof window !== "undefined") {
+1 ...useEffect runs initially after the first render so the window check can be removed.

2020-08-24 15:44 UTC, M0nica commented on src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
> +    expect(_useBorrowSpy).toHaveBeenCalledTimes(2);
In the UI it also looked to me like it was trying to borrow once for each version (atleast on the book search page)

2020-08-24 15:49 UTC, hokei commented on src/components/BookList.tsx
> +      let label: string;
This is how it looks:  

![Screen Shot 2020-08-24 at 11 48 34 AM](https://user-images.githubusercontent.com/3579472/91066468-c3a4cc80-e5ff-11ea-9fc0-3a2d3854b22f.png)

![Screen Shot 2020-08-24 at 11 49 10 AM](https://user-images.githubusercontent.com/3579472/91066553-d7503300-e5ff-11ea-9fd4-e605c8116469.png)


I'll take a look again at this logic, it's currently pretty confusing. 

>     5. By "Read on a mobile device" do you mean "Read with SimplyE/OpenEbooks"? I think we should be specific about that since on a mobile device is ambiguous.

So that's not exactly what's happening.  Books can either be served in `application/vnd.librarysimplified.axisnow+json` or other formats such as Adobe ACM, etc.  
If you borrow a book in a format, you must also read it in that format.  Before, when only one borrow and read link was ever shown, this wasn't a problem.  Now, though, we want to give people the choice of formats.  

However, showing them "Borrow `application/vnd.librarysimplified.axisnow+json` format" is clearly not useful.  "Read Online/Read on Mobile" seems to be the most useful distinction because that's what people care about?  SimplyE/Open Ebooks probably won't work here because the entire product is Open Ebooks, right?  

Talking through this, I'm also realizing that if a book has more than one mobile link it'll show up twice ... gah, I need to put in logic to handle that.  I might separate that out into a separate ticket depending on how this refactor work goes ...

2020-08-24 16:19 UTC, hokei commented on src/components/bookDetails/FulfillmentCard.tsx
> +                link.type === "application/vnd.librarysimplified.axisnow+json"
I asked Risa about this -- SimplyE will want to be able to access encryption/decryptions options eventually, but not for like another year (re: current plans)  

Personally, I think of the AXIS_NOW env variable as a "Do I have access to the axis-now-access-control-web repo" 
Is there a better way to represent this?

2020-08-24 19:43 UTC, hokei commented on .gitignore
> +config.txt
aaah I completely missed that.  I'll put my config into /config

2020-08-24 19:43 UTC, hokei commented on .gitignore
> +lib/
This was coming from something I was trying earlier, I need to remove it.

2020-08-25 15:13 UTC, hokei commented
Note, currently, loading an ebook for the first time is incredibly slow.  Like, walk away and eat a snack slow.  It also will show you "there is an error loading this page"  while it is loading.  In this PR I want to replace that error page with a loading page, but speeding up ebook loading is going to happen in a different ticket

2020-08-26 12:08 UTC, kristojorg commented on src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
> +  test("shows loading state on both buttons when borrowing", async () => {
Okay well at least it will give an appropriate error

2020-08-26 12:10 UTC, kristojorg commented
@M0nica thanks! I think the ui there should be updated rethought, what do you all think? It seems like too much for the purpose of that card. Maybe we put the options into a modal and just leave a single "Borrow" button on the card? We could reuse that UI for the book details page then. Thoughts?

2020-08-26 14:35 UTC, hokei commented
@kristojorg I think that would be great!  I also think, let's get this ticket to a "this is a reasonable thing to use" state and separate that out into a separate ticket as this ticket is ostensibly a "load encryption" ticket and I'm pretty excited to get this to a state where people who aren't us can see that encrypted ebook reading works

2020-08-26 19:40 UTC, hokei commented on .gitignore
> +config.txt
So when I put it into `/config/config.txt` something in the code is still looking for `config.txt` in the main file.  What am I doing wrong?
![Screen Shot 2020-08-26 at 3 40 14 PM](https://user-images.githubusercontent.com/3579472/91348919-80d72600-e7b2-11ea-90d3-005680aaff46.png)

2020-08-26 21:03 UTC, hokei commented on src/utils/reader.ts
> +  decryptorParams?: any
Currently it might need to be, but theoretically, decryptor implementation details shouldn't be exposed in this public repo, so `any` is a way to hide that.

2020-08-26 21:06 UTC, hokei commented on src/utils/__tests__/reader.test.ts
> +// });
How would y'all feel if I moved this and the webpubviewer.test.tsx to a different ticket to try and unblock work?

2020-08-26 21:08 UTC, hokei commented
![Screen Shot 2020-08-26 at 5 07 30 PM](https://user-images.githubusercontent.com/3579472/91357064-a702c300-e7be-11ea-9157-205c31df7882.png)

Since the two pages are now sharing the same button, this is what the book list page looks like 

And 

![Screen Shot 2020-08-26 at 5 08 03 PM](https://user-images.githubusercontent.com/3579472/91357115-b97cfc80-e7be-11ea-89e7-53cc8321195c.png)

The book detail page

2020-08-27 14:08 UTC, kristojorg commented
@hokei I understand wanting to keep this from bloating too much. Is it possible instead of the full blown modal solution to just add space between the buttons so they're visually separated? You can use a `Stack` component to do that easily.

2020-08-27 14:24 UTC, hokei commented
@kristojorg Oh  yes I can definitely do that!

2020-08-27 14:37 UTC, kristojorg requested changes
Okay just a couple more things and then I think this is ready : )

2020-08-27 14:37 UTC, kristojorg commented on .config/config.txt
> +brazoria|https://simplye.amigos.org/txbrazoria
This should be in `/config` instead of `/.config`, and then it will be gitignored

2020-08-27 14:37 UTC, kristojorg commented on config.txt
> +brazoria|https://simplye.amigos.org/txbrazoria
This file should be removed

2020-08-27 14:37 UTC, kristojorg commented on src/dataflow/getLibraryData.ts
> +    console.log("CONFIG_FILE", CONFIG_FILE);
Sorry if my previous comment wasn't clear... I think all these console logs should be left as they were personally.

2020-08-27 14:37 UTC, kristojorg commented on src/utils/book.tsx
> +  FulfillmentLink
Check the lint warnings in this file

2020-08-27 14:37 UTC, kristojorg commented on src/utils/reader.ts
> +  decryptorParams?: any
Okay, we can leave it if it needs to be

2020-08-27 14:37 UTC, kristojorg commented on src/components/WebpubViewer.tsx
> +  let decryptorParams = undefined;
Still think it would be more readable with an early return

2020-08-27 14:37 UTC, kristojorg commented on src/components/WebpubViewer.tsx
>      if (typeof window !== "undefined") {
Should remove this window check

2020-08-27 14:37 UTC, kristojorg commented on src/components/bookDetails/FulfillmentCard.tsx
> +import { jsx, Link } from "theme-ui";
We don't use this `Link` component

2020-08-27 14:37 UTC, kristojorg commented on src/components/bookDetails/FulfillmentCard.tsx
> +  const { errorMsg } = useBorrow();
I think each button should render the error message separately (this goes with their separate `useBorrow` instances

2020-08-27 22:07 UTC, hokei commented on src/components/__tests__/BookListItem.test.tsx
> +    ).toBeInTheDocument();
this (and L209) happened because of the moving the error checking to be per-button, which means it's no longer possible to check for the error outside the button.  FulfillmentCard doesn't check for errors before showing the availability string or borrow status, so, I think, actually represents more consistent behavior.

2020-08-27 22:21 UTC, M0nica commented on src/utils/__tests__/reader.test.ts
> +// });
I think I'd be okay with that assuming the test tickets will get picked up in this sprint?

2020-08-27 22:23 UTC, M0nica commented on src/components/__tests__/BookListItem.test.tsx
> +    ).toBeInTheDocument();
If this test is passing it looks like it shows both the availability and the error message in cases where there is an error? If so, I think this is fine unless we end up making UX changes in the future.

2020-08-27 22:24 UTC, M0nica commented on src/components/__tests__/BookListItem.test.tsx
>        utils.queryByText("You can now borrow this book!")
This seems wonky to me that when the response is a 403 error it is able to find the text "You can now borrow this book!". I think that it should _not_ appear and it seems to be a breaking change if it does.

2020-08-27 22:26 UTC, M0nica commented on src/dataflow/getLibraryData.ts
> -    console.log("Running with Library Registry at: ", REGISTRY_BASE);
I think these `console.logs` would be helpful to retain.

2020-08-27 22:29 UTC, kristojorg commented on src/components/__tests__/BookListItem.test.tsx
>        utils.queryByText("You can now borrow this book!")
I think it's somewhat normal actually. Consider a "Submit" button on a form. If the form gives you an error, it'll display the error but still allow you to click submit again, which will again show you the error. So I think it's okay that you can still try and borrow the book after an error occurred, so long as the error message is also displayed. But idk, both perspectives seem valid to be

2020-08-27 22:31 UTC, kristojorg commented on src/components/__tests__/BookListItem.test.tsx
> +    ).toBeInTheDocument();
This seems okay with me. One thing I wonder is that with multiple borrow buttons wouldn't there actually be _multiple availabilities_? 🤯  I don't know if that's the case or not, but if so then we should open a ticket to fix that once the data fetching is refactored and the internal data model more closely represents the actual OPDS Feed

2020-08-27 23:44 UTC, hokei commented
@kristojorg I am having an issue with the `useBorrow` error message logic.  It seems like, `state.book.error` isn't specific to any loan, but to all loans.  This means that, when you have an error for one book, it shows underneath all books.  This is what it looks like on the `beta` branch 
![Screen Shot 2020-08-27 at 7 41 27 PM](https://user-images.githubusercontent.com/3579472/91505359-629a2480-e89d-11ea-8dee-b7c1e4d5ceda.png)

Is there a ticket already for this?  Since it's in the beta branch, should I try address it here?  

I think @M0nica 's outstanding question can't really be addressed until this is addressed because I think this means that there currently isn't a way to query "is there a problem with this exact book loan"?

2020-08-27 23:44 UTC, hokei commented on src/dataflow/getLibraryData.ts
> -    console.log("Running with Library Registry at: ", REGISTRY_BASE);
aaaaaaaahhh I went overly delete-happy again.  I'm sorry.

2020-08-27 23:47 UTC, hokei commented on src/components/__tests__/BookListItem.test.tsx
> +    ).toBeInTheDocument();
I think this UI needs a real good re-think.  There isn't multiple availabilities (because if you borrow a book to read online, you can't borrow the same book to read on your device.  Is this intended?  I don't know?)  But, I think a better UI would be one where you first select the format you want and then get presented with a borrow button, so you never see more than one borrow button on the same book.

2020-08-28 10:23 UTC, kristojorg commented
Yea I think we should make a ticket for this. It's a symptom of how redux is used in opds-web-client. I'm currently working on further updates that will separate CPW from opds-web-client completely and remove redux, so this should no longer happen once my updates are finished. Let's just leave it

2020-08-28 10:24 UTC, kristojorg commented on src/components/__tests__/BookListItem.test.tsx
> +    ).toBeInTheDocument();
Yea that makes sense, but also the single borrow button we used before led to multiple formats available for download. So yea I think we need to make a separate ticket for this

2020-08-28 13:29 UTC, hokei commented
> led to multiple formats available for download. So yea I think we need to make a separate ticket for this

Oh no I guess we're gonna need to look into the response logic 

I filed 
https://jira.nypl.org/browse/SIMPLY-3021 and https://jira.nypl.org/browse/SIMPLY-3020 for the other issues

2020-08-28 14:28 UTC, kristojorg commented
> Oh no I think that means the response logic isn't the same for downloads vs not-downloads aaahhhh

It's worse even because one borrow button can currently lead to multiple download + read online options, and then the other one leads to something else I guess? So thinking about this more carefully, I don't think the labels "Borrow to read online" and "Borrow to read on a mobile device" are really accurate... I don't know what they should be because I don't know what the two different borrow urls are actually meant to represent

2020-09-01 14:21 UTC, M0nica commented on CHANGELOG.md
> +
Should this mention anything about the AxisNow functionality/dependency being added?

2020-09-02 08:50 UTC, kristojorg commented
Okay I got this to run, but can anyone give me a login so I can try the reading logic?

2020-09-02 08:57 UTC, kristojorg commented on .env
> +# AXIS_NOW_DECRYPT=true
My one thought here is that since we are using the `NEXT_PUBLIC_` prefix with the `NEXT_PUBLIC_COMPANION_APP` variable, I think we should do it with this one as well. It means we don't have to declare it in `next.config.js` as next.js will automatically expose it on the frontend (without `NEXT_PUBLIC_` or declaring it in `next.config.js` it is only available on the backend for security). 

What do you think? Should we switch this to that format or should we switch the companion app to not use it? I can see arguments for both. In the past we never had it, so the old env vars don't use it. It looks a little weird to someone not in the know who is setting those env vars, but at the same time it removes a source of bugs if we forget to declare an env var in `next.config.js`...

2020-09-02 09:13 UTC, kristojorg reviewed
Few comments, none of them blocking because everything does work, but I think these would be good to get in to a follow on if possible.

2020-09-02 09:13 UTC, kristojorg commented on src/hooks/useBorrow.ts
> +  const borrowOrReserve = async (url: string | undefined) => {
This doesn't need to go in to this PR, but we can make this function only take a `string` and then you don't have to throw the error if there is no url. You just deal with it higher up and probably don't display the button

2020-09-02 09:13 UTC, kristojorg commented on src/components/bookDetails/FulfillmentCard.tsx
> +import { BorrowOrReserve } from "components/BookList";
This is a small thing but this component shouldn't be in the `BookList` anymore if we are using it this way. Could you move it out into `/components`?

2020-09-02 09:13 UTC, kristojorg commented on src/components/BookList.tsx
> +        size="lg"
These buttons look pretty large to me on the page, is there a reason they need to be so big?

2020-09-02 09:13 UTC, kristojorg commented on src/components/BookList.tsx
> +    : "Reserve";
Again a small thing for now, but I think that this should be moved in to `useBorrow` as it's logic that is necessary any time we are letting people borrow.

2020-09-02 09:16 UTC, kristojorg commented
I think the main thing that needs to be fixed in a follow on PR is the logic around "Borrow to read online" vs "Borrow to read on mobile device". We need to move to a solution that we discussed with Leonard before this goes in to production, because that language is confusing and isn't accurate

2020-09-02 17:31 UTC, hokei commented on .env
> +# AXIS_NOW_DECRYPT=true
I'd go with the one that removes bugs, so I'll prefix NEXT_PUBLIC to this.  I think generally the person doing the configuration just rolls with stuff.

2020-09-02 21:00 UTC, hokei commented on src/components/BookList.tsx
> +    : "Reserve";
To do this I'd have to pass `isBorrow` and `borrowLink` into `useBorrow` -- is that standard? I thought hooks were supposed to pretty straightforward?

2020-09-03 11:29 UTC, kristojorg commented on src/utils/env.ts
> +  process.env.NEXT_PUBLIC_AXIS_NOW_DECRYPT;
I would take the opportunity to make this a boolean right here, that way you don't have to check `=== "true"` or `!!NEXT_PUBLIC_AXIS_NOW_DECRYPT`, which I don't think works the way you would expect it to (I think it would pass if it was `"false"`...

2020-09-03 11:30 UTC, kristojorg commented on src/components/WebpubViewer.tsx
> +      !!NEXT_PUBLIC_AXIS_NOW_DECRYPT,
This check will currently pass if it is `"false"`, so I would make the variable a boolean in `/utils/env`

2020-09-03 11:32 UTC, kristojorg requested changes
Okay just the one change on the env variable that I think is actually important because it won't work the way we expect currently (I think?). Other than that this looks ready to me!

2020-09-03 11:32 UTC, kristojorg commented on src/components/BookList.tsx
> +    : "Reserve";
Yea that's standard! you can def pass variables in to hooks

2020-09-07 08:36 UTC, kristojorg approved these changes
I think this is ready for an approval provided we can fix the CI issues and that we can have a follow on PR refining the "Borrow to read on Mobile" and "Borrow to read online" logic based on our conversation with Leonard. 

Please update the CHANGELOG before merging as well.

2020-09-08 14:28 UTC, merged